### ISSUE TITLE
Error if Comparison Data is not supplied in R backend

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#101]
I am running op.R without any comparison data supplied.  I am running a new set of emissions that have no outside comparison data.  

Error in list.files(COMPARISON_DATA, pattern = "*.csv$", recursive = T) : 
  object 'COMPARISON_DATA' not found

**Comment by bpbond** [comment]
Hmm. OK. I may come visit about this later if you are around. Note tied to #84
