### ISSUE TITLE
"Has the model output changed"?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#102]
We'd like a easy-to-use tool that verifies model output against some references, so you can be sure that your change didn't affect anything quantitatively. Currently I guess you could `diff` the model output against the sample files included in the repo, but this probably isn't satisfactory over the long term.

This is linked with #82

**Comment by rplzzz** [comment]
I've been using the diff method, but since the Windows standard library has trivial formatting differences from unix and mac libraries (1.23e+006 vs. 1.23e+06), you get a lot of spurious diffs.  It would definitely be good to have something better.

**Comment by bpbond** [comment]
Agreed. Re your baseline question on slack, that's a good one. Currently I guess those sample outputs files is all we have.

**Comment by cahartin** [comment]
I made a small change to the name of an output variable  (in consistent_ph_naming branch).  Can this be added to the 1.1 release?

**Comment by rplzzz** [comment]
Looks fine.  I'll merge it into the rc1.1 branch, and it can go in with the rest of the tweaks and tune-ups.

**Comment by bpbond** [comment]
This being handled by @dawnlwoodard 's `hectoreval` package.
