### ISSUE TITLE
Need to update sample output streams 

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#106]
Since we changed the case on the labels for the pH output, we now get bogus diffs between new runs and the sample outputs.  We need to update the samples.  While we're at that, does anybody object to running them with linux-style stdio (i.e., 1.23e+04 instead of 1.23e+004) this time around?

**Comment by cahartin** [comment]
@rplzzz  that seems fine to me.  I can rerun the sample outputs if you give me a little more background on the how to change the output (linux-style).

**Comment by rplzzz** [comment]
I've already run them on PIC.  I'll push them up shortly.
