### ISSUE TITLE
Need a reset capability

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#108]
Right now, the only way to restart a run from the beginning (_e.g._, to run an alternate emissions pathway, as GCAM does) is to tear down the core and instantiate a new one.  This is a bit of a tedious process, as it requires us to reparse the INI files, reattach visitors, and so on.  It would be better if we had the ability to call something like `hcore->reset()`, and that would cause the core and all of the components to reset themselves to their initial states.  This would be really helpful not just for IAM linkage, but also for Monte Carlo studies.

I've tentatively tagged this for v.1.2, but if that proves to be too ambitious, we could always kick it down the road a couple months.

**Comment by bpbond** [comment]
I definitely agree about the utility of this...so the reset message would revert the entire system back to the moment all input parsing is done, but before components' `prepareToRun` methods are called? Hmm, what's the cleanest/easiest way to implement this?

**Comment by rplzzz** [comment]
Yes, that's something we will have to decide.  The right answer depends on whether there is a case for doing other things between calling `reset()` and `prepareToRun()`, and that in turn depends on what `prepareToRun()` is doing, which I don't remember off the top of my head.

I think the most likely determiner will be whether or not `prepareToRun()` references parameter values.  If so, then, anticipating #109, we should give a code a chance to reset the parameters before calling `prepareToRun()`.  If not, then it would be better to roll it all together so that a call to `reset()` leaves you ready to run.

**Comment by rplzzz** [comment]
This is a dupe of #240 (or vice versa, if you prefer).  It was implemented in #243.
