### ISSUE TITLE
Setting model parameters via messages

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#109]
Hector model parameters, such as the ocean heat uptake parameters, `k_min`, `k_max`, and `t_mid` are set in the input (INI) files.  Therefore, if you want to run a different set of values you have to write a new INI file and set up a new Hector instance.  That's a little awkward, especially if you are doing something like a Monte Carlo run where you want to evaluate tens of thousands of parameter sets.  

It would be pretty easy to add this functionality to the `setData` message.  As far as I can tell, all we need to do is to have the components register the parameters they want to expose and then add handlers for those targets.

**Comment by bpbond** [comment]
Each component's `setData` is already used for the INI parsing step; by definition, if it's in the INI file, there's a handler for it already.

**Comment by rplzzz** [comment]
Yes, I was thinking that you would have to add a handler to `sendMessage()`, but it looks like all setData messages are routed to the `setData()` method.  However, you still have to make sure that the components register the parameters they want to expose with the core; otherwise, there is no way for the core to route the message to the correct component.  (The INI parser avoids this problem by calling methods on the components directly, rather than through the core.)

**Comment by cahartin** [comment]
@rplzzz is this issue taken care of now with the Rpackage?

**Comment by rplzzz** [comment]
Yes.  It's now possible for a component to register anything set in the ini file as an input that can be set via message.  Not all such parameters are currently registered (none of the ones mentioned above are), since I've been adding them as needed.  Adding a new one is easy to do; it only takes a couple lines of code.
