### ISSUE TITLE
Terminology question on CO_2 emissions

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#111]
In Hector CO_2 emissions are declared like 
```INI
; Anthropogenic contributions: direct emissions and land use change, Pg C/yr
anthroEmissions=csv:emissions/RCP26_emissions.csv
lucEmissions=csv:emissions/RCP26_emissions.csv 
```
Having worked mostly with MAGICC before (I work at PIK in a group originally started by Malte Meinshausen) where they are called "FossilCO2" and "OtherCO2" I was a bit confused by the "anthro" part. 
Isn't land use change also (at least partly) "anthropogenic"?
In the RCP database they are called "Fossil fuels and industry" and "Land-use change".

**Comment by bpbond** [comment]
That's a good point--I agree, `anthroEmissions` is ambiguous. I'd support renaming this to `fossilEmissions`, or something like that, especially if that makes the corresponding RCP category clearer.

I'd suggest that for now (starting with upcoming 1.2) we allow either `anthroEmissions` or `fossilEmissions`, but print a warning message that the former is deprecated. At version 2.0, we drop `anthroEmissions` entirely.

@cahartin ?

**Comment by cahartin** [comment]
@bpbond  I agree with those changes.   AnthroEmissions doesn't really help the user at figuring out what they are exactly. I think for a v1.2 a total name change is a good idea.

**Comment by rgieseke** [comment]
How about

CO2_ffi_emissions or CO2_fossil_emissions
and
CO2_luc_emissions

to be more similar to the other gases? Ending all gases with "_emissions" would also simplify dropping "_emissions" from the column names when reading the CSV into a R or Python/Pandas data frame.

**Comment by bpbond** [comment]
Addressed; closing.
