### ISSUE TITLE
Exception error message never shown

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#112]
I never get to see the exception error messages like the one here in [init_to_core_reader](https://github.com/JGCRI/hector/blob/master/source/input/ini_to_core_reader.cpp#L70)
for CSV files not found.

Commit https://github.com/JGCRI/hector/commit/6c1d73d595fe741b5369be41ff8964eea5ab3442#diff-bfd574051572855ffede390ec872fc68L84 commented catching `h_exception` out, was there a particular reason for that?

**Comment by rplzzz** [comment]
I commented out the exception catching because I was doing some debugging where it was really helpful to get a stack trace from the frame where the exception was thrown, which you can't easily do if the exception is caught.  For production code we should probably put it back in.

**Comment by bpbond** [comment]
Whoah, yes. I'm having nasty flashbacks to all the GCAM asserts that wherein the code, but didn't actually do anything.

**Comment by bpbond** [comment]
Fixed in commit 410b1b1, so closing this.
