### ISSUE TITLE
Clean up Xcode and Visual Studio project files

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#114]
We'd like more flexible symlink'd libraries, updated* project files, etc.

\* TBA

**Comment by bpbond** [comment]
@cahartin please reference this issue when you commit your new VS15 project files.

**Comment by cahartin** [comment]
@pralitp:  I'm cleaning up the issue list and I'm pretty sure you made new project files recently...

**Comment by bpbond** [comment]
Closing this, as both @cahartin (for VS) and I (for Xcode) have committed project file updates recently.
