### ISSUE TITLE
Output is silently discarded if `./output` does not exist

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#115]
We dealt with a similar problem pertaining to the log files in #39.  This variant never surfaced before because when we ran from the hector install directory the output directory already existed and was populated with sample outputs.  Now that we can easily run from other locations, we see this unwanted behavior.

**Comment by bpbond** [comment]
If we start to use `boost::filesystem` (see issue #110 ) then we should be able to easily test for `output/` and create it if necessary, right?

**Comment by rplzzz** [comment]
Yes.  While we are at it, we should probably backport that to the code that creates the logs directory.  If you'll recall, not having a cross-platform way to test for the directory's existence caused us some windows problems that we sort of punted on.

**Comment by ashiklom** [comment]
Necrobumping because I just ran into this problem trying to figure out why I wasn't getting any CSV output. For now, we should add a note to the documentation wiki indicating that an `output` directory is required. I can open a PR about that once I figure out how to edit the wiki locally.

**Comment by ashiklom** [comment]
I just added a note to the [wiki](https://github.com/JGCRI/hector/wiki/OutputFiles) warning future users about this. Once we resolve this bug, we should remove that note.

**Comment by rplzzz** [comment]
Right, you probably ran into this because you were working on the rcpp branch, where `output` has been moved to `inst/output`.  

I think another thing we should be doing here is giving users a choice about where to write the output, rather than always assuming that they're ok with the default output directory.

**Comment by rplzzz** [comment]
Adding it as a second (optional) command line argument seems like the right thing to do.  It's easy enough to do, and it only affects the wrapper code.

**Comment by bpbond** [comment]
I'm fine with that, but it would be good to have a coherent and consistent philosophy about what options go where.

**Comment by rplzzz** [comment]
This particular option is only relevant to the stand-alone version of the model (when you run from GCAM, or R, or pyhector you have to create the visitors yourself, so you have direct control over where they write their data) .  Because of that, it makes sense to put it in the command line arguments, which are only used by the stand-alone version.

**Comment by NatasjaF** [comment]
Hi everyone.

Just started with Hector run from R  (also not very experienced) in Windows and facing the same issue. 
I created an `output` directory ( `hector/output` )  but I still do not get any .csv output files.  
I can plot the results for RCPs but I can't find the files where the results are stored. What could be wrong?!

**Comment by bpbond** [comment]
Hi @NatasjaF , are you working in R? Or building the command-line version of the model?

**Comment by NatasjaF** [comment]
Hi, I am working in R.

**Comment by bpbond** [comment]
I'm sorry—you said that in your original message! 🤦  Yes, when run through R the model doesn't create output files at all. You should retrieve any outputs you want using the `fetchvars()` function, as demonstrated in the [introductory vignette](http://jgcri.github.io/hector/articles/intro-to-hector.html).

**Comment by NatasjaF** [comment]
I was actually wondering if I need to save those outputs for comparison between RCPs / change of parameters etc after exiting R, should I do that manually for each run then (through write.csv) since they are not created?

**Comment by bpbond** [comment]
Yes, you'll want to 
* Create a hector core
* Run your scenario
* Extract output data and save in some way
* Reset the core OR shut it down and then re-create for the next run

You can see examples of this in the second part of the basic vignette, link above.

**Comment by NatasjaF** [comment]
Clear, thank you!

**Comment by kdorheim** [comment]
Addressed at part of #548 thanks @pralitp!
