### ISSUE TITLE
Visual Studio - unsafe build errors

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#117]
There are 3 places in the code that VS throws a warning/error about certain functions being unsafe. As a work around, under Hector properties, we told VS to ignore those particular error messages.  It may be useful to address these errors for future releases of Hector. 

Error messages:

'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
line 59 of csv_table_reader.cpp

'std::_Copy_impl': Function call with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
line 2230 vc/include/xutility

'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
line 251 logger.cpp

**Comment by kdorheim** [comment]
@pralitp do you think this may be related to #415? Or is it okay to close?

**Comment by kdorheim** [comment]
@pralitp okay to close?
