### ISSUE TITLE
table reader needs to be robust to Excel

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#12]
Critical    Excel makes shitty line endings, but people will use it; table reader needs to be robust    N   csv_table_reader.cpp    17  Ben Ben/Pralit  Open

**Comment by cahartin** [comment]
add to a help page about this for future use. caution people about using MAC OS9

**Comment by kdorheim** [comment]
@bpbond is this issue still relevant?

**Comment by bpbond** [comment]
Five years later and I haven't heard anyone complain about this, so let's say no.
