### ISSUE TITLE
Hector output when csv file not found is spectacularly unhelpful

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#124]
When you compile with g++ 5.X, if your input file tries to read data from a file that doesn't exist, you get:

```
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
```

which doesn't actually help you track down why your run failed.  The problem seems to be that trying to catch `std::ios_base::failure` doesn't work, due to this bug in g++:  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66145

Allegedly this will be fixed in g++ 5.3, so maybe the answer is to stand pat and wait for gcc to get fixed, but I thought we should at least document the behavior so that nobody else wastes as much time as I did tracking this one down.

**Comment by bpbond** [comment]
Ugh. Adding to v1.2 milestone.

**Comment by rplzzz** [comment]
Like I said, this is actually a bug in g++.  Let's wait and see if it is fixed in g++ v. 5.3.  It should be out fairly soon:  https://gcc.gnu.org/ml/gcc/2015-11/msg00113.html

**Comment by bpbond** [comment]
I checked and this doesn't occur for me (that is, Hector prints a nice file-not-found error message). @rplzzz at your leisure, can you check to see whether this has been fixed yet for you?

**Comment by rplzzz** [comment]
What version of g++ did you do your test with?

**Comment by rplzzz** [comment]
Ok, after doing some more tests, I can confirm that the bug is still present in g++ v. 6.1.0.  The bug tracker in the original issue report now lists the target milestone for the fix as gcc v. 7.  It probably doesn't help that the guy in charge of fixing the bug thinks that "using exceptions in iostreams is dumb", so we'll have to wait and see.  GCC 7 is due out in "March or April" of this year.

**Comment by bpbond** [comment]
@rplzzz my bad. I tested the clang executable, not that built by gcc.

**Comment by rplzzz** [comment]
[Allegedly fixed in GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66145#c36), and even if it's not, there isn't much we can do about it.
