### ISSUE TITLE
Probabilistic climate runs

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#125]
At the meeting today, Jae presented some results from MAGICC run in probabilistic mode.  Hector should have a similar mode so that we can produce "X% chance of temperature change <Y degrees" results for IA scenarios.

We should find out what factors MAGICC includes in its probabilistic runs and start implementing them one by one in Hector.

**Comment by bpbond** [comment]
I've done this for Corinne's "ocean acidification" project. It consists of three R scripts that (i) sample input variables from defined PDFs, (ii) substitute those values into Hector's inputs, run, collect outputs, and (iii) collect and summarize outputs. Support parallelized runs.

**Comment by cahartin** [comment]
this capability is currently being undertaken by our subcontract with UIUC.
