### ISSUE TITLE
Getting Hector to Run

### ISSUE THREAD

**Issue by djtrainwreckx** [JGCRI/hector#126]
I am having trouble running Hector on Windows 7. I am up to the second to last bulletin on Windows wiki steps. I open up the " ALL_BUILD.vcxproj" file in Visual Studio and then I don't know where to go from there. How do I change the VS target to DEBUG and to RELEASE. 

-- Thank you!

**Comment by bpbond** [comment]
Hi @djtrainwreckx I don't work on a Windows box, but from Google, it looks like the basic procedure is as follows?

**To change the target Framework**
1. In Visual Studio, in Solution Explorer, select your project. ...
2. On the menu bar, select File, Open, File. ...
3. In the project file, locate the entry for the target Framework version. ...
4. Change the value to the Framework version you want

That said, I or someone will double-check this later today and update this post.

**Comment by djtrainwreckx** [comment]
Thank you so much for replying, I finally understand what it means to open it up on Solution Explorer. This is what I get when I open it up on solution explorer. 

![capture1](https://cloud.githubusercontent.com/assets/15677829/11577233/6a2a1edc-99ea-11e5-9b18-1af174a18ad8.PNG)




However, on step 3, I don't really know what is the Framework version I looking for that the Wiki for Hector is referring to. In the wiki it says to go to the debug folder, which I have, but is empty, and chose the "All Build" file, which is outside of the debug folder. Once I click on that file, I'm lost where to go. 

![capture2](https://cloud.githubusercontent.com/assets/15677829/11577322/fa5ddf02-99ea-11e5-8555-aa1c72e9a52d.PNG)


I'm sorry I feel like I am stuck on what might be something silly. 

On a side note, assuming I have finished these steps, how do I actually use Hector, how do I get it running?

**Comment by pralitp** [comment]
Yes, I think we can make the instructions a bit more clear here.  You are correct the ALL_BUILD is located outside of the Debug or Release folders.  Also initially the Debug and Release folders will be empty.

Once you double click on the project file it will open it in Visual Studio.

To change your build configuration from Debug to Release there should be a drop down right on the main toolbar.  You will want to build the library for each.  To build the Library select from the menu bar:
"Build" -> "Build Solution"

This will compile the library for all sub projects.  Again be sure to do this in both Debug and Release configurations.

Once this is done you can find the resulting .lib files in the "Release" and "Debug" folders at the same level as ALL_BUILD.vcxproj

**Comment by bpbond** [comment]
@djtrainwreckx did that fix things for you?

Note that we're also happy to accept suggestions on improving the Hector documentation and wiki.

**Comment by silva-diego** [comment]
Hello,
I am having trouble installing Hector. I followed the instructions in the wiki but I am getting the following error when building the hector project in VS2015.

Error C2679: binary '=': no operator found which takes a right-hand operand of type 'const boost::filesystem::path::value_type *' (or there is no acceptable conversion)	
File: c:\hector\hector-master\project_files\vs15\hector\hector\source\input\ini_to_core_reader.cpp
Line: 129

My system is Windows 8.1 64-bit. I tried the solution in both "x86" and "x64" platforms. 
Thank you.

**Comment by bpbond** [comment]
Hi @silva-diego - we ran into this recently too. A fix has been committed to one of our release candidate branches but is not yet in `master`, and involves changing a single line in `source/input/ini_to_core_reader.cpp`. See commit 2c2e1428a. Let us know if this doesn't fix your issue.

**Comment by rplzzz** [comment]
This seems like a pretty important fix.  It's on a branch with patch-level changes, so we should probably just merge them and make the next patch-level release.

**Comment by bpbond** [comment]
Agreed. `rc1.1.3` has this VS fix, as well as Hector-returning-0-even-on-error fix. Both small but important.

**Comment by rplzzz** [comment]
Ok, do you want to do the honors?

**Comment by bpbond** [comment]
Sure, it's kind of been my thing today.
