### ISSUE TITLE
Negative temperature response from a BC pulse

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#127]
From Adria Schwarber's work, we found the following:  
In panel C, a pulse of BC in one year leads to an increase in temperature (as expected) but then a sharp negative response (not expected). I am looking for any ideas on what could be causing this and what are some starting points to further investigate this.
![bc_temp](https://cloud.githubusercontent.com/assets/7500729/12153328/64276398-b487-11e5-92f9-461203a4d166.png)

**Comment by cahartin** [comment]
Inclusion of doeclim temperature component fixes this issue of a negative temperature response. 

![image](https://cloud.githubusercontent.com/assets/7500729/22309789/c5bbb5d8-e31a-11e6-86b2-619a872d4775.png)

**Comment by rplzzz** [comment]
I'm not so sure I'd consider this issue solved just yet.  The stock Hector temperature component produces temperature proportional to forcing (subject to the CO<sub>2</sub> lag correction).  Therefore, the negative response has a corresponding negative response in the forcing component, and as I understand it, doeclim is simply masking that response, not actually fixing it.  We need to look for the cause in the BC component's calculation of its forcing and/or concentration and fix whatever we find there.

**Comment by cahartin** [comment]
I did a significant amount of debugging this issue last year.  This response happens for any species we perturb, not just BC (BC was just used as an example). The issue is that when hector's temperature spikes the ocean took up too much heat in that year, causing the temperatures in the next year to drop.  The system shouldn't behave in that sense.  I do agree that this is not entirely 'fixed' but it's a step in the right direction.

**Comment by cahartin** [comment]
[pulse_doeclim_plots.zip](https://github.com/JGCRI/hector/files/761772/pulse_doeclim_plots.zip)

**Comment by cahartin** [comment]
fixed with the addition of DOECLIM heat component
