### ISSUE TITLE
Improving Hector's performance

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#137]
It would be good to run Hector through a profiler to identify, and ideally improve, expensive (slow) parts of the code.

See also "Hector command line options" #69  - suppressing all output would help here.

**Comment by rplzzz** [comment]
With logging disabled, a hector run through 2300, including spinup, (but not including reading the ini file) takes about 250 ms.  We could maybe find something to squeeze out of there, but at this point even the Monte Carlo runs can be run in about as much time as it takes to have a decent coffee break.

```
> microbenchmark::microbenchmark({reset(hcore); run(hcore)})
Unit: milliseconds
                                expr      min       lq     mean   median       uq      max neval
 {     reset(hcore)     run(hcore) } 234.6876 243.8912 248.8542 247.4879 251.9418 279.0081   100
```
