### ISSUE TITLE
Incorrect library path in makefile

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#138]
In `source/Makefile` there's the following line:

>BOOSTLIB = $(BOOSTROOT)/stage/lib

This is (I'm pretty sure) incorrect. When you install boost (via `./b2 install`) it moves the Boost libs from e.g. `boost_1_60_0/stage/lib/` into `$(BOOSTROOT)/lib`, which is the path that should appear here. (As written, the make errors out at this point.) I haven't changed in `master` yet–please confirm @rplzzz .

**Comment by rplzzz** [comment]
Whenever I've built boost, it's always left the libraries in the stage directory.  Perhaps I'm building it wrong.

**Comment by cahartin** [comment]
On the VS end the libraries are also in the stage directory.

**Comment by bpbond** [comment]
Right, the files are still in `stage`; my comment above should have said _copies_ not _moves_. But as its name implies, that is a staging directory, and sits in the download folder that presumably will be deleted (and which has a Boost version-specific name, breaking any previous definition of $BOOSTROOT).

See the install directions (http://www.boost.org/doc/libs/1_60_0/more/getting_started/unix-variants.html#easy-build-and-install) - you're clearly supposed to build everything (via `bootstrap.sh`) and then install (via `b2.sh`) into `/usr/local` or some other place of your choosing.

**Comment by rplzzz** [comment]
Moving to /usr/local is fine for people running on workstations, but people running on shared systems won't have write access to that.  Or are you saying that we should instruct users to set their installation prefix to $BOOSTROOT?

**Comment by bpbond** [comment]
Now I'm doubting myself. I think (1) people should install Boost following the instructions:
>Select your configuration options and invoke ./bootstrap.sh again without the --help option. Unless you have write permission in your system's /usr/local/ directory, you'll probably want to at least use
>
>$ ./bootstrap.sh --prefix=path/to/installation/prefix
>
>to install somewhere else. Also, consider using the --show-libraries and --with-libraries=library-name-list options to limit the long wait you'll experience if you build everything. Finally,
>
>$ ./b2 install
>
>will leave Boost binaries in the lib/ subdirectory of your installation prefix. You will also find a copy of the Boost headers in the include/ subdirectory of the installation prefix, so you can henceforth use that directory as an #include path in place of the Boost root directory.

...and then (2) set BOOSTROOT to whatever that installation prefix path was specified (yes by default `/usr/local` but can be anywhere).

**Comment by bpbond** [comment]
P.S. This way, when Boost is updated, there's no need to touch the makefile setting.

**Comment by rplzzz** [comment]
The Boost location is communicated to the makefile via an environment variable, so there's never really a need to touch the makefile.  Installing to a prefix does mean you can update without even resetting an environment variable, but I'm not sure that's a positive.  What if one program wants a newer version of boost, while some other one prefers to stick with the older version?  

I don't really have strong feelings one way or the other, but whatever we do we need to clarify what users are expected to do with Boost because what we have now is a little confusing.  I think many of the assumptions about Boost still date back to the days when we were using the header libraries only, and so we didn't expect users to install Boost anywhere.  They were meant to just unpack the distribution, set the relevant environment variables, and run.

**Comment by bpbond** [comment]
Agreed - whatever we do, should be consistent and clear.

**Comment by cahartin** [comment]
@bpbond and @rplzzz  did we end up fixing this issue?  can we close?

**Comment by rplzzz** [comment]
I don't think we ever came to a firm conclusion one way or the other.  In addition to everything discussed above, we should probably ensure that we do things the same way we do them in GCAM; otherwise people will wind up having to have two copies of the boost libraries.

**Comment by bpbond** [comment]
The current Makefile runs as smooth as butter on Travis-ci. I think we can close this.

**Comment by rplzzz** [comment]
Excellent.  I love it when a plan comes together.
