### ISSUE TITLE
Overloaded macros

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#142]
From @pralitp -

>We ran into a problem with this in Hector where an overloaded H_ASSERT was failing on visual studio while worked just fine on other compilers. As a work around we just decided not to use overloaded macros.
>
>Looks like boost provides a wrapper which can work around Visual Studio’s deficiencies in case we want to bring them back:
>http://www.boost.org/doc/libs/1_60_0/libs/preprocessor/doc/index.html

**Comment by rplzzz** [comment]
Do we really need this capability?  Seems like it introduces a lot of additional complexity for little gain.

**Comment by bpbond** [comment]
Fine by me. Closing.
