### ISSUE TITLE
do_spinup flag error

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#146]
When setting do_spinup to 0 (do not run Hector in spinup mode), Hector fails with an error:
`* Program exception: Assertion failed: variable is not of this type`
`* Function Hector::unitval::value, file unitval.hpp, line 213`

**Comment by bpbond** [comment]
Hmm, looks like it's the ocean's fault...

**Comment by bpbond** [comment]
Added no-spinup test re issue #164

**Comment by bpbond** [comment]
Closing pending PR #166
