### ISSUE TITLE
Windows mklink and boost-lib

### ISSUE THREAD

**Issue by mgior** [JGCRI/hector#157]
I've gotten boost successfully installed but this part of the Install and Build directions isn't very descriptive:

"Currently the Hector repository includes a VS project file, but not the symbolic links to the model's source and headers directories you'll need to create in project_files\VS\hector. Create them using mklink."

Does this mean there should be a symbolic link in ....\hector\project_files\VS that points to ...\boost? Should they be in the source and header directories that point to \boost or somewhere else? Should the link be named boost or boost-lib? Both? Should mklink be done with the \d flag to make it a directory link instead of a file link (which is default)?

I've tried all combinations of the above but I am still getting "Cannot open inlcude file:'boost/(e.g. lexical_cast.hpp)': No such file or directory" errors when I try to build hector in VS 2015.

**Comment by bpbond** [comment]
Hi @mgior - agreed, that could be clearer. I've never built the Windows version but it sounds like you want to
* change into the `project_files\VS\hector` directory
* `mklink source path/to/hector/source`
* `mklink headers path/to/hector/headers`

**But the error you're getting doesn't relate to this** (I don't think). Instead, it sound like the compiler isn't finding the Boost header files, which is a different issue. Have you verified that the correct Boost header directory is in the Visual Studio search path? See http://stackoverflow.com/questions/2676417/how-do-include-paths-work-in-visual-studio.

**Comment by pralitp** [comment]
Yes, the documentation isn't particularly clear here.  The idea is to have a libs directory at the top level of the hector repository:
```
07/26/2016  11:58 AM    <DIR>          .
07/26/2016  11:58 AM    <DIR>          ..
07/26/2016  11:09 AM               755 .gitignore
07/26/2016  11:09 AM                83 .gitmodules
07/26/2016  11:09 AM               629 changelog.txt
07/26/2016  11:09 AM             3,057 CONTRIBUTING.md
07/26/2016  11:09 AM    <DIR>          headers
07/26/2016  11:09 AM    <DIR>          input
07/26/2016  11:16 AM    <SYMLINKD>     libs [E:\common\libs]
07/26/2016  11:09 AM            15,518 LICENSE.md
07/26/2016  11:58 AM    <DIR>          logs
07/26/2016  11:09 AM                35 Makefile
07/26/2016  11:09 AM    <DIR>          old
07/26/2016  11:58 AM    <DIR>          output
07/26/2016  11:09 AM    <DIR>          project_files
07/26/2016  11:09 AM    <DIR>          R
07/26/2016  11:09 AM             1,562 README.md
07/26/2016  11:09 AM    <DIR>          source
07/26/2016  11:09 AM    <DIR>          wiki
               7 File(s)         21,639 bytes
```

And within the libs you can symlink (or just rename) `boost_1_NN_N` to boost-lib.

This is where the visual studio project as committed is expecting to find the boost headers.

Alternatively you could simply (for which ever targets you need) change the "Additional Include Directories" in the project properties as @bpbond has suggested.

I do not believe the other mklink commands are necessary at this point.

**Comment by bpbond** [comment]
Ah, that documentation does need fixing then. Tagging @cahartin for this.

@mgior - let us know if @pralitp 's answer solves things, or if we can provide further clarification.

**Comment by mgior** [comment]
All, thank you for clearing up the mklink directions, that makes some sense now.

As for the boost header directory, I found a couple of problems that I seem to have resolved:

1) the default bootstrap command does not build the correct libraries for boost_1_62_0 and VS2015. You may want to consider linking the following site on the directions to get boost to properly compile: https://studiofreya.com/2016/09/29/how-to-build-boost-1-62-with-visual-studio-2015/

2) In VS2015 the boost libs are pointed at by editing property pages, not like how they are pointed at in previous VS's (apparently). Again, another link: https://studiofreya.com/2016/06/25/how-to-use-cpp-boost-library-in-visual-studio/

3) In contrast with link 2, I was not able to get the symbolic (maybe the wrong word) directories to work in VS 2015 to point towards the correct boost libs. I don't know if this is because I am on a x64 machine and have x64 VS installed but hector is looking for the win32 libs, but I had to point to C:/..../win32/libs instead of $(SolutionDir)boost_1_62_0\stage\$(Platform)\lib\

3.5) also worth noting that in VS2015, you have to point both "hector" and "hector-lib" to the boost libs via the solution explorer property pages as per point 3.

**Comment by mgior** [comment]
Followup question I feel silly for asking: there doesn't seem to be any documentation on how to actually run hector. The only statement I can find is: "When Hector is invoked from the command line, it takes a single parameter: the name of the primary input file to read."  I tried calling hector.exe in cmd but get the error:
* Program exception: Unable to open log file logs/hector.log
* Function Hector::Logger::open, file logger.cpp, line 149

Also, what is the syntax for calling in the command line? (program.exe) --(input file name)?
E.g. hector.exe --hector_rcp26.ini


Thanks, sorry for the dumb questions!

**Comment by cahartin** [comment]
hi @mgior,  Thanks for the comments, I'll be sure to incorporate them into the instructions. 

try `source/hector input/hector_rcp26.ini` to run Hector.

**Comment by pralitp** [comment]
In addition I wonder if the error about `Unable to open log file` is really because the `logs` directory doesn't exist and Windows unlike other platforms will not create it for you?  Could you try to create an empty `logs` directory and see if that fixes it?

**Comment by mgior** [comment]
Thanks again for the help everyone, it is much appreciated! I seem to be up and running now. One more question though: output of the runs are supposed to go to /logs, correct? The /output directory that is from the github download is just a folder to house the sample outputs, correct? Is there any command line parameter where we can specify where the output should go?

@pralitp creating a logs file under hector/project_files/VS/release fixes the issue
@cahartin I got it running without the "/source" as long as I cd'd into project_files/VS/release

**Comment by cahartin** [comment]
@mgior Happy to hear you are up and running.  The model output will be in the `/outputs` folder.  We include the sample output as reference.  You should have a file `outputstream_NameOfRun.csv`.  The `log` folder will contain the log for each model component.

**Comment by mgior** [comment]
@cahartin got it, I also had to mklink/d a symlink to the /outputs folder...I guess I could have also just made another outputs folder in project_files/vs/release. Worth noting that there is no error thrown if /outputs is not found though.

**Comment by FrankErrickson** [comment]
Just built Hector and got it running on a Windows setup.  I actually ran into the same issue with the `logs` directory not being created, leading to the `unable to open log file` exception.  This would not have been an obvious fix to me without finding this Issue thread. It would be helpful just to throw a link to this issue in the BuildHector Wiki for Windows users.

**Comment by bpbond** [comment]
Thanks @FrankErrickson ! Will do.

**Comment by rplzzz** [comment]
We should go a step further and create a windows setup script that does all of these one-time tasks like creating the symbolic links and the logs directory.  Then we could just instruct people to run that at installation time, and that would side step many of these issues.

**Comment by ashiklom** [comment]
Now that #282 is in, I think a lot of this is irrelevant. Can it be closed?

**Comment by bpbond** [comment]
Agreed.
