### ISSUE TITLE
My travis-ci account not updating

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#159]
I've added continuous integration to Hector ( #158 ) but for some reason my Travis account isn't correctly updating (I've actually submitted an issue to them about this, see https://github.com/travis-ci/travis-ci/issues/6734).

Could one of you - @pralitp @rplzzz @cahartin - try logging into http://travis-ci.org using your GitHub credentials and turn "on" Hector CI? It should build on the Travis VM, and if it does, we can update the badge on the Hector homepage.

**Comment by rplzzz** [comment]
I logged in, and CI for Hector was already there, but it was erroring because it couldn't find a branch called "ci".  I'm not terribly familiar with Travis, so I don't exactly know how to fix this, but it sounds like we need to change the branch being tested to "master" (like it is in RCMIP5).

**Comment by bpbond** [comment]
Yeah, that's the same for me. Argh. I don't know why it's stuck looking for this, and not updating the branches correctly (it doesn't display `master`, and `ci` doesn't even exist anymore).  👎
