### ISSUE TITLE
Methane radiative forcing

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#161]
**Radiative forcing of carbon dioxide, methane, and nitrous oxide: A significant revision of the methane radiative forcing**

>New calculations of the radiative forcing (RF) are presented for the three main well-mixed greenhouse gases, methane, nitrous oxide, and carbon dioxide. Methane's RF is particularly impacted because of the inclusion of the shortwave forcing; the 1750–2011 RF is about 25% higher (increasing from 0.48 W m−2 to 0.61 W m−2) compared to the value in the Intergovernmental Panel on Climate Change (IPCC) 2013 assessment; the 100 year global warming potential is 14% higher than the IPCC value. We present new simplified expressions to calculate RF. Unlike previous expressions used by IPCC, the new ones include the overlap between CO2 and N2O; for N2O forcing, the CO2 overlap can be as important as the CH4 overlap. The 1750–2011 CO2 RF is within 1% of IPCC's value but is about 10% higher when CO2 amounts reach 2000 ppm, a value projected to be possible under the extended RCP8.5 scenario.

http://onlinelibrary.wiley.com/doi/10.1002/2016GL071930/full

**Comment by mnichol3** [comment]
Here is a comparison of the current radiative forcings produced by Hector (eqs. from Joos et al., 2001) and the radiative forcings calculated using the equations in Etminan et al., 2016: 

![rf_eq_compare](https://user-images.githubusercontent.com/15006171/72647816-6947dd00-3947-11ea-9d9a-72184e739723.png)

The calculations used co2, ch4, & n2o concentrations from a "default" Hector run using the rcp45 ini file.

Are the forcings from the newer equations satisfactory? If so, shall I implement them within Hector's forcing component code?

The code for the updated RF calculations can be found [here](https://github.com/mnichol3/my_jgcri/blob/master/hector/scripts/test/update_ch4_rf.py). For transparency, [here](https://github.com/mnichol3/my_jgcri/blob/master/hector/scripts/test/plot_rf.py) is the plotting script.

**Comment by ssmithClimate** [comment]
@mnichol3 looks good! I suggest as a validation to plug in a specific concentration value pulled from Figure 2 of Etminan et al. for CH4 and N2O and compare with values on the graph there just as a double check.

**Comment by mnichol3** [comment]
@ssmithClimate [this script](https://github.com/mnichol3/my_jgcri/blob/master/hector/scripts/test/validate_rf.py) uses the radiative forcing equations (implemented in the scripts used to produce the above plots) and concentrations from Etminan et al., 2016's [supplemental information table S1](https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2F2016GL071930&file=grl55302-sup-0001-Supplementary.pdf) to calculate the radiative forcings, then compares them to the forcings given in table S1. 

After rounding the calculated forcings to the nearest hundredth to match the precision in table S1, the forcings for all three species are identical to those given in the table

**Comment by ssmithClimate** [comment]
@mnichol3 that's great!

**Comment by kdorheim** [comment]
Closed with #536
