### ISSUE TITLE
Better tests!

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#164]
After fixing #147 - it would be great to include more and better tests, now that we have Travis CI working. To-do list includes:

- [x] All four RCPs
- [x] Atmospheric CO2 constraint run
- [ ] Ocean-atmosphere C exchange constraint run
- [x] Temperature constraint run
- [x] Radiative forcing constraint run
- [x] Change run start and stop dates
- [x] Spinup and not spinup

**Comment by bpbond** [comment]
Probably create a `travis_tests/` directory, and the script runs any INI files inside of it.

**Comment by bpbond** [comment]
Tagging @cahartin re the ocean-atmosphere constraint run missing file - see PR #165

**Comment by rplzzz** [comment]
FYI, we now run an extensive suite of tests including all of the standard scenarios, changes to the major model parameters, and changes to emissions.  Does that answer the mail for this issue?

**Comment by bpbond** [comment]
I think it's pretty solid at this point, agreed.
