### ISSUE TITLE
Better onelineocean component

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#167]
[Hurrell et al. (2013)](http://journals.ametsoc.org/doi/abs/10.1175/BAMS-D-12-00121.1) show a graph of ocean uptake in CESM relative to atmospheric CO2:

<img width="345" alt="screen shot 2017-01-18 at 12 52 20 pm" src="https://cloud.githubusercontent.com/assets/1956468/22076201/171116e2-dd7d-11e6-8e2d-67cd545d8a21.png">

**Fig. 9. (a) Temporal evolution of CO2 sources, prognostic sinks, and the time tendency of atmospheric CO2 for historical and RCP 8.5 conditions. Evolution of (b) ocean and (c) land CO2 uptake under idealized 1% yr−1 ramping CO2 integrations. Solid lines show results from integrations in which both the radiative transfer and CO2 flux calculations use the prescribed ramping CO2 concentration...**

We could fit a curve to this solid line and have a pretty robust, one line ocean model, better than what we have now. Here are the relevant numbers (measuring to axes, should be quite accurate):

CO2 | Flux
------------ | -------------
300 |	-1
350 |	-2.8
400 |	-3.5
500 |	-4.3
600 |	-4.65
700 |	-4.8
800 |	-4.95
1000 |	-5

**Comment by rplzzz** [comment]
Is this something we really want?  I've always assumed that the existing "onelineocean" component is relict of the early days of hector testing and therefore something we should get around to removing someday.  Is there some sort of advantage to including an alternate ocean component?  If not, then I think we should pass on this development.

**Comment by bpbond** [comment]
Seems reasonable to me.
