### ISSUE TITLE
Revamp R backend

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#168]

**Comment by bpbond** [comment]
Specifically, current scripts are in poor shape: fragile, not well documented, use out-of-date R packages.

**Comment by cahartin** [comment]
@kdorheim is working on re-analyzing the CMIP5 data using CDO.

**Comment by rplzzz** [comment]
One of the things I would like to do is to put together an R package that provides R bindings for Hector API functions.  Maybe the thing to do with these functions is to put them into that package, which would then provide a one-stop shop for running Hector and analyzing the results.

**Comment by bpbond** [comment]
👍  Good idea.

**Comment by rplzzz** [comment]
Been there.  Done that in 7f5938b
