### ISSUE TITLE
Output file format

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#169]
I might have overlooked it but if doesn't exist, do you have an overview of the fields in the output streams and their meaning?

It's of course possible to look at the source but this might be helpful for others, e.g. to quickly find global temperature (it took me a while to find the differences between Tgav, Tgaveq, Temp_HL/LL ...)

**Comment by rplzzz** [comment]
Good point.  The wiki has a link called [output files](https://github.com/JGCRI/hector/wiki/OutputFiles), but the page hasn't been created yet.  This would be a good place to provide a detailed description of the format and contents of the output.

**Comment by rgieseke** [comment]
Thanks! I added an alphabetical list there as a start.

**Comment by bpbond** [comment]
As part of this, document the what "year" means! See #177

**Comment by cahartin** [comment]
i updated the wiki with this information.  It would be good for us to revisit this after each release.
@rgieseke thanks for the alphabetical list. I already had a file written in the order they appear in the outputstream.  I can always rearrange if its easier alphabetically.

**Comment by rgieseke** [comment]
Thanks! Having it ordered by Component is much better.
