### ISSUE TITLE
INI parser and equals signs

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#17]
Minor   INI parser needs to be robust to spaces around csv= N           Ben     Open

**Comment by ashiklom** [comment]
Is this still relevant? In the current INI format, we use `csv:/path/...` rather than `=`.

Also, I'd personally rather be strict and explicit (i.e. we would need to add documentation) about not having spaces before or after the `:`.

**Comment by bpbond** [comment]
Not really, and even if yes, let's wait for it to be demonstrated to be a _problem_.
