### ISSUE TITLE
Make logging into files optional

### ISSUE THREAD

**Issue by swillner** [JGCRI/hector#171]
Currently, logging is always writing into log files. Since that takes some amount of running time, it would be great to have that optional.
I have a code solution proposal on that, but do not know which branch to use for the pull request. Also, I would include a compile-time switch for writing logging to files for the debug loggers used in the components.

**Comment by bpbond** [comment]
This is somewhat related to #69 (which proposes, among other things, a 'quiet' command line switch).

I very much agree about the need for this functionality. @swillner can you briefly describe your proposal here? I think we'd ask you to target the `rc1.2` branch.

**Comment by bpbond** [comment]
Note that we'd really like a solution that's runtime (INI or command line setting), not only a compile-time one, I think. @rplzzz ?

**Comment by rplzzz** [comment]
Do we not have logging levels that we can use to control how much logging data is written?  If so, then setting the log level to something higher than the highest log severity normally used would have the effect of suppressing all logging.

**Comment by swillner** [comment]
Most components setup their own logger on the DEBUG level on creation. Also, independent of the level the logging directory and files are created.

**Comment by rplzzz** [comment]
Obviously we need to get the logging level from the user configuration.  The hardwired debug-level was probably put in as a placeholder, and revising it never made it onto anyone's radar.  We could also check for debug levels high enough to preclude all output and suppress creating the empty file in those cases.

**Comment by swillner** [comment]
I suppose, it would be great to also allow for only stdout/stderr logging without writing into files.
