### ISSUE TITLE
Switch to "GPL3" or "GPL2 or later"

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#178]
Hi,

as discussed already a bit in #28 I would propose to change the license to either "GPLv3" or "GPLv2 or later". I understand the reasoning for choosing the simpler version 2 ("tivoization" not being an issue) but I see the following advantages of switching:

- currently it's not possible (I think) to distribute a compiled/linked binary version of Hector, as GSL is distributed under GPLv3 (see compatibility table: https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility); it could be useful to have Hector distributed through package management systems (though this would only apply to Hector 1.1.3 since you're using BOOST now, right?)
- the Educational Community License is according to [Wikipedia](https://en.wikipedia.org/wiki/Educational_Community_License) only compatible with version GPLv3, since GCAM is under ECLv2 (and your license change in the gcam-integration branch to ECLv2) this seems like an obvious change to make

Further, it seems to me that most scientific software projects have switched to GPLv3, so a switch would make it easier to exchange and link code.

Personally, I'm working on wrappers for Hector (with @swillner) and would prefer to have this clarified before choosing a license (I'd like to use GPLv3 or AGPLv3 for the reasons given above).

I think it would only require changing the text in the LICENSE.md file, so no massive header update would be necessary ...

The [GPL](https://www.gnu.org/licenses/#GPL) plain text version can be found here:
https://www.gnu.org/licenses/gpl.txt

**Comment by rplzzz** [comment]
Correct.  We removed the GSL precisely for this reason.  I don't have any real objection to the GPL v.3, but I do have a problem with the "or later version" language that appears in stock GPL licenses.  I don't know who will be running the FSF once Stallman dies or retires, and I don't know what GPL v.6 might look like.  Allowing some unknown person to rewrite the license of your code at some point in the indefinite future seems risky to me.  

That said, I don't feel strongly enough about the matter to spend any significant energy fighting it, and none of this is my decision anyhow.  The only advice I have is that if there is a way to omit the "or later version" language, we should do so.

**Comment by rgieseke** [comment]
Then, how about just switching to GPL3 (only) and get all the advantages discussed above (especially clean compatibility with ECLv2).

**Comment by rplzzz** [comment]
Seems reasonable.  @bpbond it's pretty much your decision.

**Comment by bpbond** [comment]
This sounds good to me. @rgieseke want to open a PR, targeting `rc1.2`?

**Comment by rgieseke** [comment]
Done! Let me know if you need something else. I think due to just referring to LICENSE.md this is the only think that needs changing.

**Comment by bpbond** [comment]
Thanks!

...looks like the Travis build failed. Hmm. I'm going to close this and we can proceed in PR #182
