### ISSUE TITLE
Redundant halocarbon emissions printed in output

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#179]
For all of the halocarbons we copy the input emissions into the output at every time step.  I think we can eliminate these from the outputstream to make it a little more compact and only output those variables that were calculated.  Thoughts?

**Comment by bpbond** [comment]
Agreed. (Do industrial land use change emissions appear in the outputstream? If so they could be removed as well.)

**Comment by cahartin** [comment]
yes they are output as well.  delete them or comment them out?

**Comment by bpbond** [comment]
Delete 'em. Will you PR this to `rc1.2`?

**Comment by cahartin** [comment]
will do

**Comment by rplzzz** [comment]
Hmm.  I was busy with other projects yesterday and didn't see this, but IMO you'll regret this change the first time you want to make a plot of the HC emissions for some reason.  There is no real advantage to making the outputstream smaller.  It is (should be?) only ever handled by software, and it's not so large that it's a problem for disk space.  Therefore, my advice is, if there's a chance, however remote, that you might want to look at it someday, leave it in.

**Comment by cahartin** [comment]
If we want to plot up emissions, than we can read in the input file at the time of plotting.  Emissions are not an output (at the moment), so to call them an output is somewhat misleading, implying that the model is calculating those emissions.  Also, we weren't consistent.  We only had emissions for halocarbons and CO2, not for CH4 or N2O etc.
