### ISSUE TITLE
Let the core accept arrays of doubles during initialization

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#181]
@rplzzz in #173 :

>I think the right thing to do here (i.e., what I should have done when I first did the GCAM coupling) is to add some initialization functions to the API. We could allow these to accept arrays of doubles, with the unit specified just once for the whole array. We would probably also want to make some provision for designating one (or more?) of the arrays as a key that indexes the others (e.g., the year column in our emissions tables). We might also arrange for these parts of the API to be disabled once the simulation is running, which would prevent someone from trying to use it inappropriately.

**Comment by kdorheim** [comment]
@bpbond bump to v4? close? or address. with v3?

**Comment by bpbond** [comment]
Close! I haven't heard any demand for this.
