### ISSUE TITLE
Useful to have the date printed in the outputstream

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#183]
The outputstream.csv will get overwritten but the date in the folder does not change.  It could be useful to print the date in the outputstream under the version of Hector ran.

**Comment by kdorheim** [comment]
Modify this so that there is some check or way that automatically changes the version indexing written in the output stream.

**Comment by bpbond** [comment]
>but the date in the folder does not change

I suspect this is a Windows limitation? The dates definitely change on my machine.

`outputstream.csv` could certainly have a header, though.

**Comment by kdorheim** [comment]
I think it does have a header, but the header only contains version information, which is ocassionally outdated.

**Comment by bpbond** [comment]
Addressed by @kdorheim in #571
