### ISSUE TITLE
Questions about Spatial distribution and resolution

### ISSUE THREAD

**Issue by chenhan1989** [JGCRI/hector#189]
Hi!
First time to use Hector. And I want very much to know whether the reduced form model can generate output files like gridded CO2 or BC concentration? Or at least the gridded temperature so that we can see the spatial distribution pattern of these output parameters?

**Comment by cahartin** [comment]
Hi @chenhan1989, thanks for checking out Hector! Core Hector does not produce gridded climate information.  Hector only computes global mean values*.  However, we have some done some work recently to investigate the relationship between global mean temperature and local temperature change (i.e., pattern scaling).  Please take a look at the following manuscripts, recently accepted and our pattern library.   For example, you can simply multiply Hector's global mean temperature output by the patterns, which will result in a new gridded temperature output. 

*note that BC and OC are not converted to concentrations. 

<www.github.com/JGCRI_CMIP5_patterns>
<http://www.earth-syst-sci-data-discuss.net/essd-2016-68/>
<http://www.geosci-model-dev-discuss.net/gmd-2016-258/>

**Comment by chenhan1989** [comment]
Thanks a lot for your kind help and patient explanation. It really saves me lots of time if I have to search for the documentation.


发自网易邮箱大师
On 05/09/2017 04:42, Corinne Hartin wrote:

Hi @chenhan1989, thanks for checking out Hector! Core Hector does not produce gridded climate information. Hector only computes global mean values*. However, we have some done some work recently to investigate the relationship between global mean temperature and local temperature change (i.e., pattern scaling). Please take a look at the following manuscripts, recently accepted and our pattern library. For example, you can simply multiply Hector's global mean temperature output by the patterns, which will result in a new gridded temperature output.

*note that BC and OC are not converted to concentrations.

<www.github.com/JGCRI_CMIP5_patterns>
http://www.earth-syst-sci-data-discuss.net/essd-2016-68/
http://www.geosci-model-dev-discuss.net/gmd-2016-258/
