### ISSUE TITLE
Constraining CO2 in Hector-doeclim

### ISSUE THREAD

**Issue by akschw04** [JGCRI/hector#190]
I constrained the CO2 concentration in Hector-doeclim by stepping the concentration in one year (here I used 2010). I used 1.25X and 1.50X 2010 values. I also tried 2X 2010 values distributed over 3 years from 2010-2012. Though these three experiments succeeded, there is instability in the ocean carbon flux (please see attached) related to the DIC error. Other CO2 steps failed with a DIC error in the ocean. 
[Ocean and Terrestiral Flux in Hector-doeclim.pdf](https://github.com/JGCRI/hector/files/1019818/Ocean.and.Terrestiral.Flux.in.Hector-doeclim.pdf)

**Comment by bpbond** [comment]
Right, I'm not surprised, with the current model design, that it couldn't handle a one-year 25% increase in CO2. You and I talked about reducing the model's minimum timestep--is this your next step? I could also clear some time to look at this soon, if useful.

**Comment by akschw04** [comment]
Yes, I looking into changing the timestep to see if this changes the instability in the ocean carbon.
