### ISSUE TITLE
Permafrost notes

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#191]
"An observation-based constraint on permafrost loss as a function of global warming"
http://dx.doi.org/10.1038/nclimate3262

**Comment by bpbond** [comment]
Also "Quantifying uncertainties of permafrost carbon–climate feedbacks"
http://www.biogeosciences.net/14/3051/2017/

**Comment by bpbond** [comment]
"Higher climatological temperature sensitivity of soil carbon in cold than warm climates"
https://www.nature.com/nclimate/journal/vaop/ncurrent/full/nclimate3421.html

**Comment by bpbond** [comment]
Methane:

https://www.biogeosciences.net/10/1659/2013/bg-10-1659-2013.pdf
https://www.nature.com/articles/nature13164

**Comment by cahartin** [comment]
https://www.nature.com/articles/s41558-018-0095-z?WT.ec_id=NCLIMATE-201804&spMailingID=56337072&spUserID=MzI0MzExMTc4MTA1S0&spJobID=1380658101&spReportId=MTM4MDY1ODEwMQS2

**Comment by bpbond** [comment]
http://www.pnas.org/content/115/15/3882

**Comment by bpbond** [comment]
Tagging @dawnlwoodard for awareness of this issue.

**Comment by bpbond** [comment]
Closing with paper being published.
