### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#192]
I've noticed that our last release was in Feb. 2016.  Since then we've had some bug fixes, along with the switch from GSL to Boost.  Does anyone object to releasing the current master as v1.1.4?  

An added benefit of doing a release would be that I've configured Zenodo, so drafting a release will mint a DOI for the hector source code, which I think would be a useful thing to have.

**Comment by cahartin** [comment]
@rplzzz i think that's a great idea.  are there any other open issues we want to address for this release?

**Comment by rplzzz** [comment]
I don't see any quick hits, and we're just talking about a patch-level release anyhow, so I'd say let's just go with what we've got.

**Comment by cahartin** [comment]
sounds good!

**Comment by rplzzz** [comment]
All set.  Check out the release front page with our shiny new DOI badge.
