### ISSUE TITLE
Forcing.log does not match output forcing for O3

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#196]
Within the forcing.log file, O3 forcing is the total forcing not from a reference (which is the first Hector time step ~ 1750). Therefore, the total forcing in the forcing.log file does not match the forcing in the outputstream.  The forcing within the outputstream is calculated correctly.  It just isn't apparent why there is a difference without exploring the source code. 

outputstream: 
`2100 | ref | 0 | forcing | FO3 | 0.5477 | W/m2`
`2100 | ref | 0 | forcing | Ftot | 8.453 | W/m2`

Forcing.log
`forcing FO3 in 2100 is 1.90817 W/m2`
`forcing total is 9.83036 W/m2`

**Comment by cahartin** [comment]
I also noticed a slight difference in CF4 and CH3Br that I should look into further.

**Comment by cahartin** [comment]
CF4, CH3Br, and CH3Cl all have initial preindustrial values set in the ini file.

**Comment by bpbond** [comment]
Fixed in #601
