### ISSUE TITLE
Binder/Notebook

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#203]
The Binder infrastructure used in the Pyhector repo for running a live demo notebook is transitioning to a new setup.

With their beta version I managed to get the Pyhector version back running: 

https://beta.mybinder.org/v2/gh/openclimatedata/pyhector/master?filepath=index.ipynb

I realised that for 'vanilla' Hector it shouldn't be too difficult either:

https://beta.mybinder.org/v2/gh/rgieseke/hector/binder

The Dockerfile there compiles Hector and makes it available. Click on "New / Terminal" to get a terminal where you can e.g. run (or even re-compile Hector)
```
./source/hector input/hector_rcp26.ini
```

It would be possible to combine this with or rather run this from a 'real' Python or R notebook.

Would there be interest to have this included in the main Hector repo?
What's the current status of the R wrapper?

**Comment by bpbond** [comment]
The current R wrapper (more accurately described as a backend) is [crude and out of date](https://github.com/JGCRI/hector/issues/168), honestly.
