### ISSUE TITLE
Temp_doeclim tracking internal_Ftot doesn't work

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#205]
Line 336 in `temp_doeclim_component.cpp` inherents a bunch of text and code that allows a smooth transition from a historical temperature constraint.  With doeclim enabled this doesn't work.

**Comment by cahartin** [comment]
<// Commented section below is for case of user-specified temperature record.
    // TempDOECLIM component can't handle that at the moment!
    
    //// We track total radiative forcing using internal variable `internal_Ftot`
    //// Need to do this because if we're subject to a user constraint (being forced
    //// to match a temperature record), need to track the Ftot that *would* have
    //// produced the observed temperature record. This way there's a smooth
    //// transition when we exit the constraint period, after which internal_Ftot
    //// will rise in parallel with the value reported by ForcingComponent.
    
    // If we never had any temperature constraint, `internal_Ftot` will match `Ftot`.>

**Comment by rgieseke** [comment]
If temperature constraining doesn't work anymore it might be good to remove or comment this section in the INI input files.

**Comment by kdorheim** [comment]
@bpbond was this addressed by your tgav constraint work?
