### ISSUE TITLE
Error: bad Tk value

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#207]
Hi,

I'm getting an error with Hector (built from Master) for the RCP85 scenario and a climate sensitivity set to 4.1, 4.0 works fine.

```
...
Tue Nov 28 17:34:25 2017:NOTICE:run: ODE solver success at t= 2234  last dt= 0.28125
Tue Nov 28 17:34:25 2017:NOTICE:run: 
* Program exception: Assertion failed: bad Tk value
* Function ocean_csys_run, file ocean_csys.cpp, line 130
```

Only change in INI file:
```
[temperature]
S=4.1 				; equilibrium climate sensitivity for 2xCO2, degC
```

For RCP6 it's failing from S=7.5

These are the limits set in `ocean_csys.cpp`:
l. 130
	H_ASSERT( Tk > 265 && Tk < 308, "bad Tk value" ); // Kelvin

**Comment by rplzzz** [comment]
This looks like an overly zealous attempt to ensure that temperatures are "reasonable".  We could probably raise that up to 325 or something like that.

**Comment by cahartin** [comment]
yea, I totally agree.  I think I was trying to make sure the ocean's boil away but it looks like I went overboard.

**Comment by rgieseke** [comment]
Depending on what you want to support 325 might not be enough ...

See e.g.
https://www.nature.com/articles/ngeo3017/figures/5

**Comment by rplzzz** [comment]
This value is meant to be the average sea surface temperature, isn't it?  325 K is over 50 C, or just slightly warmer than the temperature of a nice hot shower.  I would say that if it reaches that kind of level, then something has gone pretty wrong with the calculation.  

In fact, even the default limit of 308 (~35 C) seems really high.  What are we getting for the air temperatures in those scenarios?  

The figure you link to shows distributions for climate sensitivity, but it doesn't say anything about ocean temperatures.  I doubt that anyone expects that even at the high end of sensitivity values and emissions scenarios we will be turning the oceans into bath water.

**Comment by rgieseke** [comment]
Fair enough, it certainly makes sense to have these sensible ranges for ocean temps.
I was thinking of probabilistic setups, where climate sensitivity might be even higher.

What is 'dic', checked in line 131?

**Comment by rgieseke** [comment]
If I set the Tk limit to a high value, I get an error for `dic`.

**Comment by rplzzz** [comment]
Looks like it means "dissolved inorganic carbon".  It looks like a similar issue; we have defined a reasonable range, and when we let the temperature get really high, DIC goes out of that range (presumably on the low end, since solubility decreases with increasing temperature).

**Comment by rgieseke** [comment]
It might make sense to look into this once https://github.com/JGCRI/hector/pull/206 is merged, doesn't it?. (Or on that branch ...)

**Comment by rplzzz** [comment]
I think so, yes.  @cahartin, do you know if this problem happens on the doeclim branch?

**Comment by rgieseke** [comment]
With a rc2.0.0 build from 9dd16696355b3d80de020e84061e18c1ba375662
I can run RCP8.5 with S=4.9, S=5.0 produces

```
* Program exception: Assertion failed: bad Tk value
* Function ocean_csys_run, file ocean_csys.cpp, line 130
```

Which would mean that the "likely" AR5 range of 1.5 - 4.5 would be covered with rc.2.0.0.

**Comment by rplzzz** [comment]
I don't really have much of an opinion on this.  From a software point of view everything is working as intended.  From an earth science point of view, the question is, how warm can it get before the simplifications in the model become unreliable?  We should give some thought to that because the cutoff right now is a little arbitrary.

Also, maybe instead of throwing an exception we should have it just log a (nonfatal) error.

**Comment by cahartin** [comment]
with the addition of DOECLIM for the temperature component Hector can run with a CS much higher. 
#287.  We should still decide if we want to add any physical constraints to the model.
