### ISSUE TITLE
Automated calibration of Hector against time series

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#208]
Any re-calibration of Hector for v2 (after merging of #206 ) should use a script that we bundle in the repo.

**Comment by cahartin** [comment]
Yes I think calibrating to observational temperature would be ideal.  HadCrut data is used a lot. But it would be cool to see how different hector is when calibrated to different temp data sets.

**Comment by bpbond** [comment]
Well, I think this will essentially be solved with your and Kalyn's work.

**Comment by rplzzz** [comment]
Yes, but it would still be good to add an analysis code that sets up the calculations and runs them.
