### ISSUE TITLE
Compare Hector v1.1 and Hector v2.0

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#212]
compare old and new Hector with MAGICC and CMIP5 output.

**Comment by rgieseke** [comment]
Hi, I did some plots comparing Pyhector versions
Pyhector 0.7.0 should be equivalent 1.1.*,
0.8.1 has the halo-fix backported and 
rc2.0.0 is built directly with the latest Master commit from Hector (I only testet briefly but the latest cal value bug fix didn't seem to make a big difference).

![rcp85](https://user-images.githubusercontent.com/198537/36214822-b3c3815c-11aa-11e8-8bb8-f807f9d0d2ef.png)

![rcp60](https://user-images.githubusercontent.com/198537/36214824-b3e4cf88-11aa-11e8-922b-cc75c03d85d2.png)

![rcp45](https://user-images.githubusercontent.com/198537/36214825-b4055e42-11aa-11e8-9a88-d77b03bd35a1.png)

![rcp26](https://user-images.githubusercontent.com/198537/36214826-b4240216-11aa-11e8-90ce-fa24613285f2.png)

**Comment by rgieseke** [comment]
I've add MAGICC (through Pymagicc, so it's MAGICC 6.8) to the plots, reference period for temperatures is 1850 - 1900

![rcp85](https://user-images.githubusercontent.com/198537/36250365-dca7b6ae-123d-11e8-8dbc-2b50e74d68be.png)
![rcp60](https://user-images.githubusercontent.com/198537/36250366-dcc089b8-123d-11e8-99dd-3cf9a59020b9.png)
![rcp45](https://user-images.githubusercontent.com/198537/36250367-dcd95d12-123d-11e8-9bef-5635b2bcb07d.png)
![rcp26](https://user-images.githubusercontent.com/198537/36250368-dcf134d2-123d-11e8-8ca1-85ada8a06f55.png)

**Comment by cahartin** [comment]
https://www.authorea.com/users/170481/articles/207125-hector-doeclim
