### ISSUE TITLE
Run Hector rc2.0 on all 3 platforms

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#214]
PC, MAC and Linux

**Comment by bpbond** [comment]
I have tested rc2.0 on Mac 10.12.6 with the newest Boost, 1_66_0. All good.

**Comment by rgieseke** [comment]
I've tested rc2.0.0 with a Homebrew installed Boost on OS X:

    brew install boost

And environment variables set as follows:

    BOOSTLIB /usr/local/lib
    BOOSTROOT /usr/local/lib
    BOOSTVERSION 1.66

Works fine!

**Comment by cahartin** [comment]
@rgieseke awesome thanks!

**Comment by cahartin** [comment]
works on VS as well.
