### ISSUE TITLE
Spinup and fixed NPP

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#22]
Minor   Using fixed NPP in spinup means bad things can happen if other C pools are too low  N   simpleNbox.cpp      Ben     Open

**Comment by kdorheim** [comment]
Slightly cryptic @bpbond is this still a problem? If not let's close this issue 👍

**Comment by bpbond** [comment]
It is still a problem, more strictly a characteristic of Hector, but maybe doesn't deserve its own issue, especially given #53 .
