### ISSUE TITLE
Consider integrating Hector into PEcAn

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#223]
The Predictive Ecosystem Analyzer (PEcAn) (see pecanproject.org) is an integrated ecological bioinformatics toolbox–it provides a completely kick-ass automated front- and back-end to run multiple ecosystem models at a site, a single model across lots of sites, perform data assimilation and sensitivity analyses, and more, all through a web-based interface and virtual machines.

I asked PEcAn lead Mike Dietze whether a model like Hector could be used with PEcAn, and he said he didn't think it would be too hard - see pecanproject/pecan#1813.

Anyway, we might consider this, rather than rolling our own MCMC/sensitivity/DA Hector framework.

Edit: fixed PEcAn issue number.

**Comment by bpbond** [comment]
Just to clarify, this doesn't mean "make Hector part of PEcAn", it means "write a PEcAn module to interface with Hector".

**Comment by ashiklom** [comment]
Quick thought:

Hector's concept of multiple biomes should map neatly onto PEcAn's concept of PFTs. With that in mind, it should be straightforward to use PEcAn to run Hector under multiple different PFT configurations and see how that affects the output uncertainties.

One caveat is that the CO2 fertilization parameter (`beta`) in Hector is an empirically calibrated quantity that doesn't really map onto any measurable plant trait and therefore wouldn't immediately benefit from PEcAn's trait database (BETY). To do those runs, we would have to add `beta` as a new "trait" to Bety (this isn't hard to do). That said, an interesting project might be to calibrate the parameter for several different biomes (e.g. tropical, temperate, boreal) and then try to establish empirically how that parameter is related to measurable plant functional traits (e.g. foliar biochemistry, leaf morphology, allometries, roots, etc.).

**Comment by ashiklom** [comment]
Another quick thought:

Based on the Hector paper, Hector currently initializes the terrestrial carbon pool using spin-up to a stable optimum. Eventually, it would be good to figure out a way to initialize Hector based on the true state of the carbon cycle (or perhaps this is already possible?). This capability would also be necessary to take advantage of any of PEcAn's state data assimilation functionality.

**Comment by bpbond** [comment]
>Hector's concept of multiple biomes should map neatly onto PEcAn's concept of PFTs

That's really good to know–thanks.

Re calibrating beta for different biomes and seeing how it relates to plant traits, interesting, although this strikes me as fraught with potential difficulties. But it's a good possibility to consider.

Yes, you can already provide current state-of-C-cycle info to Hector and tell it to skip spinup. Though this hasn't been particularly well tested.
