### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#239]
It would be nice to have an automatic way of generating unit tests for any future model development.  Can we package up Adria's code into an R package?

**Comment by rplzzz** [comment]
It only just dawned on me that climate scientists use "unit test" differently to software engineers.  For this kind of test wouldn't we just have to create emissions input files with the emissions profile used for each test, plus ini files for each test that read in those emissions?  Is there more to it than that?

**Comment by bpbond** [comment]
Yeah the terminology differs confusingly. Yes, I think that’s basically all that’s required.

**Comment by akschw04** [comment]
Yes, for each "unit test" you will want to create an emissions profile (or CO<sub>2</sub> concentration pathway for CO<sub>2</sub> forcing experiments) and corresponding .ini files to read in those emissions/concentrations. In our unit tests we reported the model response, found by subtracting the results from a reference run from a perturbation run. If you follow this procedure, you will need reference emissions files and .ini files, along with the perturbation files and .ini files.

**Comment by rplzzz** [comment]
I see.  So there is a little bit more to it because you have to compare results from two runs; you can't get everything you need from a single one.

**Comment by ssmithClimate** [comment]
Yes, two runs - or actually a set of runs. Another name for this would be impulse response tests. Just re-stating what Adria said: for emissions unit tests, we want to take some reference set of emissions (presumably what is committed with hector), run that, then run a series of additional runs with perturbations to one emission species at a time in one year. The result of those runs are subtracted from the reference run to get the model response. That gives the response of the model to each emission species. Also useful are concentration unit tests, where the model is first run with a fixed background CO2 concentration, then again with fixed background concentration with a concentration perturbation in one year.

**Comment by rplzzz** [comment]
If you can supply the ini files for the impulse runs, it would be easy enough to add a function to the hector package that runs the base case and the perturbation case and produces a table of differences, or a plot if ggplot2 is installed.

**Comment by rplzzz** [comment]
Going through the issues to see what needs to be added to the backlog.  I think this would actually be pretty easy to do the way things stand.  It might make a good vignette for the hector package.

**Comment by ssmithClimate** [comment]
That would be great IMHO!

**Comment by rplzzz** [comment]
@ssmithClimate I've added it to the backlog I've been keeping.  Probably it would be best for me to walk someone who has already run the impulse tests through translating them into the R interface.  Has @akschw04 done these runs?

**Comment by rplzzz** [comment]
I think the thing to do would be to add this as a vignette in the package.  This would make a good project for a student who is learning to use hector.

**Comment by kdorheim** [comment]
@bpbond this might be a test to add to @dawnlwoodard hectoreval project, it will show how Hector temperature responds to the different emissions. Thoughts?

**Comment by bpbond** [comment]
I think Robert was right here—this would be a good vignette, and if someone wants to do something like this in the future, great. But this isn't an issue with Hector, so closing.
