### ISSUE TITLE
Define R interface for Hector

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#246]
Determine what Hector functions should be exposed via the R interface and set up a skeleton for them.

Candidate interface:

- [x] `setup(inifilename)`: Instantiate the model core, read input file, run through spinup
- [x] `run(time)`: Run the model up through `time`.  
- [x]  `DataFrameVisitor`: Visitor to collect and format results.
- [x] `setData(component, what, time, value)`: Set data in `component`.  Should support vectorized `time` and `value`.
- [x] `reset(time)` Reset the model to a previous time, rerunning spinup if necessary.
- [x] `shutdown()` Shut down the model.  
- [x] `getStartDate()` Report the starting date for the model.

Questions to answer:

* ~Do we want to try to support having multiple instantiated cores?  This might be useful for doing comparisons between multiple scenarios, or for having an MC likelihood account for performance over several scenarios. However, it's not clear to me that Hector can support having its components multiply instantiated.  We've never tested it that way.  If we do decide to support multiple cores, how do we keep track of them, both on the R side and on the C++ side?~
This turns out to be pretty easy to support.  You hold the core objects in a vector on the C++ side, and the R objects hold an index into that vector.

**Comment by rgieseke** [comment]
Pinging @swillner ... for a new Pyhector version we should also consider these, the `reset` and `run` until timestep stuff could be useful to add.

Fwiw, here is Pyhector's API doc:
http://pyhector.readthedocs.io/en/latest/pyhector.html
