### ISSUE TITLE
Handling of visitors in core is prone to memory leaks

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#247]
The code in question is:
https://github.com/JGCRI/hector/blob/master/source/core/core.cpp#L256-L262
Basically, the caller creates a visitor, then passes a pointer to the visitor to the Core object, and the Core squirrels it away for later use.  However, the core doesn't _own_ the pointer, and so the calling code is responsible for keeping the visitor object alive for the appropriate duration.  This works ok when the calling code is just a thin wrapper around the core functionality, like the hector main.  For anything more complicated than that, it makes it really hard to isolate the hector-specific parts of the calling code in some sort of interface module.  You either have to propagate that interface all the way up to the calling program's main, or you have to develop some sort of resource manager class to manage all the hector-specific handles you have to track.

The right thing to do here is to have the core act as the primary resource manager, keeping the visitors alive for as long as they're needed and destroying them when the core itself is shut down.

**Comment by rplzzz** [comment]
Actually, there's another, bigger problem here.  The visitor class hierarchy was designed under the assumption that all visitors would be writing their data out to disk.  As such, there is no provision at all for returning a value, and suppressing the running of visitors is clunky at best.  I'm probably going to leave visitors the way they are for now and have the Rcpp interface get the data it needs via the Core messaging interface.

**Comment by bpbond** [comment]
@rplzzz You closed this; does that mean you don't think, finally, that this needs to be addressed as a bug? Thanks.

**Comment by bpbond** [comment]
> kind of obsolete

Interesting point.
