### ISSUE TITLE
Build Hector using GNU Build System (i.e. configure + make)

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#249]
Not a huge priority, but it may be nice to revise Hector's build system to use the standard [GNU Build Tools](https://www.gnu.org/software/automake/manual/html_node/GNU-Build-System.html) approach of `configure --with-boost-lib=... --with-whatever=...` + `make`. This would make it easier to build Hector against different libraries in the future, if it was expanded with other dependencies (which we should avoid...but still).

Right now, as far as I can tell, the option required for user compilation is the location of Boost libraries, which means that, _in theory_, the `configure` script should not be very involved.

I admit that most of the motivation for this issue to give me a good reason to learn how to set up projects to use the GNU Build System, which is something I've wanted to learn for years. It's _definitely_ something that larger earth system models would benefit from -- many of their current build systems are a nightmare.

**Comment by rplzzz** [comment]
Agreed.  If you wanted to take a whack at this, it's a subject on which we would entertain a pull request.

**Comment by bpbond** [comment]
👍  Go for it.

**Comment by ashiklom** [comment]
Now that #282 is merged and this is no longer needed for the R package, I'm gonna close this. It would still be useful for standalone Hector, but it's finding Boost library location automatically via configure is pretty complicated, and it's much simpler to ask users to set 2 environment variables.
