### ISSUE TITLE
Store Hector manual (wiki) as part of Hector codebase

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#280]
Original text from Slack:

> For a software project I worked on for my PhD, we stored the un-rendered version of the documentation/manual as part of the repository, but host the rendered manual itself in a separate GitHub repository. That way, we could still use GitHub's free web hosting without ballooning the size of our repository with rendered HTMLs. The nice thing about that is that code and documentation changes are version controlled together, which makes it (1) easy to ensure that PRs with significant code changes are accompanied by documentation updates, and, more importantly, (2) east to link Hector code and documentation in releases (so, e.g., we would always know that Hector 0.3.5 is linked to the documentation for Hector 0.3.5).
>
> With that system, you can also do some clever (if somewhat janky) things like have Travis automatically build the latest documentation and push the rendered files up to the rendered docs repository.

Linking code and documentation versions would address #130.

Some additional notes:
* The project I'm referring to is here: https://github.com/PecanProject/pecan
* The documentation markdown files are stored in the [`book_source`](https://github.com/PecanProject/pecan/tree/develop/book_source) directory.
* [This bit of Travis config](https://github.com/PecanProject/pecan/blob/develop/.travis.yml#L150-L158) builds and uploads the manual.
* The rendered documentation HTMLs are in this GitHub repo: https://github.com/PecanProject/pecan-documentation
* The latest version is rendered (using GitHub pages) here: https://pecanproject.github.io/pecan-documentation/develop/
* We also have documentation versions for previous releases listed here: https://pecanproject.github.io/documentation.html

**Comment by ashiklom** [comment]
An additional advantage is that this would make the documentation easier to edit locally. Technically, you can do the same with the GitHub wiki, but it's pulled down as a submodule, which I've always found to be exceedingly confusing and hard to work with.

**Comment by rgieseke** [comment]
See also the discusssion in https://github.com/JGCRI/hector/issues/130

**Comment by ashiklom** [comment]
Here's an [implementation](https://github.com/ashiklom/hector/tree/pkgdown) of this idea using [`pkgdown`](https://pkgdown.r-lib.org/index.html), and here's the resulting [package website](https://ashiklom.github.io/hector/). The manual files from the wiki live in the [`vignettes/manual`](https://github.com/ashiklom/hector/tree/pkgdown/vignettes/manual) directory (as R markdown -- `.Rmd` -- files). The `manual` part can be changed, but as far as I can tell, the files have to live in `vignettes` for `pkgdown` to automatically compile them.

The files are rendered by GitHub pages, and updated automatically by Travis. We could also explore the possibility of rendering the development and release code separately, which seems to be something that [`pkgdown` supports](https://pkgdown.r-lib.org/reference/build_site.html#development-mode).

What do you all think? If this looks good, I can open a PR and we can close this and #130.

**Comment by bpbond** [comment]
That is _super_ slick and looks great. 👏 I'm also a fan of avoiding submodules if possible.

The one problem is see is that `pkgdown` is pulling the author information for the R package, of course, and displaying it on what will easily be taken (by most folks) as the website for the entire model. 

<img width="126" alt="screen shot 2019-01-26 at 1 09 24 pm" src="https://user-images.githubusercontent.com/1956468/51791073-9f56e480-216b-11e9-9b7e-0e2c2b455ce1.png">

Nothing against @rplzzz , but we don't want to make it seem that he's the sole author of Hector the model.

**Comment by ashiklom** [comment]
Closed via #294.

**Comment by ashiklom** [comment]
Now that the entire wiki has been migrated to the [`vignettes/manual`](https://github.com/JGCRI/hector/tree/master/vignettes/manual) folder inside the repository, and is nicely rendered on the [Hector website](http://jgcri.github.io/hector/articles/manual/index.html), should we eliminate the wiki altogether, especially since some of the information in there (especially about installation) is outdated?
