### ISSUE TITLE
Bogus C++ warning is bogus

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#283]
On windows builds we get the following warnings from the C++ compiler 
```
* checking whether package 'hector' can be installed ... WARNING
Found the following significant warnings:
  ../inst/include/core.hpp:149:9: warning: 'Hector::Core::max_spinup' will be initialized after [-Wreorder]
  ../inst/include/core.hpp:116:10: warning:   'bool Hector::Core::setup_complete' [-Wreorder]
  core.cpp:49:1: warning:   when initialized here [-Wreorder]
```
We're not getting them on linux builds, which is probably only because someone turned off that warning message.  

This warning is almost always a false alarm, and this time is no exception.  We can silence it by reordering the initializations to go in the same order as the declarations in the class body, or by moving the initializations into the constructor body.

**Comment by kdorheim** [comment]
@bpbond @pralitp is this still an issue?

**Comment by bpbond** [comment]
I don't know, but if someone on Windows is troubled by it, they can re-open.
