### ISSUE TITLE
Update installation instructions in wiki

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#293]
Since #282, installing the Hector R package can be done entirely from within R (via `install.packages`, `devtools::install_github`, or the RStudio buttons). The wiki instructions for installing Hector need to be simplified to reflect this fact.

Per my conversation with @ssmithClimate.

**Comment by rplzzz** [comment]
Be sure to note that there is a bug in (some versions of?) Rstudio that causes installation via `install_github` to be unable to find the toolset to build the package (seen in Rstudio v 1.0.136).  Running `install_github` from a command-line R session works fine, however.
