### ISSUE TITLE
Calculate emissions needed for observations of CH4 and N2O

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#296]
Ideally we would like to better match the historical observations of CH4 and N2O concentrations.  Since emissions are highly uncertain, can we calculate the emissions needed to match the observational concentrations?

**Comment by rplzzz** [comment]
I showed an example of how to do this with CH4 at the meeting with Marcus a while back.

**Comment by cahartin** [comment]
We want to use this capability to drive historical emissions .

**Comment by ssmithClimate** [comment]
@rplzzz thanks! Will definitely talk to you once we have some new hands in place to get things like this done...

**Comment by bpbond** [comment]
Closing. Robert's example in the vignette shows one way to do this.
