### ISSUE TITLE
Not all variables exposed in R hector are actually available

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/hector#299]
r hector has a number of variables available, for example: EMISSIONS_CH4(), EMISSIONS_BC(), EMISSIONS_CF4(), etc. The hector code is not set up to return all of these. For exampe:
fetchvars( ref_core, some_year, EMISSIONS_CF4() )
will return an error of "Caller is requesting unknown variable: CF4_emissions".

**Comment by bpbond** [comment]
CH4 emissions are exposed in #298 .

**Comment by kdorheim** [comment]
The emission variables listed here are accessible with fetch vars. If there are other variables that need to be exposed please open another issue and specify which ones users would to be exposed.
