### ISSUE TITLE
Come up with our own formatted time output

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#3]
Cosmetic	Come up with our own formatted time output	N	logger::getDateTimeStamp		Pralit	Pralit	Open

**Comment by bpbond** [comment]
It's straightforward to parse the existing output though. @pralitp - can this be closed?

**Comment by pralitp** [comment]
Well, to tell you the truth I don't even remember writing that code but if looks good.. I'll remove the TODO comment and commit/close.   Also there is a comment wondering if it works ok on Windows @cahartin I assume you get the time stamp in the logs on windows too?

**Comment by cahartin** [comment]
this is what I get on Windows : 
Thu Feb 05 21:05:27 2015:NOTICE:Hector::Logger::printLogHeader: hector version 1.0
Thu Feb 05 21:05:27 2015:DEBUG:Hector::ForcingComponent::init: hello forcing

**Comment by pralitp** [comment]
Cool, I'll remove that TODO as well.
