### ISSUE TITLE
Provide a way to pass a prescribed concentration? 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#301]
**Is your feature request related to a problem? Please describe.**
When I am trying to do an abrupt four times CO2 concentration step instead of being able to use `setvars` to change the constrained CO2 concentration I have to use a series of ini / csv files.

**Describe the solution you'd like**
Enable `ATMOSPHERIC_CO2()` to be reset with `setvars` if we think enough people will use this feature.

**Comment by rplzzz** [comment]
Small detail: we probably want to have a separate variable (`CO2_CONSTRAINT` or something like that) for setting the constraint.  That makes it more clear what is going on; setting something that is supposed to be an output variable is confusing.  (Also, internally the calculated CO<sub>2</sub> and the constraint are stored in different places, so we don't want to have a single capability read one thing and write another.)  We might also want to do some sort of check whether CO<sub>2</sub> constraints are in effect and/or provide a mechanism for toggling the constraint on or off.

**Comment by ashiklom** [comment]
@kdorheim This sounds great! I could definitely see this being useful in my permafrost work.

**Comment by bpbond** [comment]
Agreed, but I echo @rplzzz 's comment about let's use the existing constraint mechanism for this if possible.

**Comment by kdorheim** [comment]
Addressed in a Hector v3 devlopment
