### ISSUE TITLE
Should components use specific land/ocean temperature instead of GMT?

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/hector#304]
Now that hector separately reports separate temperature values for land and ocean air, and ocean SST, should components use the appropriate temperatures instead of global mean surface air temperature (GMT)?

Changing what temperature value is used would alter results in two ways. 1) The numerical value of these vary for any given year, and 2) also the time trend is different as compared to GMT.

These components currently use GMT:
slr_component.cpp
simpleNbox.cpp
ocean_component.cpp
oceanbox.cpp
temperature_component.cpp

Mechanically this is easily done. 

However, would we need to change parameter values to accommodate this? That is, care the current parameters (heat transport, Q10, etc.) derived relative to GMT, so they would need to be re-derived if something other than GMT was used?

**Comment by kdorheim** [comment]
Addressed in #562
