### ISSUE TITLE
Initial atmospheric concentration isn't equal to preindustrial co2 setting

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#306]
During the spin-up process the atmosphere has some net absorption from the other carbon pools in the model, to the tune of about 11.7 ppmv.  
![image](https://user-images.githubusercontent.com/7209964/57969536-ff091380-7945-11e9-9231-7c3e0a820647.png)

It's not totally clear that the 1745 value _should_ be equal to the preindustrial value, since the definition of "preindustrial" is a bit nebulous.  However, it also seems like our discrepancy between the preindustrial and initial concentrations is not the result of a considered assessment of the likely change in concentration from preindustrial times to the start of the simulation.  Rather, it seems to be a byproduct of trying to equilibrate the model before the run begins in earnest.

I can see a couple of ways of dealing with this situation.
1. Ignore it.  We calibrate the parameter to match ESM outputs, so as long as we recognize that its value shouldn't be taken as literally representative of the concentration at some particular past time it doesn't really present (much of) a problem.
2. Apply an adjustment at initialization.  Since the discrepancy is pretty constant, we could initialize the atmospheric carbon pool to a value 11.7 ppmv less than the input parameter.  Then, by the end of the spinup the value should be pretty close to the value specified by the preindustrial concentration parameter.  The disadvantage to this method is that it is brittle.  Changes to the model will probably affect the offset, so we would have to monitor it.  (That said, it wouldn't be hard to write a test that would do this.)
3. Apply an adjustment during spinup.  At each time step we could add or remove carbon as required to bring the atmospheric concentration back to the intended initial value.  This is more work, but it is probably the closest to the right way to handle the matter.

Is this something we want to tackle?

**Comment by bpbond** [comment]
>Rather, it seems to be a byproduct of trying to equilibrate the model before the run begins in earnest.

Well, it's not a _byproduct_; after all the whole point of the spinup is to bring the C cycle to equilibrium. But you raise a good point, and one that we should at the very least be clearer about to model users: the "initial (preindustrial) pools and fluxes" given in an `ini` file is _not_ what the model actually starts with in 1745 or whenever. 

Anyway, I agree this is at least a definitional problem we need to be clearer about. My vote would be for number 1 above, telling users "the preindustrial values you specify may differ from model-start conditions because spinup brings the C cycle into equilibrium; if you need these exact values, experiment to find initial numbers that are roughly in equilibrium". Or something like that. (Another option, in theory, would be to turn off spinup, right? But I suspect this would break the ocean.) Number 2 seems brittle, as you say, and number 3 privileges the atmosphere pool over everything else in the system, and I'm not sure we want to do that.

**Comment by rplzzz** [comment]
Sure, the point of the spinup is to bring the system to equilibrium, but to _which_ equilibrium?  It's not as if there don't exist equilibria where the initial concentration is equal to the preindustrial value; it's just that our procedure doesn't find them.  That is, at best, surprising behavior, and I suspect the only reason we haven't gotten questions about it before now is that we tend not to look at the data before 1850 because that's when the ESMs start their historical output.

On the question of privileging the atmosphere pool, the atmosphere is already privileged.  It is the thing that we talk about the most and the thing that we compare to other models.  People have opinions about what the initial atmospheric concentration ought to be.  About the other carbon pools, not so much.

**Comment by rplzzz** [comment]
Option 3 turned out to be remarkably easy to implement.  

Here are are the first few years of concentrations, as compared to the preindustrial:


|scenario            | year|variable |    value|units    | 
|:-------------------|----:|:--------|--------:|:--------| 
|spinup-constrain |   NA|C0       | 276.0897|ppmv CO2 |
|spinup-constrain | 1745|Ca       | 276.0897|ppmv CO2 |
|spinup-constrain | 1746|Ca       | 276.0897|ppmv CO2 |
|spinup-constrain | 1747|Ca       | 276.0909|ppmv CO2 |
|spinup-constrain | 1748|Ca       | 276.0923|ppmv CO2 |
|spinup-constrain | 1749|Ca       | 276.0937|ppmv CO2 |
|spinup-constrain | 1750|Ca       | 276.0951|ppmv CO2 |

And a comparison to the current core version of hector:
![image](https://user-images.githubusercontent.com/7209964/57979565-9d9c7f80-79ed-11e9-82c0-07b183a4abb6.png)
The difference in CO<sub>2</sub> concentration just carries through over time.  The temperatures, on the other hand, are nearly identical between the two runs because the baseline concentration is set in 1750 using whatever concentration is current in that year, and the ratios aren't that different.  They are ever so slightly different, however, which we can see if we look at the actual temperature values.

|scenario         | year|variable |    value|units |
|:----------------|----:|:--------|--------:|:-----|
|spinup-constrain | 2100|Tgav     | 2.55|degC  |
|core-hector      | 2100|Tgav     | 2.51|degC  |

**Comment by bpbond** [comment]
>People have opinions about what the initial atmospheric concentration ought to be. About the other carbon pools, not so much.

Well, that's one perspective, I guess.

**Comment by bpbond** [comment]
That's cool Option 3 was so straightforward.
