### ISSUE TITLE
Distinct variables for initial vegetation, soil, and detritus C pools

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#318]
Basically, have separate variables `veg_c0`, `detritus_c0`, and `soil_c0`, and then reserve the `veg_c`, `detritus_c`, and `soil_c` to mean the pools at the current moment. This might result in cleaner, slightly more robust separation of `setData` calls around initialization vs. modifying pools in existing Hector instances.

---

> If we were starting over from the beginning, this is probably how we would want to design it, but given where we are now, I suspect this falls into the category of, if it ain't broke, don't fix it.  Unless we can think of some badness (beyond slightly awkward internal workarounds) that is occurring because of this, I say we let it be.

_Originally posted by @rplzzz in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjU5MDE5Mzgx/pull_request_reviews/more_threads_

**Comment by kdorheim** [comment]
@bpbond okay to close?

**Comment by bpbond** [comment]
If it ain't broke...
