### ISSUE TITLE
Prototype of concentration-constrained CO2, CH4, N2O, and halocarbons

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#324]
The highest-priority RCMIP scenarios are concentration-driven, rather than emissions-driven. One way to do this is to fit emissions trajectories to concentration time series, as @rplzzz has done in the past. However, I'm wondering if a valid alternative is modifying the Hector code to take concentrations directly.

I have a rough prototype of this here: https://github.com/JGCRI/hector/compare/master...ashiklom:concentration-constraint

Basically, the changes are (1) allow concentrations of CH4, N2O, and halocarbons to be passed as inputs, and (2) if that happens, set a special boolean flag (`emissions_forced` to `false`), which causes Hector to skip all of the processes that convert emissions to concentrations.

Presumably, there's a good reason not to do things this way...but I'm not sure what it is and was hoping to be enlightened. I understand that solving the C cycle is more complicated and therefore we need the additional step of dumping the excess C to the deep ocean, but all of these other gases (CH4, N2O, and halocarbons) seem to just be directly calculated at every time step, so I don't immediately see the problem with just bypassing that math if concentrations are provided.

Closely related to #296 and #301 (and directly borrowing some of @kdorheim's code from #302).

**Comment by ssmithClimate** [comment]
This seems useful to me.

**Comment by bpbond** [comment]
Agreed, that seems like the straightforward approach actually, rather than back-calculating emissions necessary to produce concentrations. It also seems a very useful capability.

**Comment by kdorheim** [comment]
@bpbond all of these constraints are implemented in land_tracking okay to close?

**Comment by bpbond** [comment]
Yes.
