### ISSUE TITLE
More halocarbons from IPCC AR5

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#325]
IPCC AR5 WG1, Chapter 8, Table 8.A.1 contains chemical formulae, atmospheric lifetimes, and radiative efficiencies for a bunch of different halocarbons, including all of the ones Hector currently has and many more that it doesn't. I thought I'd post here a rough digitized version of that table (still in need to post-processing, but hopefully a good start) for whenever we want to update Hector's current list of halocarbons.

https://github.com/ashiklom/ipcc-ar5-wg1-table8a1

**Comment by rgieseke** [comment]
I created a CSV table from the Montreal Protocol which might be useful for you too.

Source: https://ozone.unep.org/sites/default/files/2019-08/MP_Handbook_2019_1.pdf

https://github.com/openclimatedata/montreal-protocol-controlled-substances

This report also has up-to-date numbers (I think) but is a bit harder to extract:

https://www.esrl.noaa.gov/csd/assessments/ozone/2018/

**Comment by cahartin** [comment]
@mnichol3 take a look at the [RCMIP] (www.rcmip.org) emissions to see which gases we need to include

**Comment by kdorheim** [comment]
Hi @mnichol3, @bpbond  and I are going through and trying to organize/triage all the open Hector issues. It looks like you were assigned to work on this and we are curious how much/if any progress was made on this? Thanks!

**Comment by ssmithClimate** [comment]
@ouyang363 has also been looking at F-gases in hector and GCAM and may have some thoughts.
