### ISSUE TITLE
Invalid units in `sendmessage` are silently converted to `U_UNDEFINED`

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#327]
Currently, passing bogus units to a Hector core from the R interface (via `setvar -> sendmessage`) will silently convert them to `Hector::U_UNDEFINED`:

https://github.com/JGCRI/hector/blob/master/src/rcpp_hector.cpp#L307-L309

This should probably at least throw a warning, right? Or should it be an outright error, as the commented code suggests?

**Comment by bpbond** [comment]
This does not seem optimal; this should be an out-and-out error, agreed.
