### ISSUE TITLE
Retrieve atmosphere-land and atmosphere-ocean flux time series 

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#328]
Currently, neither `LAND_CFLUX` nor `OCEAN_CFLUX` accept date values -- only the values for the current time step. I have a personal stake in this because "total C sequestration" is tier 1 variable for RCMIP. However, both of these seem like useful diagnostic variables and could be good targets for calibrating Hector's C cycle to CMIP models, etc.

I think the following changes (on a branch of my Hector fork) accomplish this, but I may be missing something:

https://github.com/ashiklom/hector/compare/concentration-constraint..track-cfluxes

**Comment by bpbond** [comment]
(i) I agree this is useful and (ii) that code looks like what's needed. 👍

**Comment by cahartin** [comment]
@ashiklom has this been merged in?  @mnichol3 may have found this issue with other variables wihtin the ocean component.

**Comment by ashiklom** [comment]
No, not merged. I can submit a PR about just that...or @mnichol3 can cherry-pick the commit linked above as part of a larger time-series pull request.
