### ISSUE TITLE
Remove onelineocean

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#332]
I personally have never gotten the `onelineocean` component to successfully run, and it seems to be deprecated anyway in favor of an ocean model with multiple lines. Per @cahartin 's suggestion, we should probably just remove it from the code altogether.

Some additional context:

- The component header file: https://github.com/JGCRI/hector/blob/master/inst/include/ocean_component.hpp
- The component source file: https://github.com/JGCRI/hector/blob/master/src/onelineocean_component.cpp
- Line initializing the `onelineocean` component in all cores by default (possibly its own issue): https://github.com/JGCRI/hector/blob/e97ff4ef4697dbcdddc25aed02214a29452992e5/src/core.cpp#L117
  - Related discussion on Confluence for GCAM-Hector update PR: https://stash.pnnl.gov/projects/JGCRI/repos/gcam-core/pull-requests/86/overview?commentId=28645
- #167 is a related issue

**Comment by bpbond** [comment]
👍  My only comment here is that `onelineocean()` is a window into the past–Hector's past, that is. It was one of the very first things we coded.

**Comment by kdorheim** [comment]
Was this replaced by DOEClim? Awesome that this is a window into Hector's first soul but even if we remove it shouldn't we be able to revisit it via version control? 🤔

**Comment by bpbond** [comment]
Yes, we should be able to. It was replaced by Corinne's ocean compartment model.
