### ISSUE TITLE
Direct SO2 and tropospheric O3 radiative forcings not exposed to R interface

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#333]
Identified by @ssmithClimate and @brinday -- could one of you clarify exactly which RFs are missing?

This may end up being resolved by @mnichol3's work on #330.

**Comment by brinday** [comment]
Direct SO2 and Trop O3 are not reported out.
Additionally the categories: "forcing-Montreal" and "forcing-RCP" are not reported out, but I'm not sure if these are just groupings of other species that are reported out.

**Comment by mnichol3** [comment]
I haven't modified the forcing component file (I'm assuming that's where the RFs would be) while working on [#330](https://github.com/JGCRI/hector/issues/330), but this is definitely something I can look into

**Comment by ashiklom** [comment]
@mnichol3 Probably easier to make that a separate PR -- smaller changes are almost always easier to review and test.

**Comment by brinday** [comment]
I misunderstood this issue. The issue is that Dir SO2 and Trop O3 are not reported in GCAM. They are reported in the hector R package.

**Comment by mnichol3** [comment]
Can confirm Dir SO2 & O3 are reporting in the R package

**Comment by cahartin** [comment]
@ashiklom @mnichol3 can we close this?

**Comment by ashiklom** [comment]
Yeah, this is a GCAM-Hector coupling issue, not a Hector issue, so migrated to https://github.com/JGCRI/gcam-core/issues/86.
