### ISSUE TITLE
Coefficients missing for reactive species in oh_component

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#338]
The coefficients in the oh_componet for CH4, NOx, CO and NMVOC are -1.0.  These should have coefficients corresponding to each species.

See Tanaka 2007 table 2.1 and Meinshassen et al. 2011 equation A30

**Comment by cahartin** [comment]
@ssmithClimate When we tackle this issue keep in mind any potential updates to these values or the code.

**Comment by ssmithClimate** [comment]
Turns out these are ok after all. The coefficients are in the INI file. 

The code was confusing because increasing emissions resulted in a negative delta. Propose to flip signs (correcting for typo in Meinshausen etal 2011 Eq. A31). This results in no change in the results.

**Comment by cahartin** [comment]
@ssmithClimate did you make this change?

**Comment by ssmithClimate** [comment]
No change was needed. I do have a branch that I think is clearer. I'll submit a PR for that.
