### ISSUE TITLE
Replace Hector Wiki with Hector Manual 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#344]
The information on the Hector wiki is currently out of date. Do we want to update the wiki or do we want to replace the information on the wiki with a link to the Hector manual that will be automatically updated with every PR? (Shout out to @ashiklom for this awesome development)

@cahartin, @bpbond, and @rplzzz what are your thoughts? Do we see a need to continue the development and support of the Hector wiki?

**Comment by ashiklom** [comment]
See also discussion in #280.

**Comment by cahartin** [comment]
addressed in PR #345
