### ISSUE TITLE
Clarify forcing names

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/hector#352]
Stratospheric H2O and troposphere ozone forcing are not clearly named. Perhaps update to clarify: RF_H2O -> RF_StratH2O and RF_O3 -> RF_TropO3? This may break interfaces that look for the older names.

**Comment by mnichol3** [comment]
Is it sufficient to only update the names of the exported `rcpp` functions in `rcpp_constants.cpp`? I.E.,
```
String RF_O3() {
return D_RF_O3;
}
```
becomes
```
String RF_TropO3() {
return D_RF_O3;
}
```
This would provide clarification for the user, but would keep the changes limited to the R wrapper (not update the names in the `.ini` or emission files, etc)

**Comment by ssmithClimate** [comment]
Good question. Would be good to hear from @cahartin and @kdorheim  on that!

**Comment by cahartin** [comment]
I'm inclined to update all the code in case we have future developments like stato_O3.

**Comment by mnichol3** [comment]
@cahartin good idea!
