### ISSUE TITLE
Cannot retrieve atmosphere -> land C flux for first year (1745)

### ISSUE THREAD

**Issue by ashiklom** [JGCRI/hector#354]
The way it is currently implemented (#341), atmosphere -> land C flux is calculated in `simpleNbox::stashCValues`, which is never called for the very first time step (by default, 1745). As a result, the first year that atmosphere-land C flux can be retrieved is 1746.

**Comment by kdorheim** [comment]
@bpbond is this on your radar? Do you know if it could pose a problem for the carbon tacking work?

**Comment by bpbond** [comment]
Not at all on my radar. Thanks. No, I don't think so?

**Comment by bpbond** [comment]
This is an artifact of the way Hector treats dates: "1746" in the output stream means "1746.0" = "January 1, 1746". So the NBP (in the v3 nomenclature) that we retrieve at this timepoint is for the calendar year 1745 (1/1/1745-12/31/1746).

So, closing, but let's make sure the documentation addresses this point.
