### ISSUE TITLE
Hector Reference Temp

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#359]
There are a few Hector issues that I need to open but GitHub is being weird 

Hector temperature output is returned as an anomaly and there are several outstanding questions. 

1. Where does Hector's reference temperature come from? In the `ocean_componet.cpp` there is a line that say 
```
  // delta T is added 288.15 to return the initial temperature value of the surface box
``` 

where does 288.15K come from? and what year is it for? 

2. What do we want Hector's reference temperature to be? Where should it come from? What period of time? Do we want it to be adjustable?

**Comment by kdorheim** [comment]
@stephpenn1 can you add the info from you search? and include the relevant text?

**Comment by bpbond** [comment]
The 288.15 is 273.15 + 15; we assume that the preindustrial global mean temperature was, roughly, 15 C.

**Comment by kdorheim** [comment]
Okay preindustrial global mean temperature from what year? 1850, 1750, it is an average over a period?

**Comment by bpbond** [comment]
My memory is that it's just a broad preindustrial mean; not intended to be super-precise either numerically or to a specific point in time.

**Comment by stephpenn1** [comment]
> "With the average surface temperature of the Earth of about 15°C (288 K)"

This is from the _AR5 Summary for Policymakers, Technical Summary and Frequently Asked Questions Glossary_ term: **Energy budget (of the Earth)**, see screenshot below (full document [here](https://www.ipcc.ch/site/assets/uploads/2018/03/WG1AR5_SummaryVolume_FINAL.pdf)) I can't quite find what time period they calculated that value from but will keep looking.


![Screen Shot 2020-02-25 at 1 37 40 PM](https://user-images.githubusercontent.com/20341158/75276389-0d893300-57d4-11ea-800a-1f6d615bcbf6.png)

**Comment by kdorheim** [comment]
@bpbond fair enough but when we are talking about calibrating Hector to ESM data it matters what the value is and what the reference period is

**Comment by bpbond** [comment]
@kdorheim 🤷‍♂ this isn't a use that it intended for originally.

**Comment by kdorheim** [comment]
I think that we can close out this issue if we add some more inline text to `ocean_componet.cpp` explaining that the reference preindustrial temp is 288 K and some source.

**Comment by kdorheim** [comment]
To recap, Hector runs with anomalies to convert to absolute one can use the value of 15C or 288.15K, this happens in the ocean component where the ocean chemistry need absolute temperature in its calculations. 

@bpbond does this sound correct to you, 👌 to close this issue?

**Comment by bpbond** [comment]
Yes it does, and yes OK to close! Thanks.
