### ISSUE TITLE
Global Mean Temp (GSAT or GMST)

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#360]
Does Hector calculate global mean air surface temp or global mean surface temp? Does it matter for SCMs?

**Comment by bpbond** [comment]
I've thought of it as 2 m air temperature, but don't know if that's formally defined anywhere.

**Comment by kdorheim** [comment]
RCMIP was interested in `Surface Air Ocean Blended Temperature Change` aka GMST instead of GSAT. 

Talking with @ssmithClimate this is something we should be able to calculate from Hector output. Here are some notes from a slack conversation about it. 

```
#define D_LAND_AIR_TEMP         "Tgav_land"
#define D_OCEAN_SURFACE_TEMP    "Tgav_ocean_ST"
#define D_OCEAN_AIR_TEMP        "Tgav_ocean_air"

Right now hector reports global temperature as:
temp[tstep] = flnd * temp_landair[tstep] + (1.0 - flnd) * bsi * temp_sst[tstep];
temp_oceanair = bsi * temp_sst[tstep];
So its reporting now surface air temperature as Tgav, but you can report blended temperature by just calculating Tblend =  flnd * temp_landair[tstep] + (1.0 - flnd) * temp_sst[tstep]; (since flnd is a physical constant and the other two variables are reported out). (edited) 

flnd is the global surface fraction of land.
```

**Comment by kdorheim** [comment]
Things to Think About 
1.  Does GMST and GSAT actually diverge in the simple climate models?
2. If GMST is different. Should we calibrate this variable with observations instead of (talk to @claudiatebaldi)
3. If GMST is going to be an output used in the calibration process should it be written out as an output instead of something that can be back calculated from Hector output?

**Comment by kdorheim** [comment]
So it looks like there is a small difference between the GMST and GAST, at most it is a difference of 0.03 degrees in the year 2100. 

![image](https://user-images.githubusercontent.com/27299759/92663809-4e5c1b80-f2d0-11ea-9f2b-d7294005a57d.png)

```
> summary(SE)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.000e+00 2.210e-05 5.606e-05 4.171e-03 4.902e-03 2.979e-02 
```

**Comment by claudiatebaldi** [comment]
Is there a way to figure out a priori if the two should be identical or not?

A 0.03 difference in year 2100 (under which scenario?) seems difficult to take seriously but I think we should be able to know if there is any reason for there to be a difference.

**Comment by ssmithClimate** [comment]
This seems surprisingly small. Ocean surface vs ocean air temperatures differ in hector by 30% (bsi = 1.3). So I would expect to see the absolute value of the two differ by something of that magnitude (a bit smaller since land surface temperature is the same in both cases).

**Comment by kdorheim** [comment]
It is a difference in SSP370 (I've added that information to the post). Hmmm @claudiatebaldi I that we need a better understanding of Hector's ocean component to understand why these two time series are different and if they should be in Hector. This being said now I am conflicted about submitting the blended temperature results to RCMIP II. On one hand it would be helpful to see how Hector results differ from the other models, but also it seems suspect.

**Comment by claudiatebaldi** [comment]
From what Steve says it should be straightforward to look at a time series of ocean surface temperatures and compare it to the ocean-only TAS and see if they are different. Or am I missing something?

**Comment by ssmithClimate** [comment]
Interesting.  Even in the historical period I was expecting the difference should be larger. If historical temperature change is 0.6, then 30% of that is 0.18, which is much larger than the difference in the graph.  

By 2100 if the overall scale of temperature change is 3 degrees, then ocean air vs ocean surface temperature should be different by almost a degree. Averaged with land I was thinking that should show up as something larger.

(And we could definitely output both of these directly from hector.)

**Comment by kdorheim** [comment]
Hector does not report out a time series of the SST but here is a plot comparing the GMST back calculated, the Tgav and the Tgav ocean air

![image](https://user-images.githubusercontent.com/27299759/92741799-fd3e3d00-f34c-11ea-8711-8a80f2abcdf0.png)

**Comment by claudiatebaldi** [comment]
What is Tgav and Tgav_ocean_air?

And by the way, the expectation is that GSAT > GMST in the future. So @ssmith<https://jgcri.slack.com/team/U1EH4JKK3> when you say ocean T and ocean air T differ by 30% which one is bigger?

Also, @kdorheim<https://jgcri.slack.com/team/U4XNX82AH>, looking at your first plot (aside from the order that is opposite to what is expected) the gap between the two time series looks bigger than 0.03 to me.

**Comment by kdorheim** [comment]
@claudiatebaldi you are correct 🤦‍♀️ I was reporting MSE, the max difference between the GMST and GAST is `0.1725936`.

**Comment by ssmithClimate** [comment]
@claudiatebaldi 
temp_oceanair = bsi * temp_sst[tstep];
(bsi = 1.3 in hector now)
So ocean air temperature change is larger than sea surface temperature change

**Comment by claudiatebaldi** [comment]
So the first plot does not make sense, correct?

**Comment by kdorheim** [comment]
@claudiatebaldi @ssmithClimate @bpbond please take a look at https://rpubs.com/kdorheim/661078, as @claudiatebaldi pointed out the earlier plots do not make sense, now I believe they do. The plots from last week were incorrect, a product of sloppy/rushed work, my apologies.

**Comment by claudiatebaldi** [comment]
That’s good, nice work.
I don’t know if and how hector would account for this but it is expected that the difference becomes larger the larger the warming, having to do with the melting of sea ice with larger warming.

**Comment by ssmithClimate** [comment]
Cool! I'm thinking what is happening is that when there is a bit volcanic cooling, the land/ocean temperature difference reverses, which acts to "reset" the GMAT/GMST difference as the difference is temporarily in the opposite direction. Then since Pinatubo there's been no net cooling so the difference then just accumulates. And is larger overall because absolute magnitudes are larger.

**Comment by ssmithClimate** [comment]
We could think about parameterizing surface Albedo as a function of warming to account for melting ice and changing snow cover, but at present I'm pretty sure its constant.

**Comment by claudiatebaldi** [comment]
What I want to understand is where the bsi comes from. I thougt bsi was the land/ocean ratio, while here it is used to go from sst to ocean air temperature…so I need to sit on this a bit longer to understand of we are baking in the result or what.

**Comment by ssmithClimate** [comment]
From doeclim in the hector code:
   const double bsi = 1.3;               // warming factor for marine surface air over SST (due to retreating sea ice)
(In: temperature_component.hpp)
(That's the explanation given, but there's no mechanism there. Its just a constant that represents how much ocean air temperature warms relative to sea surface temperature.)

(Then, for completeness, there's a second constant, rlam = 1.43 that is the ratio of land clim. sens. and sea surface clim. sens. Which seems may not be sensitive enough, given Skylar's results.)

**Comment by claudiatebaldi** [comment]
Ok, so it is a baked in result, and it does somehow represent retreating sea ice. So for RCMIP purposes it will be important to let them know this is hardwired, nothing to learn here.

**Comment by cahartin** [comment]
Interesting thread!  I have few questions
1. the correct document is the rpubs one where the temperature difference is 0.4deg?
2. are these 2 metrics be included in Hector's output?
3. Hector does produce a time series of SST for the H and L latitude boxes within the ocean carbon cycle component. Do you know the results here compare?
