### ISSUE TITLE
Cold bias in RCMIP

### ISSUE THREAD

**Issue by mnichol3** [JGCRI/hector#361]
Hector displays a cold bias compared to other models in RCMIP.

Some diagnostic plots are below

[version-compare.pdf](https://github.com/JGCRI/hector/files/4339067/version-compare.pdf)
[input_emissions-rcp60.pdf](https://github.com/JGCRI/hector/files/4339082/input_emissions-rcp60.pdf)
[input_emissions-rcp45.pdf](https://github.com/JGCRI/hector/files/4339083/input_emissions-rcp45.pdf)
[forcings.pdf](https://github.com/JGCRI/hector/files/4339086/forcings.pdf)
[conentrations.pdf](https://github.com/JGCRI/hector/files/4339087/conentrations.pdf)
[emissions-n2o.pdf](https://github.com/JGCRI/hector/files/4339088/emissions-n2o.pdf)

**Comment by ssmithClimate** [comment]
Hmmm, so N2O forcing is still off. Suggest we fix that and then see where we are. @mnichol3, which lines are which in the n2o emissions graph?

**Comment by ssmithClimate** [comment]
From N2OComponent::run
```
N2O_emissions.get( runToDate ).value( U_TG_N )
```
it would seem perhaps the code is expecting emissions in Nitrogen units, whereas the RCMIP input emissions are in units of N2O. Is that conversion happening somewhere? (In older versions, its possible emissions were input in N units.)

**Comment by kdorheim** [comment]
@ssmithClimate that was exactly the issue!! @mnichol3 and I have resolved this issue with https://github.com/ashiklom/hector-rcmip/pull/8.
