### ISSUE TITLE
Expose Flux Variable Bindings 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#362]
This is an issue requested by Dawn (I think she probably needs to be added as a Hector collaborator). 

An another example of when we did this was with pull request #319. Which could be a helpful starting point but I could also take a stab at one of them first and make some notes.

**Comment by bpbond** [comment]
> collaborator

I'll take care of this.

**Comment by bpbond** [comment]
To clarify, I just mean I'll get her added to JGCCRI/hector.

**Comment by kdorheim** [comment]
Ahhhh thank you! Sorry about that I was confused.

Sent from my iPhone

On Mar 17, 2020, at 5:50 AM, Ben Bond-Lamberty <notifications@github.com> wrote:

﻿

To clarify, I just mean I'll get her added to JGCCRI/hector.

**Comment by kdorheim** [comment]
@dawnlwoodard could you add the list of variables you'd like to have exposed?

**Comment by dawnlwoodard** [comment]
I'm trying to get at all the net carbon fluxes. So the ones that don't seem to be available are NBP and ATM_OCEAN_FLUX_HL and ATM_OCEAN_FLUX_LL.

**Comment by cahartin** [comment]
I think these variables are not time series and so need some extra work in order to be exposed. 
 @mnichol3 was working on this earlier this year.

**Comment by dawnlwoodard** [comment]
Yeah @kdorheim and I were just discussing that on slack.

**Comment by dawnlwoodard** [comment]
Looks like these are actually exposed now. I think we can close this issue. That said, there is a separate issue with NBP (aka atm_land_flux) that it doesn't seem to have data for 1745, whereas other variables do. Creating a different issue for this.

**Comment by bpbond** [comment]
Can this be closed?
