### ISSUE TITLE
N2OComponent Clarifying and Documentation Question

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#364]
As part of trying to address why Hector's cool bias for RCMIP @mnichol3 has been looking into a potential issue with N2O emissions. As we have been looking into it something that I am curious/confused about is Hector's N2O component. 

@cahartin @ssmithClimate @bpbond @pralitp I am hoping that you can shed some clarity on what is going on. 

Based on the emissions files it looks like N2O is being read in as `MtN2O-N/yr`. Then as part of the N2O component the emissions are converted to a concentration, the Hector core reads in the N2O concentration. Then Hector outputs returns the N2O concentrations? Is this correct? 

Questions 
* Why does the Hector core return N2O concentrations instead of emissions? 
* Is this the case for other non-CO2 GHGs?

**Comment by ssmithClimate** [comment]
As far as I know the data flow is the same for all the well-mixed GHG species, which is, emissions -> concentrations, then the forcing component takes in whatever information it needs to calculate each forcing component (concentrations for well-mixed GHGs, emissions for aerosols, etc.).

**Comment by kdorheim** [comment]
Notes from CH  
> check out the tanaka 2007 thesis (Aggregated carbon cycle, atmospheric chemistry, and climate model (ACC2): Description of the forward and inverse modes.).  we convert to concentrations b/c N2O works with CH4 and their concentrations are dependent upon each other.

**Comment by kdorheim** [comment]
Update for some reason the output stream returned by Hector does not include `N2O_emissions` but returns `N2O` in units of concentration, this behavior is different from the methane and should be updated.
