### ISSUE TITLE
Add systematic white space tests

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#366]
PR #353 removes the trailing white space that is added to scripts in different editing tools. @bpbond and myself think that it might be worth while to add some sort of github actions, unit tests, or something of that nature to prevent PRs with the trailing white space from being merged into Hector. 

Something we discussed was using https://github.com/jimhester/lintr to create a github actions issue, but this might only work for the `.R` files ideally we would want this test to also check the C++ files.

**Comment by kdorheim** [comment]
Another idea would be to add some sort of unit test or CI that can check for spelling, a starting point could be with https://docs.ropensci.org/spelling/

**Comment by bpbond** [comment]
I feel like the false positives would kill us here, but good to consider! Thanks.

**Comment by kdorheim** [comment]
Haha yes and the package is set up to prevent the false positives with a word list and it only works on markdown text.

**Comment by bpbond** [comment]
Also the R package code could _easily_ be checked for style consistency; example GitHub Actions file [here](https://github.com/ropensci/drake/blob/main/.github/workflows/lint.yaml).

**Comment by ssmithClimate** [comment]
I'm interested to see what you find works out for white space checking, would be useful for CEDS as well.

Have you also dealt with line ending consistency? I just found this:
https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings

**Comment by bpbond** [comment]
Isn't CEDS in R @ssmithClimate ? If yes see my link in previous message, which shows how the `drake` package uses the `lintr` to enforce consistent style on all PRs. You can have one of the `lintr` tests be extraneous white space I believe, so that if any is present, the PR check will fail.

**Comment by ssmithClimate** [comment]
Thanks @bpbond. Yes its in R, and we would also want to enforce this in .csv files as well.

**Comment by bpbond** [comment]
So I just checked and we're already running a trailing-whitespace linter, so good there. Not inclined to worry about spelling or line ending checks for now (esp. since we haven't had any problems with the latter).

OK to close @kdorheim ?
