### ISSUE TITLE
Code breaking changes 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#368]
@bpbond and I would like code breaking PRs changes to be reserved for the PRs associated with a larger  version change of Hector (moving from a v2  -> v3) for example. I've opened this issue to keep track of some of the PRs we hav/will merge that have follow on items to be addressed during the larger version changes.

**Comment by kdorheim** [comment]
- [ ] #358 will contain two ini files for the RCP 6.0 scenario to prevent code breaking changes but when we transition to a new version of hector (v2.5 or v3) the ini file for RCP6 should be removed.

**Comment by bpbond** [comment]
@kdorheim Can this be closed?
