### ISSUE TITLE
Question: Does Hector back calculate emissions from concentrations? 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#369]
This came up during a conversation with @ssmithClimate 

```
I had asked Malte if they had global emission totals for all the F-gases at hand for the CMIP6 history up to 2015 (evidently they can generate those - they had done that for RCPs, which is probably what we have in hector). So what they do is constrain MAGICC to the historical F-gas concentrations and back out the global emissions consistent with that.
```

Does Hector also have this capability? If so where is it documented? If Hector does not have this capability do we want to develop it?

**Comment by bpbond** [comment]
No, Hector can't constrain to an F-gas total right now.

This strikes me as a pretty esoteric/specific need, but then again I don't work in this area.

**Comment by kdorheim** [comment]
But if you constrain CO2 concentrations does Hector calculate the emissions that would get you to those concentrations?

**Comment by bpbond** [comment]
No. Everything proceeds normally within a tilmestep, but the difference between the computed [CO2] and [CO2constrain] is dumped into the deep ocean.

**Comment by ssmithClimate** [comment]
Just to be complete, I thought hector could run historically with proscribed concentrations of CH4, N2O, etc? Or is it only emissions?

**Comment by cahartin** [comment]
@ssmithClimate we spoke about doing that a while back but never implemented it.   The MIT group has this capability and it came up a lot in discussion with them when were working together.

**Comment by bpbond** [comment]
Emission constraints are always available, as they're inputs. Re concentrations, we can constrain to [CO2], total radiative forcing, and global mean temperature.

**Comment by kdorheim** [comment]
> Just to be complete, I thought hector could run historically with proscribed concentrations of CH4, N2O, etc? Or is it only emissions for those gases?

With the current version of Hector you should be able to run Hector with prescribed concentrations of some non-CO2 ghgs.

**Comment by kdorheim** [comment]
The answer is no, Hector does not have this capability.

**Comment by cahartin** [comment]
@kdorheim With the new R interface Hector has this capability.
https://jgcri.github.io/hector/articles/hector_apply.html

**Comment by kdorheim** [comment]
@cahartin interesting does c++ hector not have this capability?

**Comment by bpbond** [comment]
Nope

**Comment by kdorheim** [comment]
Okay so we should highlight that this is a feature of R hector but not for users running the C++ executable. We should also have someone test which concentrations/emissions this works with. It would be nice if it was all of them  but part of me suspects that it might just be co2

**Comment by bpbond** [comment]
@cahartin Thanks for the clarification. In that sense, C++ Hector 'has' it too, in the sense you can run it lots of times until your emissions produce the concentrations you want. The R package certainly makes this easy though.

@kdorheim No this method (in the link Corinne provides) applies to any input/output optimization you want to do.

**Comment by cahartin** [comment]
2 thoughts: 
1. Will this take into account the interaction between N2O and CH4?
2. Can the code handle a full time series and not just a 2100 target?

**Comment by bpbond** [comment]
>Will this take into account the interaction between N2O and CH4?

Does Hector model this? I don't know offhand. If yes, yes, if not, no.

>Can the code handle a full time series and not just a 2100 target?

The current example code returns "a vector of discrepancies" between Hector's output and a single target value. No reason you couldn't have a target vector as far as I can see.

**Comment by ssmithClimate** [comment]
The N2O - CH4 interaction is forcing, so if its a concentration constraint then it won't matter. If you do a forcing constraint, it would be taken into account if you pass into hector the appropriate emissions path for the other gas.

**Comment by kdorheim** [comment]
So the answer is no when we run Hector with concentration constraints the emissions time-series is not updated to reflect the new concentrations.  

```
library(hector)
library(magrittr)
library(dplyr)
library(ggplot2)

ini <- system.file("input/hector_rcp45.ini", package = "hector")
core <- newcore(ini)

run(core)

fetchvars(core, 1900:2100, vars = c(GLOBAL_TEMP(), EMISSIONS_CH4(), ATMOSPHERIC_CH4())) %>% 
  mutate(scn = "rcp 45") -> 
  out1

reset(core)

out1 %>% 
  filter(variable == ATMOSPHERIC_CH4()) %>%  
  mutate(value = value * 2) -> 
  new_out

setvar(core = core, dates = new_out$year, var = CH4_CONSTRAIN(), values = new_out$value, unit = getunits(CH4_CONSTRAIN()))
reset(core)
run(core)

fetchvars(core, 1900:2100, vars = c(GLOBAL_TEMP(), EMISSIONS_CH4(), ATMOSPHERIC_CH4())) %>% 
  mutate(scn = "rcp 45 * 2 (for CH4 concentrations)") -> 
  out2

bind_rows(out1, out2) %>% 
  ggplot(aes(year, value, color = scn)) + 
  geom_line() +
  facet_wrap("variable", scales = "free")
```

![image](https://user-images.githubusercontent.com/27299759/125315216-e36edd00-e304-11eb-818b-14e43b3c4e32.png)

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.5  dplyr_1.0.3    magrittr_2.0.1 hector_2.5.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6       rstudioapi_0.13  tidyselect_1.1.0 munsell_0.5.0    colorspace_2.0-2 R6_2.5.0         rlang_0.4.10    
 [8] tools_4.0.3      grid_4.0.3       gtable_0.3.0     withr_2.4.0      ellipsis_0.3.2   digest_0.6.27    yaml_2.2.1      
[15] tibble_3.0.5     lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4      farver_2.1.0     vctrs_0.3.8      glue_1.4.2      
[22] labeling_0.4.2   compiler_4.0.3   pillar_1.4.7     generics_0.1.0   scales_1.1.1     pkgconfig_2.0.3 
```

**Comment by kdorheim** [comment]
For other related questions please open a new issue.
