### ISSUE TITLE
Tracer pool

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#374]
@dawnlwoodard and I had a cool idea: a tracer pool data type that would let us arbitrarily track where C (say) goes in the model. For example, we might want to know where all the SOC emitted over a run ends up.

This would be so cool!

It seems like it would require a tracked-pool class to handle things under the hood, so that Hector components could just mostly multiply, add, compute fluxes, etc., as they do now.

**Comment by bpbond** [comment]
Also we don't think any other simple climate model has anything like this?!?

**Comment by ssmithClimate** [comment]
If anyone does it would be the Bern model. (probably not the simplified version though).

**Comment by kdorheim** [comment]
That's an awesome idea!

**Comment by bpbond** [comment]
It would be nontrivial to implement, but we were like, wow would open the door to some super cool analyses.

**Comment by kdorheim** [comment]
something kinda like this? 

https://twitter.com/RARohde/status/1131224334402555905

**Comment by dawnlwoodard** [comment]
@kdorheim yes! Though of course with the ability to trace every pool, not just fossil fuels. Which means we would want to treat fossil fuel emissions like a carbon pool in terms of this capability.

**Comment by bpbond** [comment]
Long drive today and I had a chance to think this through. I think actually it'll be straightforward to implement for the carbon cycle.

Basically a `tracked_pf` (tracked pool/flux) will take the place of `unitval` for the carbon cycle elements. Each `tracked_pf` is a map of origin names (key) and unitvals (values), with the keys giving the ultimate origin of the 'package' of carbon. A subtraction of two `tracked_pf` objects (or a `tracked_pf` and a unitval) debits from each pool proportionally; an addition operation means combining the maps of two objects. This setup will let us do a drop-replacement wrt the carbon cycle calculations; that code will be unchanged.

```c++
class tracked_pf {
    std::map<string, unitval> origin_map;

public:
   
    static std::string unitsName( const unit_types );
        
    tracked_pf();
    
    void set( initial, unit_types, double );

    friend tracked_pf operator+ ( const tracked_pf&, const tracked_pf& );
      // use something like set_union to calculate a joint origin map of the two tracked_pf objects
    friend tracked_pf operator- ( const tracked_pf&, const unitval& );
      // debug the second argument (a flux) proportionally from the tracked pools of the first
    friend tracked_pf operator- ( const tracked_pf&, const tracked_pf& );
      // this just gets the unitval total of the second argument and calls method above
}
```

**Comment by bpbond** [comment]
Still noodling about this, after talking with @dawnlwoodard today.

The subtraction operation above worries me. I don't think you should be able to subtract a `tracked_pf` from another `tracked_pf`, only subtract a `unitval`. It's potentially too confusing otherwise? Hmm.

In addition to this, we'd have a new output visitor, `trackedCarbonOutputVisitor`. This would write the current state of the carbon stocks and fluxes–_with all source pool information_–to an output file.
* A CSV with variable,source_pool,quantity ?
* A CSV with one line per variable and timestep and one column per source pool? More efficient

**Comment by bpbond** [comment]
While talking with @dawnlwoodard and MH and CT today about this, I realized we'll want to attach a date to every C 'packet' in a `tracked_pf`, giving the date when it left its original pool. And/or the ability to tell tracked pf's to start tracking, as we might be interested in tracking C only after a certain date.

**Comment by bpbond** [comment]
https://github.com/skygering/carbonTrackerClass

**Comment by bpbond** [comment]
Le plan:

* @skygering Put [map version of tracked pool](https://github.com/bpbond/carbonTrackerClass/tree/bbl) into Hector and confirm compiles
* Convert earth_c and atmosphere to tracked pools. This will require a **temporary** unitval+trackedpf operation
* New output visitor to write out tracked pool information at each timestep (probably into a csv)
* Plot results from step 2
* R interface working with tracked pools ----> deal with this later
* Rest of terrestrial C cycle: LUC flux, NPP, litter, RH, soil
* Ocean ----> deal with this later
