### ISSUE TITLE
Remove hard-coded forcing calibrations

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/hector#375]
Most forcings are hard coded (e.g., forcing per unit BC). These are uncertain, and get updated over time, so it would be useful to make these parameters that can be set via API and configuration files.

Relevant to issue [#343](https://github.com/JGCRI/hector/issues/343).

**Comment by cahartin** [comment]
We would need to be careful with how these interact with the aerosol scaling parameter.  That parameter changes the relative radiative forcing efficiencies of BC, OC and SO2.

**Comment by kdorheim** [comment]
Will be closed with #463
