### ISSUE TITLE
Add Hector tag version documenation

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#376]
What is out protocol for tagging Hector version? How does that work? It is some combination of zenodo and github. Can we add some documentation about it so that it is clear to developers what needs to be done and to users what is going on?

**Comment by bpbond** [comment]
This is handled through my Zenodo account; a DOI is automatically minted for every GitHub release. The process is described [here](https://guides.github.com/activities/citable-code/).

![Screen Shot 2020-06-09 at 7 17 40 AM](https://user-images.githubusercontent.com/1956468/84141551-59798400-aa21-11ea-93f6-63e7bde9fa24.png)

We could add a Zenodo badge to the README as described in the last step of the linked document above.

**Comment by kdorheim** [comment]
Yea I think that would be great! I thought that the release page had disappeared and was very confused! It just moved location on the github page 😬. As for updating the tag, is that something we do every time a hectorPR is merged?

**Comment by bpbond** [comment]
No, we explicitly create tags and releases.

**Comment by kdorheim** [comment]
👍
