### ISSUE TITLE
Additional forcings

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/hector#377]
Hector is missing a few small forcing components that could be considered for inclusion.

1) Forcing from stratospheric O3. (This offsets a small amount of the positive forcing from ozone depleting substances such as CFCs.) AR5 values: –0.05 (–0.15 to +0.05) W/m2. (1750-2011).

2) Forcing from dust and nitrate aerosols. AR5: –0.10 (–0.30 to +0.10) and –0.11 (–0.30 to –0.03), respectively.

3) Combined contrails and contrail- induced cirrus. AR5: 0.05 (0.02 to 0.15)  W/m2.

**Comment by kdorheim** [comment]
Closed with #536
