### ISSUE TITLE
Clarify forcing names.

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/hector#378]
It would be useful to consider re-naming a couple of the forcing variables to be more descriptive and not ambiguous. 

Suggest: H2O -> StratH2O and O3 -> TropO3.

(Since H2O changes in the troposphere is a feedback and, therefore, included in the climate sensitivity. And stratospheric and tropospheric O3 forcings are generally treated separately as they have different drivers and time paths.)

**Comment by kdorheim** [comment]
This was closed with #432
