### ISSUE TITLE
Remove dplyr/tidyr dependencies 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#380]
To avoid the we have seen with other packages remove the tidyverse dependencies from hector. It looks like there are only a few in the the testing. 
@bpbond do we want to opt for the add data.table dependency instead?

**Comment by bpbond** [comment]
My first question would be: do we need a dependency at all? Can we just use base R functions?

**Comment by kdorheim** [comment]
Probably... I will look into it, that would be my preference as well.
