### ISSUE TITLE
Land-ocean warming ratio calculating Tgav in DOECLIM

### ISSUE THREAD

**Issue by skygering** [JGCRI/hector#390]
**Describe the bug**
I have a pull request in to introduce a tunable land-ocean warming ratio parameter into Hector. In my code, the new parameter is used to overwrite the land, ocean air, and sea surface temperature values. However, it does not overwrite the sea surface temperature and land temperature vectors that are used to calculate global temperature within the DOECLIM portion of `temperature_component.cpp`.  

This code has outputs as follows:
<img width="532" alt="land-ocean warming ratio" src="https://user-images.githubusercontent.com/60117338/90455922-38ca4c00-e0ac-11ea-9427-e15877c5dd3d.png">

When I tried to overwrite these vectors, the Hector outputs inverted from the previous results:
<img width="790" alt="Screen Shot 2020-08-11 at 2 03 03 PM" src="https://user-images.githubusercontent.com/60117338/90455323-a5dce200-e0aa-11ea-9357-f25b7ab644fc.png">

<img width="745" alt="InvertedFull" src="https://user-images.githubusercontent.com/60117338/90455313-a1b0c480-e0aa-11ea-9fdb-edc307550c38.png">

This suggests an error within the DOECLIM calculations or within the implementation of the land-ocean warming ratio implementation. 

**To Reproduce**
Any of the standard Hector input files reproduces this problem (RCP 2.6, 4.5, 6.0, or 8.5). The RCP 4.5 is used to produce the images above and thus is attached below: 
[hector_rcp45.ini.txt](https://github.com/JGCRI/hector/files/5087431/hector_rcp45.ini.txt)

I ran Hector using the R interface built from the branch land-ocean-warming-ratio. In order to reproduce the error, the code at the bottom of `temperature component.cpp` needs to be changed as specified in the comments. The current version of the code produces the expected results, but does not feed the land and sea surface temperatures back into the tgav calculations. 

**Expected behavior**
I expect global temperature and forcing to increase with increasing land-ocean warming ratio.

**Actual behavior**
With the code in `temperature_component.cpp` changed as specified in the comments, the global temperature and forcing decrease with increasing land-ocean warming ratio.

**Runtime and build environment (please complete the following information):**
 - OS: OS-X
 - Boost version you used to build Hector: 1.74.0
 - If running from R, output of `SessionInfo()`:
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       macOS Catalina 10.15.6      
 system   x86_64, darwin19.5.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2020-08-17                  
package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
 cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.2)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
 digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.2)
 dplyr         1.0.0   2020-05-29 [1] CRAN (R 4.0.2)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
 evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.2)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.2)
 generics      0.0.2   2018-11-29 [1] CRAN (R 4.0.2)
 glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.2)
 hector      * 2.5.0   2020-08-17 [1] local         
 htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.2)
 knitr         1.29    2020-06-23 [1] CRAN (R 4.0.2)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.2)
 pillar        1.4.4   2020-05-05 [1] CRAN (R 4.0.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
 R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.2)
 Rcpp          1.0.5   2020-07-06 [1] CRAN (R 4.0.2)
 rlang         0.4.6   2020-05-02 [1] CRAN (R 4.0.2)
 rmarkdown     2.3     2020-06-18 [1] CRAN (R 4.0.2)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
 tibble        3.0.1   2020-04-20 [1] CRAN (R 4.0.2)
 tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.2)
 vctrs         0.3.1   2020-06-05 [1] CRAN (R 4.0.2)
 withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.2)
 xfun          0.15    2020-06-21 [1] CRAN (R 4.0.2)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.2)

[1] /usr/local/lib/R/4.0/site-library
[2] /usr/local/Cellar/r/4.0.2_1/lib/R/library

**Additional context**
I started this project as SULI Intern (10-week project) and do not have time to follow the lead on this potential bug within DOECLIM.

**Comment by kdorheim** [comment]
Resolved as part of #562
