### ISSUE TITLE
Clarification on units

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#392]
I want to double check the units on N2O and SO2 emissions in the Hector input files.
The units for N2O are MtN2O-N/yr
The units for SO2 are Gg/yr

Is N2O Mt of N?
and is SO2 Gg of SO2 or S?

Thanks!

**Comment by bpbond** [comment]
Yes, megatons of N; Gg of SO2.

**Comment by cahartin** [comment]
Thanks @bpbond!  I'm still wondering about SO2. 

Below are the first few rows from the Hector emissions file.  It looks like the SO2_emissions column was converted from SOx MtS/yr to GgS/year by multiplying by 1000.   However, the units label is just Gg/yr.  

  |  
-- | --
  |  
MtS/yr | Gg/yr
SOx | SO2_emissions
0 | 0
0.098883 | 98.88265
0.116307 | 116.3065
0.133811 | 133.8108
0.151398 | 151.3979
0.16907 | 169.0705

**Comment by ssmithClimate** [comment]
What years are those emissions for?

**Comment by ssmithClimate** [comment]
In 2010 global anthropogenic SO2 emissions were 106 Mt SO2.

**Comment by cahartin** [comment]
that's just the first few years of the emissions file - 

Date
--
1765
1766
1767
1768
1769
