### ISSUE TITLE
Hector RCMIP Phase 1 citation

### ISSUE THREAD

**Issue by rgieseke** [JGCRI/hector#396]
We need a citation with creators and title for the Code repo (https://github.com/ashiklom/hector/releases/tag/rcmip-phase-1) for the final version of the RCMIP paper (cc @znicholls)

I'm a bit confused by the different versions (R package/C++ code), `citation` didn't really help me.
Could you provide me with what should be used @ashiklom or @kdorheim ?
Also not sure whether the version used is on Zenodo, is it?

GMD ideally wants something like:
```
    Model code
        Creator
        Title
        Publisher/repository
        Persistent identifier
        Publication year
    Randall, D., Dazlich, D., Heikes, R., and Konor, C.: CSU model for DCMIP 2016, Zenodo, https://doi.org/10.5281/zenodo.5800992018, 2017.
```

**Comment by bpbond** [comment]
Hi @rgieseke . I think the fundamental thing being cited is Hector, not its R package, and so while [Hartin et al. 2015](http://www.geosci-model-dev.net/8/939/2015/) is increasingly out of date, it's probably the best option. @kdorheim is the RCMIP version tagged so that the citation can be more specific?

But @kdorheim @dawnlwoodard we really need to get something newer published in 2021!

**Comment by rgieseke** [comment]
Sorry, if i have been unclear. GMD wants a citation for the model code itself (currently it's just a link to the GitHub repo). The model description papers are cuted.

When there is a Zenodo archive, there is a list of contributors used by default. 

https://zenodo.org/record/3144007

```bibtex
@software{robert_link_2019_3144007,
  author       = {Robert Link and
                  Ben Bond-Lamberty and
                  Corinne Hartin and
                  Alexey Shiklomanov and
                  bvegawe and
                  Pralit Patel and
                  Sven Willner and
                  Kalyn R. Dorheim and
                  Robert Gieseke and
                  Steve Smith and
                  Cary Lynch},
  title        = {JGCRI/hector: Hector version 2.3.0},
  month        = may,
  year         = 2019,
  publisher    = {Zenodo},
  version      = {v2.3.0},
  doi          = {10.5281/zenodo.3144007},
  url          = {https://doi.org/10.5281/zenodo.3144007}
}
```

But since you define authors etc. in your metadata i assume you might have a preference whom to have as authors for the model code.

**Comment by kdorheim** [comment]
Hi @bpbond and @rgieseke, @ashiklom is working on creating a zendo release for the version of Hector that was used in RCMIP I 👍

**Comment by kdorheim** [comment]
@rgieseke here is the citation and see below for the bib text, please let us know if you need anything else. 

Robert Link, Alexey Shiklomanov, Ben Bond-Lamberty, Corinne Hartin, bvegawe, Pralit Patel, … Cary Lynch. (2020, October 23). ashiklom/hector: RCMIP Phase 1 (Version rcmip-phase-1). Zenodo. http://doi.org/10.5281/zenodo.4121543

citation information in bib text format 
```
@software{robert_link_2020_4121543,
  author       = {Robert Link and
                  Alexey Shiklomanov and
                  Ben Bond-Lamberty and
                  Corinne Hartin and
                  bvegawe and
                  Pralit Patel and
                  Kalyn R. Dorheim and
                  Sven Willner and
                  Matt Nicholson and
                  Steve Smith and
                  Robert Gieseke and
                  Cary Lynch},
  title        = {ashiklom/hector: RCMIP Phase 1},
  month        = oct,
  year         = 2020,
  publisher    = {Zenodo},
  version      = {rcmip-phase-1},
  doi          = {10.5281/zenodo.4121543},
  url          = {https://doi.org/10.5281/zenodo.4121543}
}
```

**Comment by rgieseke** [comment]
Perfect, thanks a lot!
