### ISSUE TITLE
build issue: typo in makefile.standalone re LDFLAGS and linker arguments

### ISSUE THREAD

**Issue by payerle** [JGCRI/hector#403]
**Describe the bug**
There is a typo in the makefile.standalone file.  It has
``-Wl,-rpath $(BOOSTLIB)``
which is incorrect (missing the comma between rpath and $(BOOSTLIB))
As it currently stands, it causes the compiler to pass an empty -rpath flag to the linker, and the following $(BOOSTLIB) is passed as an argument to the compiler.

It should either be 
``-Wl,-rpath,$(BOOSTLIB)``
(with a comma between the rpath and $(BOOSTLIB)), or
``-Wl,-rpath -Wl,$(BOOSTLIB)``

**To Reproduce**
``wget https://github.com/JGCRI/hector/archive/v2.3.0.zip
unzip v2.3.0.zip
cd hector-2.3.0
BOOSTROOT=/my/path/to/boost make hector``

results in an error

**Expected behavior**
The code would compile

**Actual behavior**
``/software/spack/git.2020.05.14/lib/spack/env/gcc/g++  -L/software/spack-software/2020.05.14/linux-rhel8-ivybridge/gcc-8.4.0/boost-1.72.0-eptxcoh6ktxn3jtsfv3ble2lchvppnu4/lib -L. -Wl,-rpath /software/spack-software/2020.05.14/linux-rhel8-ivybridge/gcc-8.4.0/boost-1.72.0-eptxcoh6ktxn3jtsfv3ble2lchvppnu4/lib -o hector main.o -lhector -lm -lboost_system -lboost_filesystem
-Wl,-rpath was not followed by -Wl,*
``
 

**Runtime and build environment (please complete the following information):**
 - OS: Linux (RedHat Enterprise Linux 8.2), using gcc 8.4.0
 - Boost version: 1.72.0

**Additional context**

**Comment by bpbond** [comment]
Hi @payerle—good catch, thank you!

@kdorheim I don't understand why tests were passing.  It looks like that space got introduced in ffb523a. Will open an issue.

**Comment by bpbond** [comment]
Thanks again. Fixed in #404 .
