### ISSUE TITLE
"Hector in the wider world" wiki or documentation page?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#410]
A note from @cahartin 
>Hector is being coupled to Mimi – a modular platform to integrate IAMs and climate models. 
>https://www.mimiframework.org/#models_using_mimi

My response
>I feel like we need a list of stuff like this—the open climate folks, etc. A confluence page? A GitHub issue (better since open to the world)?

@kvcalvin said
>Agreed. What about a section/tab/page on the Hector Github wiki?

**Comment by kdorheim** [comment]
Could @leeyap add this to the pkgdown documentation update? @bpbond thoughts?

**Comment by bpbond** [comment]
Absolutely I think! @leeyap ?

**Comment by leeyap** [comment]
Sure thing! @kdorheim @bpbond 

Could you clarify what you'd like me to add to this new page? I'll get to work on it tomorrow.

**Comment by kdorheim** [comment]
We would like a page that better lists publications and the other things that feature hector. @bpbond does it look like this list is missing anything? 

* hector publications 
     * documentation manuscripts 
          * v1 https://gmd.copernicus.org/articles/8/939/2015/
          * v1 ocean https://bg.copernicus.org/articles/13/4329/2016/bg-13-4329-2016.pdf
          * v 2.5  https://doi.org/10.1029/2018EF001082
     * featuring hector to some extent 
         * https://gmd.copernicus.org/articles/13/5175/2020/
         * https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2020EF001900
         * Dawn's premafrost paper 
         * https://esd.copernicus.org/articles/10/729/2019/
         * https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2019GL085792
         *  https://doi.org/10.1029/2019EA000980

* hector in the wild world (this is somewhat of a catch-all category) 
    * https://www.mimiframework.org/#models_using_mimi
    * https://github.com/openclimatedata/pyhector
    * participant in RCMIP https://www.rcmip.org/ 
    * youtube video (https://www.youtube.com/watch?v=EFJS-buvGN8) (although the thought of this video being out there makes me want to vom)

**Comment by bpbond** [comment]
Looks good to me!

**Comment by rgieseke** [comment]
Pyhector also had an accompanying paper it that's helpful for you to keep track of (e.g. for funders): https://doi.org/10.21105/joss.00248

**Comment by bpbond** [comment]
Thanks @rgieseke !

**Comment by leeyap** [comment]
Thanks everyone (@kdorheim , @rgieseke , @bpbond)! 

I'll try to get a draft ready by early next week. Let me know if you think of anything else to add in the meantime.
