### ISSUE TITLE
Visual Studio Sln

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#415]
As of `bed6dab` Hector's [visual studio](https://github.com/JGCRI/hector/tree/master/project_files/VS) materials are out of date. The sln and sln libraries use the header/source code paths pre-Hector reorganization to support the R package. Because Hector C++ dev is supported with the Xcode and VSC  IDEs updating the VS sln is a low priority for the Hector development team. However, if a Hector community member builds the VS sln please let us know! The Hector team welcomes and values community contributions to Hector.

**Comment by kdorheim** [comment]
By 

>As of bed6dab Hector's visual studio materials are out of date

What I really mean is that we noticed on 2021-01-27 when Hector master was at `bed6dab` that this was a problem, my guess is that it has been a problem for over a year now and went undocumented until now.

**Comment by bpbond** [comment]
Closed in #516 

Why is GitHub auto-close not seem to work anymore?
