### ISSUE TITLE
merging historical and future emissions

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#422]
Is there an easy way to point the ini file to multiple emissions input files per gas? For example, I have a emissions files that start in 2005. Rather than writing code to match up and merge in historical and future emissions into one csv file, can Hector read in 2 emission files for each gas - a historical emissions and a future emissions file?

**Comment by bpbond** [comment]
My first response was "neat idea can't do it now" but...not sure. Have you tried it? E.g. having two lines in the INI file pointing to successive files?

**Comment by cahartin** [comment]
I am going to try it this week. I'll keep you posted.

**Comment by cahartin** [comment]
@bpbond looks to work!! Thanks for stating the obvious!

``ffi_emissions=csv:emissions/gcam_emissions.csv
ffi_emissions=csv:emissions/gcam_v5.3_emissions.csv``

**Comment by bpbond** [comment]
Oh that is COOL. I thought possible in theory but wasn't sure.
