### ISSUE TITLE
Unexpected halocarbon names in stay-positive branch

### ISSUE THREAD

**Issue by flannerydolan** [JGCRI/hector#426]
**Describe the bug**
After pulling the `stay-positive` branch, GCAM failed to build, throwing:
```did you mean HCFC142b``` and ```HCFC141b``` in `hector_model.cpp`
I changed the model component names within `hector_model.cpp` and the other places those names occur (`gcam-emissions.csv`, `RCP45_emissions.csv`, `component_names.hpp`)  to the suggested names, committed the changes, rebuilt GCAM (now successfully), but when trying to build the core gets dumped with:
```Assertion failed: Unknown model component: HCF22_halocarbon```
While it isn't failing on the other names that were fixed, I'm now unsure of what this name is supposed to be and if this is going to happen for all of the other halocarbons as well.

**To Reproduce**
Explain how to reproduce the behavior:
1. *what is the name of the input file needed?*
2. SSP 4 RCP 4.5 forced with IPSL and using the GEPIC crop model
3. Running in conjunction with GCAM.

**Expected behavior**
Expected GCAM to run normally.

**Actual behavior**
GCAM dumps the core when hector is being initialized before the first timestep.

``` Thu Feb 11 14:37:49 2021:WARNING:setData: Disabling onelineocean
Exception: msg:         Assertion failed: Unknown model component: HCF22_halocarbon
func:   getComponentByName
file:   core.cpp
ffile:  core.cpp

line:   519

terminate called after throwing an instance of 'h_exception'
  what():  Assertion failed: Unknown model component: HCF22_halocarbon
Aborted (core dumped) 
```

Log files are empty because hector did not run

**Runtime and build environment (please complete the following information):**
 - OS: Linux RedHat
 - Boost version you used to build Hector: boost_1_62_0

**Additional context**
I am trying to resolve many of these types of errors:

```ERROR:Receieve hector exception while running year 2058:
ERROR:* Program exception: msg:  	Assertion failed: atmos_c pool <=0
ERROR:func: 	sanitychecks
ERROR:file: 	simpleNbox.cpp
ERROR:ffile:	simpleNbox.cpp
ERROR:
ERROR:line: 	302
ERROR:
```
These do not appear in every run, nor always with a biofuel policy. They usually occur when certain ESMs (usually GFDL and IPSL) are used to force GCAM. If there is a better way of resolving this problem other than trying to pull the `stay-positive` branch, please let me know.

**Comment by bpbond** [comment]
Hi @flannerydolan 

Um...well first question, why are you trying to use  `stay-positive` at all? That's a developmental branch supporting work by @skygering — super cool work, but a long way from prime time. I'd recommend not touching it, and definitely not trying to run it under GCAM! Sorry if that wasn't clear.

**Comment by flannerydolan** [comment]
Ok I'll open a separate issue focused on the error from the bottom of the post then. Thanks!
