### ISSUE TITLE
V2.5 release

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#431]
**Describe the bug**
A few papers and GCAM output mention a Hector v2.5. However, there isn't a tagged release of Hector v2.5.

**To Reproduce**
For example, Dorheim et al., 2020
"Here we use Hector v2.5.0 to emulate the multiforcing historical and RCP scenario output for 31 concentration and seven emission-driven ESMs."

**Comment by rgieseke** [comment]
Should be this commit
https://github.com/JGCRI/hector/commit/84259b7356171aa170c8b68793b0e8c22256cfc2

(Would be nice to see this tagged and archived, makes it easier if i try to update Pyhector.)

**Comment by kdorheim** [comment]
Related to #376 we need some standard, potentially automated way of keeping track of tags/releases. 

@rgieseke please let us know what makes updating Pyhector easier 👍

**Comment by cahartin** [comment]
also the Hector output stream is either outdated or the comment is incorrect. 
# Output from hector version 2.2.2

**Comment by kdorheim** [comment]
See [here](https://github.com/JGCRI/hector/releases/tag/rcmip-tier1) for this release. 

As part of #376, #363, #194, and #183 we will address the issues related to versioning practices and version numbers reported in the output streams.
