### ISSUE TITLE
Ocean components outputs in basic run

### ISSUE THREAD

**Issue by jmemb** [JGCRI/hector#436]
When following the instruction of a [basic run](https://jgcri.github.io/hector/articles/intro-to-hector.html) with original INI files and trying to obtain PH_LL() or PH_LL (test <- fetchvars(core, 2005:2100, PH_HL())), there is the error "Unknown model datum: PH_HL". There is no error when retrieving most of the other outputs, but the only ocean component output which can be obtained is OCEAN_CFLUX().

**Comment by kdorheim** [comment]
Hi @jmemb thanks for opening this issue! I _think_ I know the cause of this problem but will need about a week to look into it. 👍

**Comment by jmemb** [comment]
Sounds great! Thanks a lot @kdorheim

**Comment by kdorheim** [comment]
@jmemb I just wanted to check in about this issue, while it is not 100% resolved we are working on it. You can follow our progress with PR #439.

**Comment by bpbond** [comment]
Resolved by #439

**Comment by kdorheim** [comment]
@jmemb  this issue has been resolved and merged into the master branch. If you reinstall Hector run `remotes::install_github('jgcri/hector')` you should be able to access the ocean variables now. 👍

**Comment by jmemb** [comment]
Yes! It works now, thank you very much @kdorheim!

**Comment by bpbond** [comment]
👏 👏 👏
