### ISSUE TITLE
Numerical differences total ocean carbon and the sum of carbon in ocean pools

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#440]
As part of #439 and the ocean unit tests (`ocecan_test.R`) we noticed that the C in the total ocean pool is not exactly equivalent to the sum of the C in the sub-pools (HL, LL, DO, IO). It is off by about 6 Pg C per timestep, this is relatively a small fraction of the C in the ocean pools.

**Comment by bpbond** [comment]
...but why is it off at all? Let's definitely follow up on this. Not in #439 though.

**Comment by leeyap** [comment]
@kdorheim okay to close?

**Comment by kdorheim** [comment]
Yup @leeyap I believe so!
