### ISSUE TITLE
Leeya July work - introductory material and skills

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#454]
Good morning @leeyap 

In addition to the resources @kdorheim  has given you, here’s a slide deck on data analysis in R using the ‘dplyr’ package: https://rpubs.com/bpbond/r-data-vcu. Given your programming background, and that you’ve already worked through some of the Swirl material, that might be a useful deck to go through (following along on the command line as you go).

Then, these two presentations on data visualization: https://rpubs.com/bpbond/727254 and https://rpubs.com/bpbond/727256

Finally, please read (lightly; this isn’t school and you’re not going to be tested on every detail) and we can discuss:
•	https://earthobservatory.nasa.gov/features/CarbonCycle 
•	https://besjournals.onlinelibrary.wiley.com/doi/10.1111/j.0022-0477.2004.00874.x 

The goal of all this is to build up your understanding of the global carbon cycle and how it’s modeled; introduce you to the tools you’ll need to work with Hector effectively.

**Comment by bpbond** [comment]
Hi @leeyap , here are my suggestions for next steps:

You’ve read about the Hector model; let’s dive in!
* The Hector manual is here: https://jgcri.github.io/hector/articles/manual/. Follow the instructions in the first part of the page on installing and building Hector to install its R package (don’t clone the Hector repository yet, just use devtools::install_github() to install it).
* Follow the instructions in the first vignette on using R Hector: https://jgcri.github.io/hector/articles/intro-to-hector.html. In particular, do the first part (“Basic run”) and reproduce the output, the look through (and hopefully do) the second section (“Setting parameters”).
* **Assignment:** if any of this documentation is unclear, or out of date, or could be improved, please [open an issue](https://github.com/JGCRI/hector/issues/new/choose).

Questions? Please let me know!

**Comment by leeyap** [comment]
Hi @bpbond , 

I finished going through the "Basic run" and "Setting parameters" vignettes. They were both fairly straightforward, but I was confused about one thing mentioned in "Setting parameters."

> Because changing Hector parameters can change the post-spinup equilibrium values of state variables, Hector will automatically run reset(core, date = 0) at the beginning of the next run call if it detects that any of its parameters have changed. This means that is not currently possible to change Hector parameters (such as β or preindustrial CO2) part-way through a run. However, it is still possible to change the values of certain drivers and state variables (such as the CO2 emissions) in the middle of a run.

I'm not sure exactly what this means by "post-spinup" or what the spinup process is in general.

Other than that, the two sections were clear and I caught no bugs.

Thanks!

**Comment by bpbond** [comment]
OK! Thanks. That would be a useful clarification to make in the documentation...are you up for (i) cloning the Hector repository, (ii) creating a branch, (iii) modifying the documentation, and (iv) opening a PR? I can assist.

**Comment by leeyap** [comment]
Yes, I can try! I'll let you know if I run into any issues. 

First, could you help me understand the paragraph I pulled above and what the spinup process is?

**Comment by bpbond** [comment]
Like many models, Hector has an initial—though optional—'spinup' mode that runs the carbon cycle _with no perturbation_ (i.e., no human emissions) until it stabilizes, i.e. the various carbon pools stop changing. In other words, it's in equilibrium. Then the model exits spinup mode, sets the year to 1750, and starts with its normal run.

**Comment by ssmithClimate** [comment]
Same can be true on other models for the ocean - the ocean has a very long equilibrium timescale, so often there are techniques used to speed up the thermal and chemical equilibrium of the ocean to a pre-industrial equilibrium (I don't believe hector has to do this?).

**Comment by bpbond** [comment]
Good points @ssmithClimate — thanks. No, Hector doesn't do anything like this; with only a four-box ocean, there's no need.

CESM and E3SM, two prominent earth system models, accelerate (by 10x) terrestrial decomposition during their spinup modes, which lets their land models come to equilibrium much faster. See [Thornton and Rosenbloom 2005](http://dx.doi.org/10.1016/j.ecolmodel.2005.04.008).

**Comment by bpbond** [comment]
Thinking about this week and next week:
* Additional vignette clarifications and changes as you see fit -> PR
* Carbon tracking vignette - we will go over this
* Additional documentation - go through one by one over time, reading for clarity, language, broken links, etc.
* Later (August): write R tests on the tracking capability

**Comment by bpbond** [comment]
" We developed a new feature for this model: the capability to track the flow of carbon from one carbon pool (e.g., atmosphere) to another and report, at the end of a model run, the origin of the carbon within each pool. Our implementation thus records the origin pools of the carbon in every model pool, determined at the start of a run or some user-defined timepoint; if carbon tracking is enabled, this origin record is updated every timestep to reflect the model’s carbon fluxes (pool-to-pool transfers)."

**Comment by bpbond** [comment]
@leeyap as long as you're dealing with documentation, could you fix #446 please?

**Comment by bpbond** [comment]
I think this can be closed. @leeyap please reopen if that's not right.
