### ISSUE TITLE
atmos_c and Ca equal but offset by a year

### ISSUE THREAD

**Issue by dawnlwoodard** [JGCRI/hector#459]
Bug discovered by @NatanelHa (screenshot of results output and code to reproduce are below): atmospheric carbon (atmos_c) and atmospheric CO2 (Ca) outputs in Hector are equal (after unit conversion) but offset by 1 year. So, for example, the year 2000 value of atmos_c matches the year 2001 value of Ca/2.13. atmos_c seems to be the one correctly aligned with the fluxes - since the way the code is set up, the net flux to the atmosphere in year 2100 corresponds to the difference between the atmospheric C in 2100 from 2099. But seems like we should take a look to see which is correct and then make sure that the fluxes are aligned with that one. 

As far as I can tell this is because Ca is set in slowparameval, which happens first and uses the previous year, whereas everything else gets set in stashCValues, which happens after the solver runs and the year is updated to the new year (based on the run method in carbon_cycle_solver.cpp). 

So if everything else is correct and the output is the only issue, we could potentially just change this line "Ca_ts.set(t, Ca);" in record_state in simpleNBox.cpp to "Ca_ts.set(t-1, Ca);" but seems worth thinking through if there are other consequences of how it's currently working and making sure that other things aren't also offset in a way they shouldn't be.

As a side note (should this be a separate issue?), the fluxes don't exactly match the difference in the atmosphere values from year to year. Seems like it would be nice to have these cleanly match up. Is this a solver-related thing? 

Other side node: it doesn't seem intuitive that the ATMOSPHERIC_C variable that is output for users doesn't include methane. I get why it isn't in that variable for the calculations, but from a user-standpoint it seems logical that it would be in an output variable for atmospheric carbon. 

**R code to reproduce issue**

```r
library(tidyverse)
vars <- c(ATMOSPHERIC_C(), ATMOSPHERIC_CO2(), FFI_EMISSIONS(), OCEAN_CFLUX(), LAND_CFLUX())
ini_file = system.file("input/hector_rcp45.ini", package="hector")
core <- hector::newcore(ini_file)
invisible(hector::run(core))
output <- hector::fetchvars(core, 2000:2100, vars=vars)

output %>% pivot_wider(id_cols=c(scenario, year,variable,value), names_from = variable, values_from=value) %>% 
  mutate(atm_flux=rowSums(cbind(ffi_emissions, -atm_ocean_flux, -atm_land_flux)),
         Ca_pgc=Ca*2.13, Ca_pgc_diff=c(NA,diff(Ca_pgc)), atmos_c_diff=c(NA,diff(atmos_c))) %>% 
  select(-c(scenario,ffi_emissions,atm_ocean_flux,atm_land_flux, Ca)) %>% 
  relocate(year,atmos_c,Ca_pgc,atmos_c_diff,Ca_pgc_diff,atm_flux) ->
  atm_output

head(atm_output,10)
tail(atm_output,10)
```
![image](https://user-images.githubusercontent.com/1285408/126236174-01011dbf-694f-4c5d-b048-41541e1e5362.png)

**Comment by bpbond** [comment]
Edited the comment above to tag NH.

**Comment by bpbond** [comment]
>So if everything else is correct and the output is the only issue, we could potentially just change this line "Ca_ts.set(t, Ca);" in record_state in simpleNBox.cpp to "Ca_ts.set(t-1, Ca);" but seems worth thinking through if there are other consequences of how it's currently working and making sure that other things aren't also offset in a way they shouldn't be.

This is right, I think, and after looking through the code and thinking about this, I'm pretty sure that there will be no unintended side effects (famous last words) and that we don't have a comparable situation elsewhere. `Ca` is weird, because it's not an independent variable — merely `atmos_c` expressed in different units. It should never be allowed to deviate from it (and probably should not exist _at all_, but let's shelve that problem for another day).

>As a side note
>Other side note

I've broken these out into separate issues.
