### ISSUE TITLE
Returning tracking data to R

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#469]
Re 
>Ideally the user can use a new function fetchtracking() to get the tracking output data from within R
in #467 -

How would this work? It's a data frame, not a single time series. Right now the tracking visitor is printing all its data to a CSV file; could it instead (or also) be printing to a `stringbuf` that is then returned and run through `read.csv()` in R?

We'd need a new overload of `sendMessage` that returns the buffer I guess?

Thoughts @pralitp @kdorheim @dawnlwoodard ?

**Comment by bpbond** [comment]
https://www.boost.org/doc/libs/1_42_0/libs/iostreams/doc/functions/tee.html

**Comment by kdorheim** [comment]
Hmm I would imagine that we would want similar functionality as fetchvars where we can use something similar to a `_hector_GETDATA` message. My impression is that writing to and reading in csv files is something to be avoided if possible and is a behavior that we don't support right with fetchvars... although @pralitp and @crvernon might be more knowledgable or have a different perspective

**Comment by bpbond** [comment]
Agreed. My current plan is to tee (using Boost functionality above) to a streambuf, which is then returned to R via a getdata, as you say.

**Comment by bpbond** [comment]
Resolved in #477
