### ISSUE TITLE
Manual documentation links not working

### ISSUE THREAD

**Issue by leeyap** [JGCRI/hector#471]
In the [Hector manual](https://jgcri.github.io/hector/articles/manual/), clicking on the following topics gives a 404 page not found error.

[The Hector external API](https://jgcri.github.io/hector/articles/manual/Hector-External-API.html)
[Units for emissions passed into Hector](https://jgcri.github.io/hector/articles/manual/Hector-Units.html)
[Hector message targets](https://jgcri.github.io/hector/articles/manual/Hector-Message-Targets.html)

Also, the Hector R Backend file isn't in the manual folder on Github.

In the [unitvals](https://jgcri.github.io/hector/articles/manual/Unitvals.html) doc, under "when is `unitval` required", neither links work (data passing or output visitors).

**Comment by kdorheim** [comment]
In the main read me & the pkgdown manual we refer to the old contribution guide, we might want to delete that one & consistently refer to https://jgcri.github.io/hector/articles/manual/ContributionsGuide.html.

**Comment by leeyap** [comment]
Just now realizing that in the manual, there are no links under the Science section to "a general summary of the science behind Hector" or "the model's ocean." 

Related to this, would it be worthwhile to add a section explaining the different types of climate models? (Could include examples of other models as discussed in #331) @bpbond 

Also, "Hector in the wider world" doesn't actually show up in the manual.

**Comment by bpbond** [comment]
Different types of climate models—as long as this was kept concise, yes, seems like a useful addition to me.

**Comment by bpbond** [comment]
Not sure I'm completely understanding—the "general summary" doesn't exist yet, right? This may be easier to touch base about in person.

But anyway yes, I think that makes sense.

**Comment by kdorheim** [comment]
Will be addressed in #589
