### ISSUE TITLE
Manual documentation has unfinished "To Dos" 

### ISSUE THREAD

**Issue by leeyap** [JGCRI/hector#472]
Several documents in the manual have sections labeled with "to do"

In [adding a new component](https://jgcri.github.io/hector/articles/manual/AddNewComponent.html):
- In X::run, TODO: describe
- In X::run, TODO: mention spinup flag return
- In X::shutDown, TODO: describe

(Also note that section four is not appearing online)

In [version numbering](https://jgcri.github.io/hector/articles/manual/VersionNumbers.html):
- There's a crossed out line at the top: The version number and the Git build number appear in all output and log files.[not yet]
- Not sure if there need to be any updates added here

In [unit values](https://jgcri.github.io/hector/articles/manual/Unitvals.html):
- The section "When is unitval optional?" is basically blank and marked with TODO

In [Hector component API](https://jgcri.github.io/hector/articles/manual/ComponentAPI.html):
- There's not much written on this page at all

**Comment by bpbond** [comment]
Updated and resolved in 4bf1728.
