### ISSUE TITLE
Final cleanup before v3 merge (running list)

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#476]
- [x] Clean up GitHub Actions yaml files to remove development branch settings
- [x] Ensure all v3 milestone issues are linked, addressed, or reassigned to a new milestone
- [x] Search and resolve any `KRD-UPDATE` and `BBL-TODO` strings
- [x] Remove the Hector wiki as it is out dated & being replaced with the pkgdown documentation 
- [x] Reformat entire C++ code base to a common style (cf. outdated #418 )
- [x] Assertion of copyright (see Chris's email and google doc)
- [x] Authorship reworking
- [x] Update old Hartin graph on repository main page (and make auto-generated?)
- [x] Prune unneeded branches

Final Steps 
- [x] Once more through `clang-format`
- [x] Make release
- [x] doi on zenodo 
- [x] update NEWS
- [x] Update R package version number and any version numbers in C++
- [x] Inform rgieske and the pyhector folks when we have stable v3 beta

**Comment by kdorheim** [comment]
@bpbond when you are referring to the GitHub Actions yaml files to remove the development branch settings are you talking about the `github_actions` branch listed in a few of the yaml files?

**Comment by bpbond** [comment]
Right

**Comment by bpbond** [comment]
Perhaps obvious, but I'm putting those in because do want testing on PRs against some of the dev branches, but don't want those as permanent settings.

**Comment by kdorheim** [comment]
true!

**Comment by kdorheim** [comment]
Do we need to do an alpha release before the final v3 release?

**Comment by bpbond** [comment]
Not necessarily I don't think.
