### ISSUE TITLE
Leeya August work - vignette and tests

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#480]
Supersedes #454 

Hello @leeyap -

What do you think, with the documentation review behind us, about tackling 
>Carbon tracking vignette - we will go over this

?

This would involve working with the branch currently open as #477 , and making a new vignette that walks the user through
* Turning on carbon tracking for a run
* Running the core
* Retrieving the tracking data
* Graphing it

cc FYI @natanelha

**Comment by leeyap** [comment]
Yes, sounds good @bpbond. When should I get a draft to you by? I can also share with @NatanelHa if that would be helpful.

**Comment by bpbond** [comment]
Ok great! Timing is flexible but sometime next week? And yes I'd suggest please get Nathaniel's feedback at some stage.

**Comment by leeyap** [comment]
@bpbond, could you post the code that you used to generate the time series graphs of the changing sources and any other important lines to go in the vignette? Thanks!

**Comment by bpbond** [comment]
I don't have the code, but it's basically just
```r
ggplot(x, aes(year, fraction, fill = source)) + geom_area() + facet_wrap(~component)
```
Typing this without looking at data, errors are almost certainly guaranteed :)

**Comment by bpbond** [comment]
Hello @leeyap !

The `covr` package allows us to understand what code is _not_ covered by tests — that is, it will run our testing code and log all the normal package code that gets exercised and tell us what never is run. We'd like to know what parts of the code are not covered by tests and, if possible, write new tests for those pieces.

- [ ] Install the `covr` package, read its documentation, and produce a coverage table: ideally by file and function.
- [ ] Then, let's take a look at the least-covered code and design tests for them
- [ ] Write tests!

**Comment by bpbond** [comment]
Some thoughts for our discussion today @leeyap @kdorheim :


Continued improvements and maintenance
* write a vignette for how to get GMST vs GMAT
* calibration—start to gather the CMIP6 data we will need for that?
* okay it also look like the HL & LL temps used in Hector used to convert to ocean was calculated by CH update with CMIP6 values?

Deeper programming
* address some more-complicated outstanding issues
* start to learn the C++ code
* issue of initial starting values & hard coded parameter values Dawn brought up look into that?

Applications
* start setup work (code + research) for Hector v3 paper KD will lead
* pick up Natanel's work and move it down the road — expanding analysis, doing background research, etc. — for negative emissions paper probably led by DW

Other
* contribute to mentoring high school student

**Comment by bpbond** [comment]
Leeya to set up meeting with Natanel to discuss his work—data, code, etc., so we have good knowledge transfer as his internship ends.

What would be involved with GMAT vs. GMST? See #360 . Take the ocean surface temperature, and land surface temperature, weighted-average them together.

**Comment by bpbond** [comment]
Consider for the future: CMIP6 data processing, perhaps with Python package, taking advantage of @leeyap 's experience with that language.

**Comment by bpbond** [comment]
@leeyap When you talk with Natanel, please take a look at his code for calculating airborne fraction. Consider—should we add that as an example at the end of the tracking vignette?

**Comment by leeyap** [comment]
@bpbond 
That could be interesting - the airborne fraction code shows how much carbon moved from the earth_c pool to atmos_c, right? So would the example be to use tracking data to calculate this (and potentially other) fractions? 

If it's okay with @NatanelHa, I can use his code, modified slightly, in the vignette. Natanel compared the airborne fraction calculation from Hector to other models/scenarios (?) - would we want to include this graph or create something different? (Pie chart? Bar graph? - thoughts?)

**Comment by NatanelHa** [comment]
Hi @leeyap, 

Feel free to use my code! Just to clarify, the values I used for comparison were all from a paper written about the airborne fraction. I think the paper itself also has good background and explanation of what exactly the airborne fraction is too. 

Here is the paper: 
Knorr 2009 - http://dx.doi.org/10.1029/2009GL040613  

And as always feel free to reach to reach out if you have any questions about my code!

- Natanel

**Comment by bpbond** [comment]
That'd be a great place for the graph and thanks @leeyap for taking this one, and thanks @NatanelHa for the code! And yes, I would include the Knorr values.

**Comment by leeyap** [comment]
@bpbond sounds good - I'll get you a draft hopefully by today or Monday.

@NatanelHa - thanks for the info and the code, appreciate it!

**Comment by bpbond** [comment]
It's the last day of August and time to close this!
