### ISSUE TITLE
Dynamic cast usage

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#483]
As mentioned in #477 the core rifles through the visitor list to the csvfluxpool one, using `dynamic_cast` to check for a non-null pointer. This is tacky and should probably be reimplemented using virtual functions in the `aVisitor` class.

**Comment by bpbond** [comment]
Hey @pralitp would you be willing to take this on? I feel like you can do something much more elegant than I'm going to come up...can provide more detail if yes.

**Comment by pralitp** [comment]
Sure, I'll take a look during the next hackathon?

**Comment by bpbond** [comment]
Why why why did this not close 😢
