### ISSUE TITLE
Changing the tracking date via R

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#484]
OK, how do we handle tracking date changes in R?

Possibilities include:
* INI file only
* a dedicated `set_tracking_date()` function
* as a parameter to both the R `run()` and C++ `core::run()` - this would follow the `runtodate` logic
* as a parameter to the R `run()`, which then uses `setData()`
* via `setvar()`

If you have time, next week I would like to talk this through with you @kdorheim .

**Comment by kdorheim** [comment]
👍 want to put something on our calendars?
