### ISSUE TITLE
Atmospheric CO2 values after spinup too high

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#49]

**Comment by bpbond** [comment]
@cahartin can this be closed?

**Comment by cahartin** [comment]
no. this is something we can move to a different milestone.

**Comment by bpbond** [comment]
Checking - can this be closed @cahartin ?

**Comment by cahartin** [comment]
i don't think this issue has been solved. Let me take a look this week.

**Comment by bpbond** [comment]
@cahartin can this be closed? Feeling like a bot that keeps asking this question :)

**Comment by cahartin** [comment]
i haven't looked at it in over a year.  I guess it doesn't hurt leaving it in limbo.

**Comment by bpbond** [comment]
Out of date, closing.
