### ISSUE TITLE
Hector version and build numbers should appear in all logs and outputs

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#50]
Presumably this means that we'll have a file `VERSION.TXT`, the contents of which the preprocessor will insert (for macro VERSION) into source files before building. Another macro GITBUILD would insert the latest commit number.

See e.g. http://stackoverflow.com/questions/6526451/how-to-include-git-commit-number-into-a-c-executable

**Comment by bpbond** [comment]
Good suggestion from @rplzzz : let's include a harcoded version for now, that appears at head of all logs and outputs, pulling from a `version.hpp`. Later, we'll make this more dynamic, and include Git build hash too.

**Comment by pralitp** [comment]
With regards including the version in the output: what do we want that to look like?  Do we want to assume some format for a header line?  Do we want to include it in every row of output?

**Comment by cahartin** [comment]
I am leaning towards a header row with that information.

**Comment by bpbond** [comment]
I agree–a single header line in the log (and every visitor output, ideally). E.g.:

```
Thu Feb  5 12:21:03 2015:DEBUG: Hector version 1.0
Thu Feb  5 12:21:03 2015:DEBUG:init: hello bc
Thu Feb  5 12:24:15 2015:DEBUG:setData: Setting BC_emissions[1765]=0
```

**Comment by pralitp** [comment]
Ok so should I add a header line to the csv output with
# Output from MODEL_NAME version MODEL_VERSION

However is this going to break any R scripts?  Doing a quick look it doesn't look like it is expecting any comment.char

**Comment by bpbond** [comment]
Yes, it's definitely going to break scripts. But we can fix this, and I think it's worth it to have a header line.

Let's say the logs will look like my previous post above; and the CSV outputs will begin with a line like

```
# Output from Hector version 1.0
```

since we're already using # as our comment char in the inputs?

**Comment by pralitp** [comment]
Sounds good.  I updated op_parser.R as well to set the comment.char="#"

**Comment by bpbond** [comment]
Thanks, Pralit.

**Comment by bpbond** [comment]
Whoops, I just realized the INI comment character is `;` while now in outputs it's `#`. We should standardize? Any preference @cahartin @rplzzz @pralitp ?

**Comment by pralitp** [comment]
I think `#` is more common and it is already used in the comparison data so I am leaning towards that.

**Comment by bpbond** [comment]
Yes, agreed, plus it's used in the R scripts as well. I'll commit the change if no objections.
