### ISSUE TITLE
fluxpool bug

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#501]
I think this is possible:

* Create a fluxpool `x` with tracking turned on
* Use `x.set` to a different value, same units, same tracking, different name
* End up with a fluxpool with two entries in its map, each 1

**Comment by kdorheim** [comment]
@bpbond Is this still a bug?

**Comment by bpbond** [comment]
I don't know. You can assign me if you want and I'll investigate.

**Comment by bpbond** [comment]
I checked, and this is not the case. Closing.
