### ISSUE TITLE
Tracking test code - check for valid pool names

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#503]
This is apropos of #499 

* Take the first (?) year of the tracking data (from `get_tracking_data()`). Call `fetchvars` for each unique `pool_name` ( using the `pool_units` in the call) and confirm (1) no error and (2) the value returned is the same as that recorded in the tracking data

For example the year 1800 values in my test rcp4.5 run start with
```
year,component,pool_name,pool_value,pool_units,source_name,source_fraction
1800,ocean,HL,140.536,Pg C,intermediate,0.167479
1800,ocean,HL,140.536,Pg C,HL,0.58578
1800,ocean,HL,140.536,Pg C,LL,0.242564
1800,ocean,HL,140.536,Pg C,atmos_c,0.00417741
1800,ocean,LL,783.724,Pg C,intermediate,0.08123
1800,ocean,LL,783.724,Pg C,LL,0.91877
1800,ocean,LL,783.724,Pg C,atmos_c,0
1800,ocean,intermediate,8418.92,Pg C,LL,0.00116229
1800,ocean,intermediate,8418.92,Pg C,deep,0.0302988
1800,ocean,intermediate,8418.92,Pg C,intermediate,0.968539
1800,ocean,intermediate,8418.92,Pg C,atmos_c,0
1800,ocean,deep,25991.7,Pg C,intermediate,0.00624645
1800,ocean,deep,25991.7,Pg C,HL,0.00378503
1800,ocean,deep,25991.7,Pg C,deep,0.989969
1800,ocean,deep,25991.7,Pg C,atmos_c,0
1800,simpleNbox,atmos_c,591.604,Pg C,atmos_c,0.914645
```
If we `fetchvars` "HL" for 1800, we should get back 140.536, atmos_c for that year should be 591.604, etc.

**Comment by bpbond** [comment]
Also

* The `source_name` entries should all be present in the `pool_name` column

**Comment by leeyap** [comment]
Hi @bpbond - I had a couple of questions

1. What is the function call for the earth_c biome? I was able to find all the others.
2. When I run the core with tracking, the soil, detritus, and veg pools still show up as _global. I restarted my session and am up to date with the origin, so not sure why that's happening?
3. So far, it looks like the values I get from the tracking data and the values from fetchvars are not identical. They're off by anywhere from 1e-5 to 1e-7. Is that a problem? I would think that they _should_ be identical but maybe that low of an error threshold is okay.

**Comment by bpbond** [comment]
Good morning @leeyap 

1. Uh I do not know. There might not be done! In which case we could add it—feel free to look at how this happens in the code, e.g. for `ATMOSPHERIC_C()`, and try to duplicate, or we could walk through it together. Basically there needs to be some R code to provide the proper variable name back to the user.
2. Have you merged in latest changes to `land-tracking`? That's where I merged the PR into.
3. What do you mean "one decimal place"? Like 3.1 versus 3.2? Or 3.10001 versus 3.10002?

**Comment by leeyap** [comment]
Hi @bpbond,

1. Is that the code is the aadoc.R file?
2. I'm working in `land-tracking` which is why I was confused?
3. It varied - one difference was 1e-2, one 1e-4, a couple 1e-5. But consistently, the call from `fetchvars` had the extra decimal place.

**Comment by bpbond** [comment]
Hmm re 1, I think so? @kdorheim has a step by step guide to exposing Hector variables in the R package that may be useful too.

Re 2, 🤷 Probably easiest to look at this together I think

Re 3, that makes sense: `fetchvars` brings variables back in-memory, while the `get_tracking_data` mechanism is through a file (effectively). So the latter loses precision.

I will have time to talk later today, if useful.

**Comment by leeyap** [comment]
@bpbond I think talking later might be helpful. I have time today until a meeting at three if that works - feel free to plug something into the calendar. Thanks!

**Comment by bpbond** [comment]
Done in #498
