### ISSUE TITLE
Remaining unclear ocean component parameters & functions 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#507]
Related to #506 & #505 

* surfaceLL.mychemistry.U  = 6.7; wind speed
* ~In convertToDIC function there is a hardcoded constant of 1027.0 is this the density of seawater? Where did it come from?~
* the function "brief calculate Omega of Ca/Ar" -- unclear where this function came from...

**Comment by kdorheim** [comment]
@cahartin do you know the source of the average wind speed? of any of the above unknown ocean information?

**Comment by cahartin** [comment]
- Wind speed HL and LL 6.7 m s−1 Takahashi et al. (2009), Liss and Merlivat (1986)
- 1027.0 is the average density of seawater - technically, density will be slightly different for the boxes and will change based on temperature change. 
- Omega Ca/Ar is calculated from equation 1.1.25 in Zeebe, R. E. and Wolf-Gladrow, D.: CO2 in Seawater: Equilibrium, Kinetics, Isotopes, Elsevier, Amsterdam, 2001.
