### ISSUE TITLE
Leeya - September

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#514]
1. Finish up #504 

2. Explore [Pangeo](https://pangeo.io/about.html) - we'd like to know about its strengths, weaknesses, what is doable and what's not, esp wrt Pangeo in the cloud. Thinking particularly about using this for CMIP6 processing (though not only that). It would be great to have someone — you! — who is really familiar with it, both in theory and hands-on.

**Comment by bpbond** [comment]
Hi @leeyap -

One that will be increasingly useful is a quick way to document how the v3 model ( #448 branch ) differs from `master`. Specifically, we'd like to save a copy of the `master` outputs and then be able to quickly generate plots comparing the current #448 outputs with the stored v2.5 ones for key variables.

Key variables might include atmospheric CO2, global temperature, and total radiative forcing.

How to store the v2.5 outputs? One way would be to commit command-line output files, e.g. outputstream_rcp45.csv and the like. The other would be to run Hector for each RCP, collect the key variables' outputs, and save that data frame as a csv or `Rdata` file.

Does this make sense?

**Comment by leeyap** [comment]
@bpbond I think so. So a procedure might look like this:

1. Identify key variables
         a. Atmospheric CO2, global temperature, radiative forcing - anything else? 
2. Run Hector for four RCPs
3. Collect outputs (values of key variables at the end of a run? values across a time series?), store data frame as .csv file
4. Graph outputs?

**Comment by bpbond** [comment]
Well, that's the procedure for part 1 (running the v2.5 Hector). We'll want a separate piece of code that runs the v3 model, loads the 2.5 data, and makes basic comparison plots.

Your code should be flexible in terms of key variables—that's a good list to start with, but we may want to easily add others later.

So, I would suggest with the first part you outline above, and we can check/review, and then proceed to second part?

**Comment by leeyap** [comment]
@bpbond Okay, I'll start working on it. 

Should I branch from master?

**Comment by bpbond** [comment]
Thanks. I think probably switch to master, do the initial run for the comparison data, save those data outside of the repository, and then branch from V3?￼

**Comment by bpbond** [comment]
Meeting 2021-09-14

* @leeyap to do some research — how does the codecov bot comment in a PR? It would be completely cool if we could do this for model outputs
* We'll talk September 28th about some longer-range things — LP to think about what interests her and what doesn't
* Continue with Pangeo but remember goal is to assess it, not master it (yet)
* We will go over specific code example of computing on CMIP data later this week or early next week

**Comment by leeyap** [comment]
To do for "Leeyabot"

- [ ] Create local script with access token to post a comment
- [ ] Create a Github action with access token to post a comment (look at Github Secrets)
- [ ] Create a Github action with access token to run comparison script

To do for Pangeo

- [ ] Continue working through relevant examples
- [ ] Write short write-up on notes, pros/cons, and conclusion on use of Pangeo

**Comment by bpbond** [comment]
Thanks @leeyap . I edited slightly.

**Comment by leeyap** [comment]
Closing - it's October

**Comment by bpbond** [comment]
🎃
