### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#52]
In particular, 

- building and running the model on all platforms
- a demo showing how to use backend R scripts

This has been (rightly) requested by the GMD reviewers.

**Comment by bpbond** [comment]
I have added documentation on installing under Mac OS X to https://github.com/JGCRI/hector/wiki/BuildHector.

**Comment by bpbond** [comment]
@rplzzz to check Linux instructions; we will add VS project files; and say Windows documentation TBA.

**Comment by rplzzz** [comment]
I have tweaked the Linux instructions a bit to make them clearer, and I have updated the makefile and the user guide to be consistent with what we are saying in the build instructions on the wiki.

One question/suggestion:  we mention the Google Test framework in several places, but we don't provide any instructions on how to use it (mostly we just say "TODO"), and it's not clear that it's even usable without a lot of work bringing the test code up to date.  Should we just delete the references to Google Test until we are ready to provide actual instructions on how to use it?

**Comment by rplzzz** [comment]
Also, I'm going to pass this issue back to @bpbond for review.

**Comment by bpbond** [comment]
Looks good @rplzzz , thanks. I'm assigning this over to @cahartin since the only remaining hole is the Windows build instructions.

**Comment by bpbond** [comment]
We're in good shape, so I'm taking this off the 1.0 milestone. More does need to be done at some point: Windows build instructions; input file details; using the R backend; etc.

**Comment by rplzzz** [comment]
Superseded by #104.
