### ISSUE TITLE
Ocean initial values in INI file not honored

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#530]
@kdorheim notes:

Reading in the ocean's initial values via the ini files does not work; they are written over by some internally hard coded numbers.

**Comment by bpbond** [comment]
This doesn't seem to be right, at least not anymore; the model respects the `TT`, `TU`, `TWI`, and `TID` parameters:
```r
library(hector)
hc <- newcore("inst/input/hector_ssp245.ini")
run(hc)
old <- fetchvars(hc, 1750:2300)
oldval <- fetchvars(hc, NA, TT())$value

setvar(hc, NA, TT(), oldval * 1.1, "m3/s")

reset(hc)
run(hc)
new <- fetchvars(hc, 1750:2300)
shutdown(hc)

old$which <- "old"
new$which <- "new"
library(ggplot2)
ggplot(rbind(old, new), aes(year, value, color = which)) + geom_line() + facet_wrap(~variable, scales="free")
```
![diff](https://user-images.githubusercontent.com/1956468/205918343-959b6710-4840-45eb-bde0-660771a7d377.png)

I checked and this works via the INI file as well.

**Comment by bpbond** [comment]
@leeyap These four parameters (above) are what Reviewer 3 is asking about. So I think we're all set to go; no model development needed 🎉

**Comment by leeyap** [comment]
@bpbond Amazing! Thanks!

**Comment by kdorheim** [comment]
this issue is related to the initial ocean carbon pool size

**Comment by bpbond** [comment]
Oh, sorry!

**Comment by kdorheim** [comment]
see 

```
  // Define the size of the preindustrial ocean surface and intermediate-deep
  // ocean carbon pools from IPCC AR6 Figure 5.12.
  const double preind_C_surface = 900; // (Pg C) IPCC AR6 Figure 5.12
  const double preind_C_ID = 37100;    // (Pg C) IPCC AR6 Figure 5.12
```
 from the ocean component cpp file
