### ISSUE TITLE
NPP not affected by changes to vegetation

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#531]
Right now, we scale preindustrial NPP only by CO2 fertilization.

This means that if we deforest and pave 10% of the planet, via the LUC input...nothing changes for NPP. That's not great.

Also, while GCAM's LUC data is "the whole cycle" — I mean, it includes ALL the effects of LUC, from the initial loss (uptake) to slower decay (growth) — most users I think will assume our LUC means the initial pulse only. Right? I.e., how it might be handled into an ESM.

So that's a definitional problem here, and it's really not great that NPP is unaffected by the amount of vegetation biomass on the land surface.

Perhaps see also #53

**Comment by ssmithClimate** [comment]
One question would be how much does NPP change if one converts forest to grassland or cropland? NPP could even go up! (Although if cropland is tilled, soil carbon would go down of course.)

**Comment by bpbond** [comment]
Yes, thanks, good point. The scenario I was discussing with @realxinzhao was if we deforested half the world and paved it; Hector would definitely not handle that correctly.

Basically: LUC is a transfer but won't affect NPP (or permanently transfer carbon). In some cases that's okay, and it's okay for GCAM because GCAM is computing the integrated LUC over time (including regrowth, etc).

**Comment by bpbond** [comment]
Documenting:

One other thing I did was to [branch an experimental version of Hector](https://github.com/JGCRI/hector/tree/newluc) that treats de/afforestation as permanently affecting plant production—i.e., LUC fluxes permanently change NPP. If we assume that the “pavement factor” equals 1, i.e. anything we deforest is paved over and taken out of future NPP, the results are big for e.g. RCP4.5 (red line shows default Hector behavior). The graph also shows a line for pavement=0.5, i.e. deforesting X PgC means a X * 0.5 NPP loss going forward; the interpretation of this would be 50% of the lost NPP is compensated for by the croplands (or whatever) that take the original vegetation’s place.
 

![luc45](https://user-images.githubusercontent.com/1956468/141677707-7e53459f-924e-44bf-bb7e-7407c18c166c.png)

The same dynamic would work in reverse in an afforestation scenario, meaning that Bryan’s currently correct comment “afforestation is useless in a cumulative sense” would no longer apply.
 
*But* (and this is a large caveat) with this new behavior, the LUC flux from GCAM would no longer make sense—or rather, no longer be consistent with Hector’s expectations. In particular, I think right now it includes soil gains and losses over time as a consequence of LUC, but Hector is expecting vegetation only (because it’s used as a scalar for NPP in the future).
