### ISSUE TITLE
Possible leeyabot behavior change

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#533]
Currently [leeyabot](https://github.com/JGCRI/hector/pull/527) always prints a message, the summary table, and the graph. But when all the R2 values are 1 and all the NRMSE values are 0, i.e. the model behavior hasn't changed, is there any point? 

Maybe in that circumstance the bot should just say "The current pull request's outputs do not differ from master" and stop. 🤷

**Comment by leeyap** [comment]
Should have been closed by #534
