### ISSUE TITLE
Fair use document

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#54]
In addition to a license (see issue #28 ) we probably want a "fair use" document, akin to what (I think) CESM has.

**Comment by bpbond** [comment]
Allison noted you shouldn't be able to use "Hector" name if you change/fork it...

**Comment by rplzzz** [comment]
Several of the commonly-used open source licenses contain a provision along these lines.

**Comment by bpbond** [comment]
Thanks. We figured, but wanted to make sure it was on the check-off list.

**Comment by bpbond** [comment]
Combining this with issue #28
