### ISSUE TITLE
How to install Hector from R

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#540]
The [basic vignette](http://jgcri.github.io/hector/articles/intro-to-hector.html) doesn't talk about this. 😕  Do we describe somewhere else how to use `remotes::install_github()` to actually install the model?

**Comment by kdorheim** [comment]
In the manual there are instructions on how to install R hector see https://jgcri.github.io/hector/articles/manual/BuildHector.html

however it uses the devtools::intall_github command instead of the remotes::install_github

**Comment by bpbond** [comment]
Ah thank you!

**Comment by kdorheim** [comment]
^^ But not necessarily clear, it may be wise to re-organize the manual and vignettes, perhaps labeling the vignettes as examples or something

**Comment by bpbond** [comment]
@leeyap At your leisure, could you
* Update the documentation page Kalyn links to above to reference `remotes::install_github()` instead of `devtools`
* Update the introduction to Hector vignette (link above) with a sentence providing a link to the how-to-install hector page

These changes can be done on either `master` or the v3 branch. Thank you!
