### ISSUE TITLE
If cores auto-reset they should notify user?

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#546]
When you run a core; change a parameter; and re-run (without resetting) it seems like the core auto-resets because it's dirty? I think so? But in that case it really should print a `message` telling the user it's done so.

**Comment by bpbond** [comment]
@leeyap This is a straightforward change that might be great for you to sharpen your skills working with R package code. Any interest?

Note - change should include test code verifying a message is generated.

**Comment by leeyap** [comment]
@bpbond 
For test code, would that go under `test_hector.R`?
What file would I have to edit to get the core to print a message?

**Comment by leeyap** [comment]
Okay, update:

From `rcpp_hector.cpp`:
```
Environment run(Environment core, double runtodate = -1.0)
{
    if(!core["clean"]) {
        std::cout << "NOTE: resetting core\n";
        reset(core, core["reset_date"]);
    }
```

I think that the `std::cout` line is not doing what I think it's doing. When I try to run the following in `test_wrapper.R`:

```
  hc <- newcore(file.path(inputdir, "hector_rcp45.ini"), suppresslogging = TRUE)
  run(hc, 2100)

  setvar(hc, 2050:2150, FFI_EMISSIONS(), 0.0, "Pg C/yr")
  expect_false(hc$clean)
  expect_output(!hc$clean), "NOTE: resetting core")
  expect_equal(hc$reset_date, 2049)
  expect_error(run(hc, 2048), "is prior")
```

The `expect_output` test fails because there is no output generated. Without using test code, I tried to trigger an auto-reset and also didn't get any output (I made sure to rebuild).

Thoughts? @bpbond

**Comment by bpbond** [comment]
Hmm, odd, I thought we tried this and DID see output.

...oh wait, you haven't tried to `run` the core! That's when the reset message should get triggered.

**Comment by leeyap** [comment]
Ah, okay. I tried this (just in console):
```
>   setvar(hc, 2050:2150, FFI_EMISSIONS(), 0.0, "Pg C/yr")
> hc$clean
[1] FALSE
```
And then ran the core without getting the output message.

**Comment by bpbond** [comment]
Documenting...

It looks like `std::cout` works on Mac (where we tested this a few weeks ago) but not on Windows. We ended up using `Rcout` instead as documented [here](https://teuder.github.io/rcpp4everyone_en/060_printing_massages.html).

**Comment by leeyap** [comment]
Debugging, then working to create a function in R that:
1. Checks if core is dirty
2. If yes, prints a warning
3. Then, passes control to C++

**Comment by leeyap** [comment]
Updates:
- Changed `rcpp_hector` to auto re-set the core if it is dirty prior to a new run, and return output alerting the user
- Updated `test_wrapper` accordingly to check for the output

Problems:
- We're considering adding an R function `run()` that (as mentioned above) would check for a dirty core, print a warning, and pass to C++. We'd (I'd) have to go into all tests that would be affected by the change to a warning. 
- The other thing is the test behavior itself. When the core auto-resets, the `tracking_date()` does not go back to zero, necessarily. 
- Do we even want to have an auto-reset, or just a warning that the user needs to manually reset the core? 

@kdorheim what do you think is the best way to go forward? 
@bpbond feel free to add anything I missed

**Comment by bpbond** [comment]
Thanks @leeyap . There are definitely some oddities here!

**Comment by kdorheim** [comment]
> We're considering adding an R function run() that (as mentioned above) would check for a dirty core, print a warning, and pass to C++. We'd (I'd) have to go into all tests that would be affected by the change to a warning.

^^ would this modify or replace the current R `hector::run` function? I don't think that we want two functions named run, that might cause some chaos

**Comment by bpbond** [comment]
Our idea is that there would be a `run()` in R, called by users, and it would pass control to `run_impl()` in C++ (like `newcore()` passes control to `newcore_impl()`).

**Comment by bpbond** [comment]
To be clear, the purpose of adding a `run()` in R would be the ability to issue an R warning on auto-reset. Can't do that from C++.

...hahah @pralitp to the rescue! 🙏

**Comment by kdorheim** [comment]
Still slightly confused, there is an R `hector::run()` [see here](https://github.com/JGCRI/hector/blob/a75702ba5a3ab9684a4eae1e49ef221172b6a494/R/RcppExports.R#L1132) already so are you modifying this existing function? Or completely replacing it?
