### ISSUE TITLE
Variable names in R

### ISSUE THREAD

**Issue by leeyap** [JGCRI/hector#547]
There doesn't seem to be a clear way to figure out what a Hector variable is in R (that I know of). Both in terms of science, but also in terms of communicating between R and the core (e.g. can call `BETA()` to get `"beta"` but not the other way around.

We could potentially create a "dictionary" in the manual of variable names and brief description/how to access them.

**Comment by bpbond** [comment]
Maybe linked with #362

**Comment by bpbond** [comment]
@kdorheim Does the existence of `data/inputstable.rda` mean that this can be closed?

**Comment by kdorheim** [comment]
hmm I think the inputstable.rda is missing the function name element of what Leeya was seeking but we sort of have that already with the output table article...

**Comment by kdorheim** [comment]
Added in #656
