### ISSUE TITLE
atm_land_flux doesn't seem to be defined for 1745

### ISSUE THREAD

**Issue by dawnlwoodard** [JGCRI/hector#556]
**Description**
When trying to get NBP data out from the R interface (using the latest land_tracking branch), I get an error if I use the dates 1745:2100 but 1746:2100 works fine. Other variables seem to have 1745 (tried veg_c and atm_ocean_flux). Haven't dug into code yet to see what might be causing this.

Here's the error I get: 
Error in sendmessage(core, GETDATA(), v, dates, NA, "") : 
sendmessage: msg: Interpolation requested but not allowed (?) date: 1745

func: get
file: tseries.hpp
ffile:	../inst/include/tseries.hpp

line: 339

**To Reproduce**
Running hector through the R interface with the following code should reproduce:

`library(hector)

scenario_file <- paste0("input/hector_ssp245.ini")
ini_file <- system.file(scenario_file, package="hector")
core <- newcore(ini_file)
run(core)
results <- fetchvars(core, 1745:2100, c("atm_land_flux"), scenario="ssp245")

results <- fetchvars(core, 1746:2100, c("atm_land_flux"), scenario="ssp245")  # this works fine
results <- fetchvars(core, 1745:2100, c("veg_c"), scenario="ssp245")  # this works fine
results <- fetchvars(core, 1745:2100, c("atm_ocean_flux"), scenario="ssp245")  # this works fine
`

**Comment by kdorheim** [comment]
Is this related to issue #354?

**Comment by dawnlwoodard** [comment]
> Is this related to issue #354?

Ah, yes, that would be the explanation. Thanks, @kdorheim!

**Comment by bpbond** [comment]
It sounds like this can be closed then? Please reopen if I'm misunderstanding.
