### ISSUE TITLE
fetchvars is returning NA for all years

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#568]
**Describe the bug**
`hector::fetchvars()` is returning `NA` for all years.

**To Reproduce**
```
> ssp <- system.file("input/hector_ssp245.ini", package = "hector")
> hc <- newcore(ssp)
> run(hc)
Hector core:	Unnamed Hector core
Start date:	1745
End date:	2300
Current date:	2300
Input file:	/Library/Frameworks/R.framework/Versions/4.1/Resources/library/hector/input/hector_ssp245.ini
> out <- fetchvars(hc, dates = NA)
> head(out)
             scenario year variable      value    units
1 Unnamed Hector core   NA       Ca 521.829709 ppmv CO2
2 Unnamed Hector core   NA     Ftot   4.113112     W/m2
3 Unnamed Hector core   NA     FCO2   3.570265     W/m2
4 Unnamed Hector core   NA     Tgav   2.899551     degC
> all(is.na(out$year))
[1] TRUE
```
**Expected behavior**
Not that! 😄

**Comment by bpbond** [comment]
This is for the `land_tracking` branch.

**Comment by bpbond** [comment]
@kdorheim When you get a chance, could you check on your system please?

**Comment by kdorheim** [comment]
This might be the expected behavior, the fetchvars is an R wrapper for the cpp `getData` function. `getData` works with specific dates. It is also set up so that when the date is undefined (aka NA) the Hector core returns constant values or if it is a temporal variable it returns the value from the most recent time step. See here in the example you provided 

```
> ssp <- here::here("inst", "input", "hector_ssp245.ini")
> hc <- newcore(ssp)
> run(hc)
Hector core:	Unnamed Hector core
Start date:	1745
End date:	2300
Current date:	2300
Input file:	/Users/dorh012/Documents/Hector-Versions/R/hector/inst/input/hector_ssp245.ini
> out1 <- fetchvars(hc, dates = NA)
> out2 <- fetchvars(hc, dates = 2300)
> out1
             scenario year variable      value    units
1 Unnamed Hector core   NA       Ca 518.324498 ppmv CO2
2 Unnamed Hector core   NA     Ftot   4.073620     W/m2
3 Unnamed Hector core   NA     FCO2   3.530685     W/m2
4 Unnamed Hector core   NA     Tgav   2.882537     degC
> out2
             scenario year variable      value    units
1 Unnamed Hector core 2300       Ca 518.324498 ppmv CO2
2 Unnamed Hector core 2300     Ftot   4.073620     W/m2
3 Unnamed Hector core 2300     FCO2   3.530685     W/m2
4 Unnamed Hector core 2300     Tgav   2.882537     degC
```

If we really want to prevent this behavior an option would be to create an additional R function that fetches the parameters and enforce fetchvars function can't read in a NAs for the dates (not quite sure how to enforce that with the R to cpp code & would probably need to make changes to the setvars functionality as well) but that seems better than the alternative of changing the `getData` behavior.

**Comment by kdorheim** [comment]
My first instinct was 
1. leave it alone? 
2. leave it to be a hector v>3.0 change, but when I think about that it would actually change any code that uses setvars & getvars (any analysis code & hector UI code) so if it is something we would like to change it would probably need to be associated with major version release such as v3 or v4

**Comment by bpbond** [comment]
Thanks! At the very least we need to change the `fetchvars` documentation, which says:

>dates | Vector of dates to fetch; this will be automatically trimmed to dates that are between the start date and the latest date currently run. **Set to NA to return all dates.**

**Comment by bpbond** [comment]
This is a test improvement opportunity, too.

**Comment by kdorheim** [comment]
> Set to NA to return all dates

this is not actually true, it will return the values for the variables associated with the core's current date. 

Also variables that are constant or would be better classified as parameters such as ECS, BETA, Q10 would have a date values of NA

**Comment by bpbond** [comment]
So I'll just tweak the documentation, removing that last sentence?

**Comment by kdorheim** [comment]
👍
