### ISSUE TITLE
Memory leak / other memory issues

### ISSUE THREAD

**Issue by pralitp** [JGCRI/hector#582]
**Describe the bug**
When running a memory profiler on GCAM (still using hector 2.5.0) a came across a few issues in Hector.  At least one of which I can verify is still valid (apologies for the screen shots!  There was more information in them than if I tried to just get the errors from logs):

<img width="481" alt="core_ozone" src="https://user-images.githubusercontent.com/7440455/158454053-520d0287-732c-443a-b6fb-16c1eae2c72f.png">

There is a memory leak in `Core::init` because `OzoneComponent` is listed twice.  Although the pattern used itself is prone to this sort of thing since we never check if a component of `temp-getComponentName()` has already has been added or not.  We should probably create a little function to add model components which will check that and warn + delete when it does happen.

I'm less sure about these.  There is an "invalid memory copy" in temperature component / the call to `erf` on this line.  Again I'm not sure why:
<img width="487" alt="temp_comp_erf" src="https://user-images.githubusercontent.com/7440455/158454806-0536876f-500b-4134-9c27-e0fcafe64d04.png">

Finally there is a usage of uninitialized value in ocean_csys:
<img width="731" alt="oceancsys" src="https://user-images.githubusercontent.com/7440455/158455014-7c55214e-fd01-4d6e-999d-5d78743bf288.png">

**To Reproduce**
These were generated using Intel Inspector using the memory issue detector level 2 (again using hector 2.5.0 via GCAM):
```
inspxe-cl -collect mi2 -result-dir ~/intel/inspxe/projects/gcam5.5_mem -- ./gcam.exe -C configuration_ref.xml
```

**Expected behavior**
No memory leak (granted the leak is so small I doubt it would ever amount to anything significant).  I'm not really sure what consequences there are (if any) for the other two.

**Actual behavior**
No memory errors detected.

**Runtime and build environment (please complete the following information):**
 - OS: Linux
 - Boost: 1.76.0
 - R: NA

**Additional context**

**Comment by bpbond** [comment]
👏  nice @pralitp  — thank you! Great idea to run a profiler on it.

Note to self: we should also run a performance profiler.

**Comment by bpbond** [comment]
The performance profile is about what you'd expect: the model spends about one-sixth its time reading in data, one-sixth spinning up, and 60% running.  The carbon cycle solver and the visitors dominate that 60%.

![Screen Shot 2022-03-15 at 7 14 07 PM](https://user-images.githubusercontent.com/1956468/158487538-3cb4f3ae-54f3-47ec-8a86-9ef462cfca03.png)
