### ISSUE TITLE
Documentation v3 push

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#588]
Hi @kdorheim -

@leeyap has extra time the next few weeks and we were talking about making a push to improve and finish the v3 documentation. 

1. Question: how do we _look_ at the built v3 documentation, do you know? When I go to https://jgcri.github.io/hector/ it seems to always be the 2.5 docs, even if I'm on the v3 branch.
2. We will build up our own list, but any suggestions about things you know off the top of your head are missing from the docs?

Thanks.

**Comment by kdorheim** [comment]
This is something that I've been working a lot on lately, I was actually hoping to be able to push a branch today (most likely late afternoon). I could provide some documentation about how to build it to look at it locally, it would be helpful for @leeyap to look through it. 

Some of the outstanding changes I've been working on include expanding the [input files documentation](https://github.com/JGCRI/hector/wiki/InputFiles) could I leave that incomplete with the idea that Leeya could complete the parameter table?

**Comment by bpbond** [comment]
Lol I like that seven-year-old link. @leeyap does that sound good? Yes please Kalyn, both of us would like to know how to build and view the documentation locally—thanks.

**Comment by leeyap** [comment]
Sounds good! Happy to do a general review of the manual contents + anything specific (like the param table)
