### ISSUE TITLE
Input parameters in a centralized CSV

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#590]
Hello @leeyap -

We were wondering if you'd be willing to take something on.

As @kdorheim notes in #588 
>Some of the outstanding changes I've been working on include expanding the [input files documentation](https://github.com/JGCRI/hector/wiki/InputFiles) could I leave that incomplete with the idea that Leeya could complete the parameter table? 

This ☝️ would be super useful: a single CSV that documents all the Hector inputs available from the INI file. It would probably have columns:
* Section
* Parameter
* Biome-specific?
* Time dimension? 
* Required?
* Default value
* Units
* Description

This table would initially be constructed by looking through the INI files; we could then cross-check quickly against the C++ code (I would show you where).

Once it's built, we could then have an R test that would compare it against the _actual_ INI files and flag any entries that don't appear in the table. In addition, the vignette code could use it to auto-generate parameter tables for the documentation.

**Comment by leeyap** [comment]
[input_params.csv](https://github.com/JGCRI/hector/files/8365284/input_params.csv)

Just wanted to link this here, too - first pass at a csv

**Comment by kdorheim** [comment]
Thanks Leeya it is looking good just a few comments 
* atm_ocean_constrain - no longer exists in hector v3, delete from the table 
* @bpbond for the biome-related parameters do we want some way of indicating that the biome name could be anything? 
* N2O_natural_emissions[1750] -- is actually a time series  right now we hold it constant but that has not always been the case
* all of the constraints should have y in the time-variant column 
* Fmisc[1750] -- is time-variant can be set in the ini or in via a csv file 
* @bpbond should we add all of the halocarbon constraints to the table? 

So the next step I think would be to read the csv file into https://github.com/JGCRI/hector/blob/krd_cran_prep/vignettes/articles/InputFiles.Rmd, and use it to populate a parameters table and the input time series table. 

[Here](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html) is a helpful resource for making pretty tables in Rmarkdown.

**Comment by kdorheim** [comment]
@leeyap & @bpbond okay to close?

**Comment by bpbond** [comment]
👍
