### ISSUE TITLE
BC and OC forcings need reworking

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#6]
Major	BC and OC forcings need reworking	N	forcing_component.cpp		Ben		Open

**Comment by cahartin** [comment]
@bpbond I am not 100% sure what you meant by this.  I have changed BC/OC from kg to Tg to better fit with GCAM commit #f79cd76.

**Comment by rplzzz** [comment]
A change like this actually breaks the GCAM interface, which was coded to use the units that Hector was using at the time.  It's easy enough to fix, but it creates a permanent break in compatibility.  Codes using versions of Hector prior to the change need to use one version of the API; codes using subsequent versions need a different version.  Therefore, we really should hold changes like this until we're doing a major release (i.e, a release where we're going to bump the major version, if we're using something like [Semantic Versioning](http://semver.org/)).  It's a lot easier to tell people, "This is the API for Hector v. 2.x," as opposed to "This is the API for Hector versions subsequent to commit #f79cd76."

**Comment by cahartin** [comment]
Sorry about that Robert. I must have misunderstood Kate last week when we were talking about units between hector and GCAM. It's easy to revert back if you think that is best.

**Comment by rplzzz** [comment]
It might be.  Let me see if I can round up Kate to see what she was concerned about.

**Comment by bpbond** [comment]
We should probably include a short version of the semantic versioning spec in the Hector documents, i.e. patch version numbers for bug fixes, etc.; minor version numbers for backward-compatible changes to API/output; major numbers for things that break API/output. That said, technically we're still in 0.x territory, "things may change at any time".

**Comment by rplzzz** [comment]
True, but since we now have some colleagues (Kate, in particular) that are actively using the API we should try to avoid making things hard for them unnecessarily.

**Comment by cahartin** [comment]
I understand now, because we have other people using we don't want too many major changes that will make it harder for them.  What happened was, Kate asked me to run some emissions through the stand alone version of Hector and said that Hector uses the same units as MAGICC, but that wasn't correct for BC/OC.  So I changed Hector units from kg/yr to Tg/yr.

**Comment by rplzzz** [comment]
GCAM provides emissions to climate models, including Hector, in the units that those climate models expect.  Those units may or may not be the same as the units used by GCAM internally or by other climate models.

**Comment by bpbond** [comment]
@cahartin and I put together a documentation page for this, Robert–comments/edits welcome: https://github.com/JGCRI/hector/wiki/VersionNumbers

The one way we will differ from standard semantic versioning, we think, is what "backward compatible" means. Anyway, see that page. Thanks.

**Comment by bpbond** [comment]
Going forward, this will be great to keep in mind and have everyone adhere to. On a related note, one thing let's to do soon, which we've mentioned, is define our "1.0" spec issues and timeline.

**Comment by bpbond** [comment]
…specifically, I'd propose that version 1.0 will correspond to the final version of Corinne's manuscript, currently in final review at GMD.
