### ISSUE TITLE
Atmospheric CO2 returning high values

### ISSUE THREAD

**Issue by leeyap** [JGCRI/hector#617]
Hi @kdorheim and @bpbond, 

When I run a new core and try to extract `atmos_co2`, I'm getting some really high historical values. 

Here's my workflow:
```
library(hector)
ini <- system.file("input/hector_ssp245.ini", package = "hector")
core <- newcore(ini)
run(core)
fetchvars(core, 1960:2020, ATMOSPHERIC_CO2())
```

And some output:
```
Unnamed Hector core 2015 atmos_co2 809.7578  Pg C
Unnamed Hector core 2016 atmos_co2 814.5340  Pg C
Unnamed Hector core 2017 atmos_co2 819.3234  Pg C
Unnamed Hector core 2018 atmos_co2 824.2039  Pg C
Unnamed Hector core 2019 atmos_co2 829.1234  Pg C
Unnamed Hector core 2020 atmos_co2 834.0812  Pg C
```

It looks like this is consistent across scenarios. I'm working on the `v3_dev` branch, I've cleaned and rebuilt Hector, and the latest commit on my machine is a565703. Any idea what's going wrong?

**Comment by kdorheim** [comment]
@leeyap are trying to query the CO2 concentrations?

**Comment by leeyap** [comment]
@kdorheim ohhhhhhh. Yes, apparently! Sorry, didn't know that was what I needed to query.

**Comment by kdorheim** [comment]
As part of resolving the confusion related to atmospheric C we switched to co2 concentrations, try using the CONCENTRATIONS_CO2() function, is that better?

**Comment by leeyap** [comment]
Yes, those numbers look reasonable!

**Comment by bpbond** [comment]
🤦 

Oh okay so `ATMOSPHERIC_CO2()` returns it in _petagrams of carbon_. (Yes @kdorheim I know I agreed and signed off on this.) Oh man, that's going to confuse some folks.

Thank you!!!
