### ISSUE TITLE
Hector crashing with various NBP constraints

### ISSUE THREAD

**Issue by dawnlwoodard** [JGCRI/hector#635]
**Describe the bug**
When running Hector with an NBP constraint, seemingly many constraints break the model by the second half of the century, and some break far earlier. I have just pulled and build the most up-to-date Hector as of the day I submitted this issue.

**To Reproduce**

Here's bash code, essentially doing what the test suite does, to replicate this. First one (with the test constraint) works, the other two fail. The first one that fails just sets NBP to 1.0 Pg C/yr out through 2060. The second sets NBP to the NBP that is produced by running Hector without a constraint under the same climate scenario, so I know the values are reasonable.
 
````
#!/bin/bash
  
HECTOR=./src/hector
INPUT=./inst/input

echo "---------- Running: default test NBP ----------"
sed 's/;[[:space:]]*NBP_constrain=csv:tables\/nbp_constraint.csv/NBP_constrain=csv:tables\/nbp_constraint.csv/' $INPUT/hector_ssp245.ini > $INPUT/hector_ssp245_nbp.ini
if [[ $(diff -q $INPUT/hector_ssp245.ini $INPUT/hector_ssp245_nbp.ini | wc -c) -eq 0 ]]; then exit 1; fi
$HECTOR $INPUT/hector_ssp245_nbp.ini
rm $INPUT/hector_ssp245_nbp.ini

echo "---------- Running: constant 1.0 PgC/yr NBP for 2000:2060  ----------"
sed 's/;[[:space:]]*NBP_constrain=csv:tables\/nbp_constraint.csv/NBP_constrain=csv:tables\/nbp_constant.csv/' $INPUT/hector_ssp245.ini > $INPUT/hector_ssp245_nbp.ini
if [[ $(diff -q $INPUT/hector_ssp245.ini $INPUT/hector_ssp245_nbp.ini | wc -c) -eq 0 ]]; then exit 1; fi
$HECTOR $INPUT/hector_ssp245_nbp.ini
rm $INPUT/hector_ssp245_nbp.ini


echo "---------- Running: Hector's output NBP under SSP245 as constraint for 2000:2100 under SSP245  ----------"
sed 's/;[[:space:]]*NBP_constrain=csv:tables\/nbp_constraint.csv/NBP_constrain=csv:tables\/nbp_output.csv/' $INPUT/hector_ssp245.ini > $INPUT/hector_ssp245_nbp.ini
if [[ $(diff -q $INPUT/hector_ssp245.ini $INPUT/hector_ssp245_nbp.ini | wc -c) -eq 0 ]]; then exit 1; fi
$HECTOR $INPUT/hector_ssp245_nbp.ini
rm $INPUT/hector_ssp245_nbp.ini
````

Running this works fine for the top one but the bottom two fail by apparently driving carbon values negative.

Error from running with the constant constraint:
![image](https://user-images.githubusercontent.com/1285408/181120023-584f6489-0ed2-4444-b8de-9874ab29bad2.png)

Error from running with the output constraint:
![image](https://user-images.githubusercontent.com/1285408/181119928-9f0b678a-78a7-441c-8cd9-25c5f38d3e06.png)

The following R code (duplicating the constant constraint) also fails after 2050:
```
library(hector)
rcp <- "ssp245"
scenario_file <- paste0("input/hector_",rcp,".ini")
ini_file <- system.file(scenario_file, package="hector")

core <- hector::newcore(ini_file, suppresslogging = FALSE)
hector::run(core,runtodate = 2100)

for (i in 2001:2100){
    setvar(core,i,"NBP_constrain",1.0,"Pg C/yr")
    hector::run(core,runtodate = i)
}
```

which results in R unhelpfully crashing entirely:
![image](https://user-images.githubusercontent.com/1285408/181120288-a766a47c-05e1-4421-8edc-36b99e7862a1.png)

 **Supporting Files**
Here are the relevant constraint files. Putting them in the input/tables folder with the other constraints will allow the bash script to run.

[nbp_constraint.csv](https://github.com/JGCRI/hector/files/9193616/nbp_constraint.csv)

[nbp_output.csv](https://github.com/JGCRI/hector/files/9193618/nbp_output.csv)

[nbp_constant.csv](https://github.com/JGCRI/hector/files/9193619/nbp_constant.csv)

**Comment by bpbond** [comment]
This is interesting. I find the proximate problem quickly — we were not correctly handling NBP when the solver stepped to partial (as opposed to complete) years. That fixed the crash issue, and the NBP values match 🎉  but the model climate and carbon cycle still differed. This led me to look hard at `simpleNbox::stashCValues()` and I realized we were mishandling things, again with respect to partial years.
