### ISSUE TITLE
Interpolation behavior

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#643]
## Current behavior

Hector time series (input data that are time-variant) can be marked as interpolation _allowed_ or _not allowed_. The land-use emissions time series allows interpolation, because if the solver stops in 1800.5, we want it to 'see' an annualized LUC value that's halfway between that of 1800 and 1801.

But for a single-year pulse test, as in @dawnlwoodard 's in #639 , this produces **very** undesirable behavior:

```
Fri Oct 28 03:05:33 2022:NOTICE:run: 1799
Fri Oct 28 03:05:33 2022:NOTICE:run: 1800
-----------------------
1800 yf = 1
	luc_e = 10
	veg_c = 558.996 Pg C
	global luc_fva_biome_flux = 2.11675 Pg C
	global veg_c = 556.879 Pg C after luc

Fri Oct 28 03:05:33 2022:NOTICE:run: 1801
-----------------------
1800.5 yf = 0.5
	luc_e = 5
	veg_c = 557.938 Pg C
	global luc_fva_biome_flux = 0.529194 Pg C
	global veg_c = 557.408 Pg C after luc
	
-----------------------
1800.75 yf = 0.25
	luc_e = 2.5
	veg_c = 557.158 Pg C
	global luc_fva_biome_flux = 0.1323 Pg C
	global veg_c = 557.025 Pg C after luc

Fri Oct 28 03:05:33 2022:NOTICE:run: 1802
Fri Oct 28 03:05:33 2022:NOTICE:run: 1803
```

Whoops! When the solver hit 1800, the land emits 10 Pg C of LUC emissions, which is what we wanted...but then another 5 (halfway through the year, so a value halfway between 10 and 0) gets debited in 1800.5 and another 2.5 in 1800.75.

**We've ended up with a total LUC pulse of 17.5 when the input files specified only 10.**

**Comment by bpbond** [comment]
## New behavior

In b6cf6cb we change things so that LUC, FFI, and DACCS are retrieved from their respective time series only _once_, at the beginning of the timestep in `slowparameval()`. These private values — `current_luc_e`, `current_luc_u`, etc. — are then referenced throughout `calcderivs()` and `stashCValues()`. 

```
Fri Oct 28 03:53:53 2022:NOTICE:run: 1799
Fri Oct 28 03:53:53 2022:NOTICE:run: 1800
Fri Oct 28 03:53:53 2022:NOTICE:run: 1801
-----------------------
1801 yf = 1
	luc_e = 10
	veg_c = 558.996 Pg C
	global luc_fva_biome_flux = 2.11675 Pg C
	global veg_c = 556.879 Pg C after luc
Fri Oct 28 03:53:53 2022:NOTICE:run: 1802
Fri Oct 28 03:53:53 2022:NOTICE:run: 1803
Fri Oct 28 03:53:53 2022:NOTICE:run: 1804
```

👍 

This also reduces the code size, which is a nice bonus.

**Comment by bpbond** [comment]
@dawnlwoodard 

![pulse](https://user-images.githubusercontent.com/1956468/198565442-6779be99-32c9-476a-9c7b-98eda2661f36.png)

**Comment by bpbond** [comment]
I am enamored of this LUC pulse test — it's a stringent test of model behavior — that I'm adding it as a permanent test.

**Comment by dawnlwoodard** [comment]
@bpbond OMG THIS EXPLAINS SO MUCH. It never made sense to me that Hector was regrowing *more* carbon than it lost in my pulse experiments, because that isn't how returning to equilibrium should work. But this totally explains it!! So glad you figured it out *and* fixed it!

**Comment by dawnlwoodard** [comment]
Also, that is SO satisfying to see vegetation just drop to a new equilibrium.
