### ISSUE TITLE
Distinguish between atmosphere-land and atmosphere-ocean feedbacks

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#68]
Some climate feedbacks operate mostly over land, which warms faster than the ocean. We'd like to account for this.

Not yet sure if this should be in milestone 1.0 or not.

**Comment by cahartin** [comment]
with the addition of DOECLIM we should be able to "easily" separate temperature over land and ocean to account for the differential warming.

**Comment by kdorheim** [comment]
Adding DOECLIM in Hector v < 2.5 and its integration #562 accounts for the warming rates being different over the ocean & land.
