### ISSUE TITLE
Aerosol radiative forcing

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#700]
Zelinka, Mark D., Christopher J. Smith, Yi Qin, and Karl E. Taylor. 2023. “Aerosol Effective Radiative Forcings in CMIP Models.” https://acp.copernicus.org/articles/23/8879/2023/

* "A weaker negative net ERFari is diagnosed here because the positive absorbing component of ERFSW ari is increased by more than 30% in the present study."
* @ssmithClimate thinks that this might cause changes in BC direct forcing and ERF ACI

(edited to have link to final published paper)

**Comment by ssmithClimate** [comment]
Actually, that was a direct comment from the authors of the paper. Once this is out of peer review we should consider revising our assumptions.

**Comment by kdorheim** [comment]
^ @ssmithClimate, thanks for correcting/clarifying!
