### ISSUE TITLE
Temperature constrained constant after historical period input

### ISSUE THREAD

**Issue by cahartin** [JGCRI/hector#71]
Hector accurately constrains itself to a user supplied temperature time series.  However, after 2013, Hector does not calculate new temperature values, it holds the 2013 value constant out to 230.  I have added a tgav_historical.csv file

**Comment by bpbond** [comment]
Note this is tied to issue #15 re constraints and extrapolation.

**Comment by bpbond** [comment]
I didn't test this, but should be fixed in 48a49212ea.
