### ISSUE TITLE
RF scalar effect not reported in respective output 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hector#743]
Adjusting RF using the volscl and alpha does not affect the RF_vol or RF aerosol results returned as output, it does have the intended effect the global temp. 

## Changing volscl 
![image](https://github.com/JGCRI/hector/assets/27299759/480b0b06-16b8-4dd6-b3af-6c2a43ab34d4)

## Changing alpha 

![image](https://github.com/JGCRI/hector/assets/27299759/bde9c7bc-2847-4e6d-a567-98266fa4b2d7)

This seems incorrect; I would think that we would want the RF values to reflect what the temperature component is seeing... It is because we adjust the total forcing in the temperature component [here](https://github.com/JGCRI/hector/blob/1ef0b4df8563a31580ffa94eb11b113e3f317b86/src/temperature_component.cpp#L469) instead of in the forcing component.

**Comment by bpbond** [comment]
Agreed.

**Comment by ssmithClimate** [comment]
Note that it will be important to point this out to users that these parameters have moved.

Question: Will hector throw an error if an undefined parameter is read in the .ini file? (e.g. if a user uses an old .ini file with these parameters in the wrong place?)

**Comment by ptrscll** [comment]
I just checked, and Hector does throw an error. When using an old .ini file, I got the following error message:

```
Error: While parsing hector input file C:\Users\scul468\Documents\repos\hector-run-archive\hector-V3.2.0\input\hector_ssp245.ini: msg:  	Could not parse var: volscl - Unknown variable name while parsing temperature: volscl
func: 	setData
file: 	temperature_component.cpp
ffile:	temperature_component.cpp

line: 	189
```

**Comment by kdorheim** [comment]
@ssmithClimate, and for that reason, this would be merged into dev and would be part of a larger release since it would be a code-breaking change!
