### ISSUE TITLE
Remove documentation folder

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#77]
Hey @rplzzz @cahartin I've put the Hector wiki into the main repository as a submodule (so it'll reflect wiki changes, and can be archived into the 1.0 release). Can we delete the `documentation` folder at this point, which I think is 100% redundant?

**Comment by cahartin** [comment]
@bpbond sounds good to me.

**Comment by rplzzz** [comment]
We definitely need to get out from under having two redundant sets of documentation that we have to keep synchronized; however, I think it is useful to have at least the build and installation instructions self-contained in the repository.  Somehow I always find myself trying to build new software from airplane seats or other places with no network access.  Maybe we could just add the bare bones to a README or INSTALL file in the top-level directory, with a note that the self-contained instructions are updated only for major releases and providing a link to the online documentation.  What do you think?

**Comment by bpbond** [comment]
But all the wiki docs now come bundled in the repository (see `wiki/`), including all build instructions, etc. Doesn't this address this concern?

**Comment by rplzzz** [comment]
Maybe.  It doesn't seem to be 100% automatic (the wiki directory in my repo is empty, for example).  I'll try to figure out if it's something specific to my repo, or a more general problem.

**Comment by bpbond** [comment]
Hmm, no, you're right. It's straightforward to do this from the command line (`git clone --recursive`) but this doesn't happen by default if people naively clone from the Github web page.

**Comment by rplzzz** [comment]
In that case, we just need to add that tip to the repository README, which people will presumably see when they try to figure out how to download the code for the first time.

**Comment by bpbond** [comment]
Agreed. I have changed `README.md` and removed the folder in commit 3dcb76ffef.
