### ISSUE TITLE
Include sample output files in repository

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#78]
Specifically, the ones that used in final published paper.

**Comment by bpbond** [comment]
@cahartin see sample output files added to repo - you will need to overwrite these with final versions.

**Comment by bpbond** [comment]
Let me know when you do this @cahartin and then we'll post the 1.0 release? The license (issue #28 ) is the only other open issue for this milestone.

**Comment by cahartin** [comment]
@bpbond

**Comment by cahartin** [comment]
@bpbond 4 rcps outputstream files have been added

**Comment by bpbond** [comment]
Thanks though I have renamed them in commit 987d1acfac - we don't want `git` tracking the standard model outputs.
