### ISSUE TITLE
Units in input files

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#79]
@pralitp implemented this, and provided a demonstration of it (as I remember). We want to extend this to all inputs–units can be (optionally) provided as a check.

**Comment by bpbond** [comment]
See also #88

**Comment by rgieseke** [comment]
Is this syntax an example of this check?
https://github.com/JGCRI/hector/blob/master/input/hector_rcp26.ini#L183

    H0=35.0,pptv ; preindustrial concentration, pptv

**Comment by bpbond** [comment]
Yes.

**Comment by rgieseke** [comment]
Thanks! Then we will try to have a similar option in our wrapper (cc @swillner) !

**Comment by bpbond** [comment]
This seems like it'd be laborious and not worth the gain. OK to close @kdorheim ?
