### ISSUE TITLE
Testing code - get it working again

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#82]
Marking this as a bug. It really needs to happen.

**Comment by rplzzz** [comment]
I have some deadlines coming up on other projects, but once those are past I'd like to tackle this.

**Comment by rplzzz** [comment]
I think we should be able to get this in to v1.2.

**Comment by rplzzz** [comment]
I think we should be able to get this in to v1.2.  It's also a prerequisite to #61, which I believe is on the 1.2 list.

**Comment by bpbond** [comment]
Note that Boost (at least the v1.6.0 I downloaded today) includes unit testing framework `boost::test`. In the spirit of reducing dependencies, let's investigate changing from googletest to this.

**Comment by bpbond** [comment]
Also see https://github.com/philsquared/Catch - a header-only testing framework

**Comment by rplzzz** [comment]
Replacing google test works for me.  I'll take a look at the Boost framework and see what it has to offer.

**Comment by bpbond** [comment]
Thanks @rplzzz . I have nothing against the googletest framework per se, but worth checking it (Boost) out.

**Comment by rplzzz** [comment]
I've been using the googletest framework in another project, and it works pretty well, but the installation guide cautions you against installing the library in a central location and linking against it.  Apparently, that can cause failures.  So, you're supposed to build it separately for each project that's using it, which is no big deal if you have only one such project, but it's a huge hassle if you have a lot of them.  What we really want is something that works more or less the same as googletest but without the goofy build requirements.

**Comment by ashiklom** [comment]
Necrobump! Now that Hector is an R package, how much of this is covered by the `testthat` tests? In other words, can this be closed?

**Comment by bpbond** [comment]
> Necrobump 

Hahaha. Yeah, I think so. Thanks.
