### ISSUE TITLE
Add second remote (e.g. Bitbucket) for redundancy

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#83]
See:

The 7 Rules for Writing Software That Won’t Die When You Do
https://medium.com/@karan/the-7-rules-for-writing-software-that-wont-die-when-you-do-38ef0a925650

**Comment by rplzzz** [comment]
Added to the PNNL bitbucket server.  Unfortunately, I couldn't find a good way to sync automatically, so it's on us to do manual synchronization from time to time.
