### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#89]
Now that we've got the external API merged in, should we consider making a new release?  We've added some pretty extensive new features that some users might want to know about.  On top of that, I'd like to be able to change the GCAM build from pointing at a 'gcam' branch in the repository to pointing at a release.  

Thoughts?

**Comment by bpbond** [comment]
Sounds reasonable. How about you, @cahartin and I take a half hour next week to go over changes made, to-do checklist, etc.?

**Comment by cahartin** [comment]
that's a good idea.  I'm available.

**Comment by bpbond** [comment]
I would still like to update the backend R scripts before release 1.1 (cf #94 ) but let's say I only have this week to do so. If I don't get to it, we'll proceed with the 1.1 release regardless. OK?

**Comment by rplzzz** [comment]
This issue is also blocking on #90.  I jumped the gun in more ways than one when posting that other issue.  I'll see what I can do on that one later this week.

**Comment by bpbond** [comment]
All remaining issues w.r.t. this milestone (v1.1) are closed now. Are we good to go? @rplzzz @cahartin

**Comment by rplzzz** [comment]
I think so.  Let me merge the latest updates into the rc1.1 branch.  We can take the discussion over to PR #96
