### ISSUE TITLE
Fix H_ASSERT in visual studio

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#9]
Major	Fix H_ASSERT macro to allow the + on the string in visual studio	N	h_exception.hpp		Corinne	Ben/Pralit	Open

**Comment by cahartin** [comment]
Hey @pralitp do you mind look at this sometime in the next month? We figured you don't have enough work to do, really

**Comment by rplzzz** [comment]
So, what is the issue here again?  As far as I know, we are building correctly under visual studio, right?  Did we find some kind of workaround for this problem?

**Comment by pralitp** [comment]
I believe we worked around it. If i remember correctly the crux of the
issue was that the H_ASSERT macro was "overloaded" to either accept just
the assertion or in addition a message. Ben wrote some macro code to choose
which didn't work right in Visual Studio. I could look into it again
although macros are not my strong suit.

Pralit

**Comment by rplzzz** [comment]
Awesome.  Could you take a quick look?  If what we've got is working well enough, then we can just mark this one done.  Also, @cahartin, you're the principal Windows user, right?  Is this issue still a problem?

**Comment by bpbond** [comment]
That's right @pralitp - VS didn't like conditional macros. The simplest things may be to disallow their use throughout the code, and just have fixed-param H_ASSERTs.

**Comment by cahartin** [comment]
I am pretty sure we had made a work around for this and fixed the issue.  Everything works on my end.

**Comment by rplzzz** [comment]
Ok, then I'm calling this one done.
