### ISSUE TITLE
Slack integration - FYI

### ISSUE THREAD

**Issue by bpbond** [JGCRI/hector#97]
Hey @rplzzz @cahartin :

Kate and I are testing out how useful the [Slack](http://slack.com) messaging system is, and as part of that we've integrated this repository into one of our 'channels' (see image), so all issues, commits, etc. are being posted there. This is FYI.

![screen shot 2015-08-19 at 11 15 24 am](https://cloud.githubusercontent.com/assets/1956468/9360379/e50c1162-4663-11e5-9bf1-b592958ea5b0.png)

**Comment by rplzzz** [comment]
Noice.

**Comment by bpbond** [comment]
It's f'ing slick.

**Comment by rplzzz** [comment]
It looks like you have to be invited to a team to join it.

**Comment by bpbond** [comment]
True. Interested in trying?

**Comment by rplzzz** [comment]
:ok:
