### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/hector#98]
I've been cleaning up some stale branches.  Most of the offenders were mine, so I just made an executive decision to get rid of them.  The only one left is revert-46-winfix, which has one unmerged commit (75d3ef98975e87e71640e08d74a067fd9b4ea3b4) from back when we were trying to deal with the lack of unistd.h on Windows.  I believe we fixed this in another branch, but I'm not 100% sure.  

Corinne, it looks like your branch.  Could you decide whether it can be deleted or merged?

**Comment by cahartin** [comment]
hum....it looks like this change was not committed and is not in the current master branch.  Everything runs fine on my end now, so I'm not sure if we should merge that change in or not?

**Comment by rplzzz** [comment]
If the current HEAD builds under Windows, then that means we fixed it in another branch and we should delete this one.

**Comment by cahartin** [comment]
Actually, I wasn't fully synced up before.  For some reason now I need to include #include <algorithm> in the logger.cpp in order to build. Can I commit this change?

**Comment by rplzzz** [comment]
Could you make a branch for the hotfix, commit there, and make a pull request for the branch?  That way Ben or I can give the change a quick review and get it onto the current master.

**Comment by bpbond** [comment]
Yes - let's make this our standard operating procedure when committing to `master`: only via pull requests, which triggers a code review (even quick and informal) by someone else. Generally no one should commit directly to the master HEAD.

Via @rplzzz see http://scottchacon.com/2011/08/31/github-flow.html

**Comment by cahartin** [comment]
sounds good. thanks.

**Comment by cahartin** [comment]
i am going to delete this branch.
